### ISSUE TITLE
WHERE OR CAUSE

### ISSUE THREAD

**Issue by shakson** [joshcam/PHP-MySQLi-Database-Class#108]
Hi guys, i cant find the way how to use WHERE OR  clause.
If I want to make query like this:

SELECT * FROM user WHERE (username='test' AND password='abcd1234') OR (username="test1" AND password="abcd4321")

How can i accomplish this with this class? I should use raw query?

**Comment by avbdr** [comment]
thats also landed $db->where ("a=1 or b=3");

could be closed
