### ISSUE TITLE
FILTER_SANITIZE_STRING stripping "<" and text after it

### ISSUE THREAD

**Issue by qahar** [joshcam/PHP-MySQLi-Database-Class#131]
Cannot use `<=` comparison in rawQuery due the FILTER_SANITIZE_STRING

Just a suggest, if it's unavoidable feature to sanitize, at least give us option to not use it and aware of own consequence.

    public function rawQuery($query, $bindParams = null, $sanitize = true)
    {
        if ($sanitize) {
            $this->_query = filter_var ($query, FILTER_SANITIZE_STRING,
                                        FILTER_FLAG_NO_ENCODE_QUOTES);
        } else {
            $this->_query = $query;
        }

        ...
    }

Thanks n keep up the good work

**Comment by cybercussion** [comment]
Thanks I was running into this with a between dates statement and took me a bit to backtrace why it was an issue.
