### ISSUE TITLE
can you make pergination?

### ISSUE THREAD

**Issue by nonnyohiyo** [joshcam/PHP-MySQLi-Database-Class#140]
http://code.tutsplus.com/tutorials/how-to-paginate-data-with-php--net-2928

**Comment by fatihtoprak** [comment]
it doesnt work for me .

**Comment by NazgulTuga** [comment]
Please, re-use the code. If it doesn't work as it is, change it.

**Comment by fatihtoprak** [comment]
now total page numbers display correctly what about the paginate links ? thanks.

**Comment by PetengDedet** [comment]
Hi, checkuout my pagination function
https://github.com/PetengDedet/PHP-MySQLi-Database-Class/blob/master/pagination.php

**Comment by afuno** [comment]
Thank U. Tried many classes today. You turned out to be the best.



Включено 16 января 2015 г. в 21:49:59, Peteng Dedet (notifications@github.com) написал:

Hi, checkuout my pagination function
https://github.com/PetengDedet/PHP-MySQLi-Database-Class/blob/master/pagination.php

**Comment by fatihtoprak** [comment]
@PetengDedet thanks for the simple tip. ;)

**Comment by avbdr** [comment]
added in master
