### ISSUE TITLE
mysqli, on duplicate key update

### ISSUE THREAD

**Issue by gintares** [joshcam/PHP-MySQLi-Database-Class#141]
How to write several " insert, on duplicate key update" sentences in single query.

This string does not work. Where is my mistake?

str2= INSERT INTO `tprice_1` (`tcday`, `tcwday`, `tcstatus`, `tcprice` ) 
VALUES 
('2014-08-09', 6, '10_000_000_000_000', NULL) ON DUPLICATE KEY UPDATE tcday='2014-08-09', tcwday=6, tcstatus='10_000_000_000_000', tcprice=NULL, 
('2014-08-10', 0, '10_000_000_000_000', NULL) ON DUPLICATE KEY UPDATE tcday='2014-08-10', tcwday=0, tcstatus='10_000_000_000_000', tcprice=NULL, 
('2014-08-11', 1, '10_000_000_000_000', NULL) ON DUPLICATE KEY UPDATE tcday='2014-08-11', tcwday=1, tcstatus='10_000_000_000_000', tcprice=NULL;

**Comment by avbdr** [comment]
fixed in master
