### ISSUE TITLE
Constructor using Mysqli object

### ISSUE THREAD

**Issue by arieffikhrie** [joshcam/PHP-MySQLi-Database-Class#148]
Adding an overload constructor that have parameter of Mysqli object only.
Since im continuing old project. They have already have the connected Mysqli object.

for example
````
$con = new mysqli('localhost','root','password','db');
$db = new Mysqlidb($con);
````

Currently im just adding another parameter on the constructor 
````
public function __construct($host = NULL, $username = NULL, $password = NULL, $db = NULL, $port = NULL, $connection = NULL )
````
if the $connection is not null
````
  $this->_mysqli = $connection
````
create mysqlidb
````
$db = new MysqliDb(NULL, NULL, NULL, NULL, NULL, $con);
````

Well it work for get function. never tried with another complex one yet

**Comment by avbdr** [comment]
master have this option already.
