### ISSUE TITLE
Support for insert() without an insert id

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#150]
I'm having a problem with inserting into this table:

```sql
CREATE TABLE `read_notices` (
  `ownerid` int(11) NOT NULL,
  `noticeid` int(11) NOT NULL,
  `read` datetime NOT NULL,
  KEY `IDX_MAIN` (`ownerid`,`noticeid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
```

The reason is that unlike `update()`, `insert()` does not contain this line:

```js
$this->count = $stmt->affected_rows;
```

Therefore, inserts without an insert id end up returning 0. For these inserts, checking `count` would suffice to know that the insert succeeded, if `count` were set.

Suggestion:  please set `count` after an `insert()`

Thanks!

**Comment by avbdr** [comment]
thank you, fixed. fix also adds count handling.
