### ISSUE TITLE
UPDATE with CASE, WHEN and THEN

### ISSUE THREAD

**Issue by smithfoto** [joshcam/PHP-MySQLi-Database-Class#152]
foreach ($data as $key => $val) {
   $str.= " WHEN $key THEN $val ";
   $ids[] = $key;
}
$keys = implode(",", $ids);

// rawQuery WORK
   $q = "UPDATE 
                 ct_content_category
            SET
                ordering = CASE id {$str} ELSE ordering END
            WHERE
               id IN($keys)
	    ";
   $db->rawQuery($q);

========================================
// update NOT WORK
$data = Array(
                      'ordering ' => "CASE id {$str} ELSE ordering END"
             );
   $db->where('id', $keys, 'IN');
   $db->update('content_category', $data);

**Comment by avbdr** [comment]
this should work with $db->func() now.
