### ISSUE TITLE
Cleaner getLastError()

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#155]
Might be just my preference, but I find the implementation of getLastError() to be harder to use than it could be. Currently:

```php
return $this->_stmtError . " " . $this->_mysqli->error;
```

Which means that even if there is no error, you will always get a " " (blank) back. I think the API would be cleaner if the caller didn't have to remember to apply trim() to the result every time.

**Comment by avbdr** [comment]
fixed
