### ISSUE TITLE
function connect, die error not showing on invalid credentials

### ISSUE THREAD

**Issue by AlexanderSk** [joshcam/PHP-MySQLi-Database-Class#156]
Hello,
I am just testing on a localhost and while issueing wrong credentials for the connector i discovered the the "or die('There was a problem connecting to the database');" part is not working.
   
 public function connect()
    {
        if ($this->isSubQuery)
            return;

        $this->_mysqli = new mysqli ($this->host, $this->username, $this->password, $this->db, $this->port)
            or die('There was a problem connecting to the database');

        $this->_mysqli->set_charset ('utf8');
    }

While searching a bit i came up with this fix:

    public function connect()
    {
        if ($this->isSubQuery)
            return;

        $this->_mysqli = @new mysqli($this->host, $this->username, $this->password, $this->db, $this->port);

		  if ($this->_mysqli->connect_error) {
			  die('Connect Error, '. $this->_mysqli->connect_errno . ': ' . $this->_mysqli->connect_error);
		  }

        $this->_mysqli->set_charset ('utf8');
    }

Can you please confirm? :)

**Comment by avbdr** [comment]
thanks, late but fixed :)
