### ISSUE TITLE
Create a clone of the PHP-MySqliDatabaseClass for the mssql provider

### ISSUE THREAD

**Issue by RPDeshaies** [joshcam/PHP-MySQLi-Database-Class#160]
Most of the time, when you create a website/web application, you do it for a client.

Sometimes, these clients are using Microsoft technologies (for many great reasons) for their main application (that contains all their data).

But, they also want to have a website using **PHP** and **MySQL** with a CMS like **Wordpress** or things like that.

Since writing `SQL` code with PHP-MySqliDatabase-Class looks better than raw `SQL` (at least for simple queries), I think it would be nice to have the same class but for the **Microsoft Sql Server provider (mssql)**.

**Comment by avbdr** [comment]
closing as a dup of #356
