### ISSUE TITLE
Call to a member function real_escape_string() on null

### ISSUE THREAD

**Issue by abunour22** [joshcam/PHP-MySQLi-Database-Class#164]
i try to create extend of class for my own functions as ( login functions , register functions etc.. ) 

using this 
class FDKDB extends MysqliDb {
                public function CreateLoginHistory($username,$userID)
		{
			$username = $this->escape($username);
			$userID= $this->escape($userID);
                           // Do Anything
			return //Anything;
		}
}
but it returns this error:
Fatal error:  Call to a member function real_escape_string() on null in C:\AppServ\www\abc\includes\class_mysqli.php on line 485

but when i make it direct before use CreateLoginHistory() function .. it return true !! 

what should i do to extend it with right way ?!

**Comment by avbdr** [comment]
i think you have your own constructor in FDKDB which is not calling parent constructor.
