### ISSUE TITLE
$db->where('(field = ? OR field = ?)',array(x,y)); - Missing Last ) in query

### ISSUE THREAD

**Issue by KTP95** [joshcam/PHP-MySQLi-Database-Class#166]
Hi, my script

i add a function to build better where .. to your class, check if valid, maybe can add to publish:

	public function where_one_of($whereProp, $whereValue = null)
    {
		$subwhere = array_fill(0, count($whereValue), $whereProp.' = ?');
		$subwhere = implode($subwhere,' OR ');
		$subwhere = '('.$subwhere.')';
		// so "$subwhere" is like as "(id = ? or id = ? or .... id = ?)"
		$this->where($subwhere, $whereValue);
		return $this;
    }

This, work right.. so i write ...script:

	$db->where('expire_ban' ,'CURDATE()','>');
	$db->where_one_of('site_id',array(3,2,4,5));
	$db->getOne ('banned');
        echo $db->getLastQuery();

output is 

SELECT * FROM prefix_banned WHERE expire_ban > CURDATE() AND (site_id = 3 OR site_id = 2 OR site_id = 4 OR site_id = 5

...the last char isn't ")" ...this is the bug, BUT.....if script is

	$db->where_one_of('site_id',array(3,2,4,5));
	$db->where('expire_ban' ,'CURDATE()','>');
	$db->getOne ('banned');
        echo $db->getLastQuery();

so work...
please, check it

**Comment by avbdr** [comment]
your last example have an extra closing.
should be
db->where( ' (koko=? OR koko = ? ) AND (toto = ? OR toto = ?)', array(1,2,3,4))
