### ISSUE TITLE
How to get different column names?

### ISSUE THREAD

**Issue by magicmind** [joshcam/PHP-MySQLi-Database-Class#176]
Imagine this:

$dbAgil = new MysqliDb ( DBHost, $dbSettings['DBuser'], $dbSettings['DBpass'], $dbSettings['dbAgil']); //$DBThings['dbAgil']);

    $dbAgil->join('sys_grupos sg', 'sg.id_group = su.id_group', 'LEFT');
    $dbAgil->join('sys_users_empresas sue', 'su.id_user = sue.id_user', 'LEFT');

    $dbAgil->where('sg.isnotdeleted',1);
    $dbAgil->where('sue.isnotdeleted',1);
    $dbAgil->where('su.isnotdeleted',1);
    $dbAgil->where('sg.ativo',1);
    $dbAgil->where('su.ativo',1);

    $dbAgil->where('sue.id_empresa' ,$_SESSION['UserData']['Empresa']);

    $grupos = $dbAgil->get('sys_users su');
   
Now.. empresas and 'grupos' both have a "design" field.. so how do I change one of them to klet's say, GrupoDesign?

thanks.
Fernando

**Comment by avbdr** [comment]
closing
