### ISSUE TITLE
Function option for where

### ISSUE THREAD

**Issue by Mystery-X** [joshcam/PHP-MySQLi-Database-Class#181]
Looks like function options like "$db->func('SHA2(?,512)',Array ($password))" are limited to insert and update.
Would it be positble to use it in where function too? like $db->where ('user_pass', $db->func('SHA2(?,512)',Array ($password)));

**Comment by afuno** [comment]
It's cool. Thank you again. I will try to use this class maximum.



Включено 16 января 2015 г. в 23:11:00, Mystery-X (notifications@github.com) написал:

Looks like function options like "$db->func('SHA2(?,512)',Array ($password))" are limited to insert and update.
Would it be positble to use it in where function too? like $db->where ('user_pass', $db->func('SHA2(?,512)',Array ($password)));

**Comment by avbdr** [comment]
the following notation should also work. 
$db->where ('user_pass = SHA2 (?,512)', Array ($password));
Looks cleaner I believe

**Comment by Mystery-X** [comment]
When i try it like you sugested avbdr i get this error :
Fatal error: Problem preparing query (SELECT * FROM admin_users WHERE user_login = ? AND user_pass = SHA2 (?,512) LIMIT 1) Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' in /var/www/domains/predb.homeip.net/public_shtml/libs/MysqliDb.php on line 863

**Comment by avbdr** [comment]
i dont think this is a problem of the library. Looks like encoding issues in the database; 
try to execute this query in the sql console. SELECT * FROM admin_users WHERE user_login = ? AND user_pass = SHA2 (?,512) LIMIT 1

**Comment by Mystery-X** [comment]
Is there a way to tell the class to use charset latin1_swedish_ci because i think it's hardcoded to utf8 now?

**Comment by avbdr** [comment]
oh, indeed. try to find line set_charset ('utf8'); and remote it or modify to a correct encoding. I will work out a proper setter if that will help.

**Comment by Mystery-X** [comment]
i commented it out and it works now, thx

**Comment by avbdr** [comment]
latest version of the library allows to change charset in constructor. Fixed

**Comment by leigh-ols** [comment]
Although the suggested method works it would be nice to do something like:

```php
$pass = $db->func('SHA2(?,512)', array($password));
$db->where('password', $pass);
```

Something like this would allow dynamic encoding of certain fields:

```php
class DBTest
{
    /**
     * Array of field keys that should always be encoded
     *
     * @var array
     */
    protected $encoded_fields = array('password');

    /**
     * Generic select method
     *
     * @param array $where_values Array('field_name', 'value');
     *
     * @return void
     * @access public
     */
    public function selectWhere($where_values) {
        $key_values = $this->encodeData($data);

        foreach ($key_values as $k => $v) {
            $this->db->where($k, $v);
        }
    }

    /**
     * encodeData
     *
     * @param array $data Array('field_name', 'value')
     *
     * @return array
     * @access public
     */
    public function encodeData($data)
    {
        foreach ($data as $k => $v) {
            if (in_array($k, $this->encoded_fields)) {
                $data[$k] = $this->db->func('SHA2(?, 512)', array($v));
            }
        }

        return $data;
    }
}

$db_test = new DBTest();
$db_test->selectWhere(array('username' => $user, 'password' => $pass));
```

This type of thing is already possible with inserts and updates, but not at present easily accomplished with clauses.
