### ISSUE TITLE
order by rand() missing

### ISSUE THREAD

**Issue by gomcodoctor** [joshcam/PHP-MySQLi-Database-Class#185]
thanks for creating wonderful class,
order by rand() function is missing which I have created using following

changing protected function _buildOrderBy to following

    protected function _buildOrderBy () {
        if (empty ($this->_orderBy))
            return;
        $this->_query .= " ORDER BY ";
        foreach ($this->_orderBy as $prop => $value)
        {
            if($prop == "RAND") $this->_query .= "rand(), ";
            else $this->_query .= $prop . " " . $value . ", ";
        }

        $this->_query = rtrim ($this->_query, ', ') . " ";
    }
    
and now using $db->orderBy("RAND","asc");

**Comment by avbdr** [comment]
pushed to https://github.com/avbdr/PHP-MySQLi-Database-Class.git with some modifications.

thank you.

**Comment by gomcodoctor** [comment]
thanks a lot :)
