### ISSUE TITLE
SELECT not working with mysql LONGTEXT type

### ISSUE THREAD

**Issue by BlackScript** [joshcam/PHP-MySQLi-Database-Class#186]
Get error when using longtext type and try to select it

**Comment by KTP95** [comment]
confirm
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4294967296 bytes) in /var/www/xxxxxxxx/public_html/wp/xxxxxx/MysqliDb.php on line 628

**Comment by KTP95** [comment]
I see better,
is the same error that here
https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119

solution: (with fast test it work, but please try better).

edit LINE 625 in MysqliDb.php:

        // avoid out of memory bug in php 5.2 and 5.3
        // https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119
        if (version_compare (phpversion(), '5.4', '<'))
             $stmt->store_result();

        call_user_func_array(array($stmt, 'bind_result'), $parameters);

in 

        // avoid out of memory bug in php 5.2 and 5.3
        // https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119
        $stmt->store_result();

        call_user_func_array(array($stmt, 'bind_result'), $parameters);

**Comment by gregtampa** [comment]
remove longtext type field and make sure your varchar are assigned lengths

**Comment by avbdr** [comment]
dup of https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/188
