### ISSUE TITLE
allowed memory size

### ISSUE THREAD

**Issue by gregtampa** [joshcam/PHP-MySQLi-Database-Class#188]
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

PHP Fatal error: Allowed memory size of 1077936128 bytes exhausted (tried to allocate 4294967296 bytes) in /data/dev/www/php/MysqliDb.php on line 628

function getMerchantsofAgents($agent_id){
global $db;
//$db->where("affiliate_id",$agent_id);
$data = $db->rawQuery("SELECT * FROM merchants WHERE affiliate_id = 17");
return $data;
}
var_dump(getMerchantsofAgents('17'));
same error.. works for some statements but others no worky...

however if i put in the fields of the table then it will work..
function getMerchantsofAgents($agent_id){
global $db;
	$cols = Array ("idmerchants", "merchant_name", "is_active");
	$db->where("affiliate_id",$agent_id);
    $data = $db->get("merchants", null, $cols);
	return $data;
}

$getMerchantsofAgents = json_encode(getMerchantsofAgents('17'));
echo $getMerchantsofAgents;

works

**Comment by gregtampa** [comment]
Looks like if the table has a longtext type field this error will occur.

**Comment by avbdr** [comment]
can anybody provide a reproducible testcase for this? I mean query + sample table structure + sample data?

**Comment by azizjassar** [comment]
hello, i have the same issue 

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 79 bytes) in /home/links/public_html/classes/db.php on line 628

and i tried several solutions:
like this : https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/186

but nothing changed. please help

**Comment by avbdr** [comment]
more info in https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/79. closing
