### ISSUE TITLE
any support for SELECT FOR UPDATE?

### ISSUE THREAD

**Issue by curt2008** [joshcam/PHP-MySQLi-Database-Class#190]
I'm attempting to use this class for utilising the SELECT FOR UPDATE syntax in mySQL although it doesn't seem to support this, here's my query which seems to fail everytime

```mysql
SELECT *
FROM web_crawler
WHERE being_scanned = DATE_SUB(NOW(),INTERVAL 20 SECOND)
AND last_scanned < '0'
ORDER BY priority DESC
LIMIT 1
FOR UPDATE;
```

Is their any functions we can use instead of trying to do RawQuery which makes this fail?

**Comment by PetengDedet** [comment]
According to  [this](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/8) the 'rawQuery()' fails on this case is because of the class uses "FILTER_SANITIZE_STRING" to remove the unsafe characters such as '<'.

**Comment by avbdr** [comment]
https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/30#issuecomment-72958277

**Comment by avbdr** [comment]
I think for a queries like this its better to use rawQuery as building an orm syntax like this will be even more messy :)

**Comment by avbdr** [comment]
just added this to master. fixes
