### ISSUE TITLE
I want the returning data as object, not an array

### ISSUE THREAD

**Issue by Farhan5** [joshcam/PHP-MySQLi-Database-Class#191]
$x = $db->get('tbl');
foreach($x as $y)
{
   // $y->z; won't works
   // echo $y['z']; works fine

   // I don't know where to edit also Im using phone, how to do this?
}

And I read rawQuery fails for some comparison operators.
Is it ok now? not? any bypassing way withing this library?

**Comment by PetengDedet** [comment]
The get() method returns the multilevel array. The first array is the row affected by the query. The second array is the column for each row.
So if you want to access the object, try this:
```php

$x = $db->get('tbl');

echo $x[0]['column'];  //the value of column only in first row

foreach($x as $y){
        echo $x[0]['column']; //value of column each affected row
}

foreach($x as $y){
        print_r($y); //every value of every column in each affected row
}
```

**Comment by Farhan5** [comment]
I am using prepared mysqli for the first time. I don't know much about it. I've tryed to edit the class to return objects with no luck.

Also I want to know,

Why its necessary to return multidimentional array? What would happen (or which data would I miss) if its a simple array? 

I want objects as I don't have to write much codes (e.g $x['z'] > $x->z in letters) So how its possible to get an object from the class?

**Comment by avbdr** [comment]
i believe you need to learn PHP deeper (as well to understand how multiple rows in the table could be stored in the single row of result) or to switch to another library like doctrine.

**Comment by avbdr** [comment]
i believe switching to doctrine wont save you from learning PHP deeper

**Comment by Farhan5** [comment]
The problem is, Im using phone as Im out of my home now. So every time I have to update script, then open in browser to check what has done. And this is painful process for debugging, it should be real time with an ease editing facility. Thats why I asked. But you are right, I didn't look deeper for sql things, as freely available libraries can do it easily.

So thats mean, there is no other ways to get an object with this method?

Thanks in advance.
