### ISSUE TITLE
Problem in Chaining

### ISSUE THREAD

**Issue by abelvieira** [joshcam/PHP-MySQLi-Database-Class#192]
Hi,

I have a strange situation here...

In this code:
<code>
$db->where("supplier_id = ? AND article_id = ? AND brand_id = ?",array((string)$request->supplierId,(string)$request_art->articleId,(string)$request_art->brandId));
$article=$db->getOne("availability");
</code>
all works.

But if i use:
<code>
$article=$db->where("supplier_id = ? AND article_id = ? AND brand_id = ?",array((string)$request->supplierId,(string)$request_art->articleId,(string)$request_art->brandId))->getOne("availability");
</code>
i have a 500 internal server error

**Comment by avbdr** [comment]
should be working just fine. Can you try latest master?

**Comment by avbdr** [comment]
closing this for missing information
