### ISSUE TITLE
Am I doing something wrong with the IN array() query? 

### ISSUE THREAD

**Issue by ramjamx** [joshcam/PHP-MySQLi-Database-Class#193]
Im trying to select some image information from $imageTable, but instead I only get the first item in array

```
 $db -> where('ID', '28,27,26,25', 'IN');
					 $imageQuery = $db->get($tableImages);

					 foreach($imageQuery as $imageInfo){
						 echo "image_url: ".$imageInfo['image_url'];
					 }
```

I want to get info from IDs 28, 27,26,25 not only 28.
Please if you know what I'm I doing wrong give me some help.

Thank you.

**Comment by avbdr** [comment]
ids should be an array.
 $db -> where('ID', Array(28,27,26,25), 'IN');

**Comment by ramjamx** [comment]
If I put an array like that, i just get a fatal error.

like this:
```
Fatal error: Problem preparing query (SELECT * FROM cms_images_data WHERE ID 0 ?) 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL 
server version for the right syntax to use near '0 ?' at line 1
 in /path/to/site/html/bin/mysqli.db.class.php on line 615
```

**Comment by avbdr** [comment]
try to upgrade your library to the latest version.

**Comment by ramjamx** [comment]
Greeeat! that solve my problem . Thank you Alexander (avdbr). 

*shame on me*
