### ISSUE TITLE
Subquery in join

### ISSUE THREAD

**Issue by Ettemlevest** [joshcam/PHP-MySQLi-Database-Class#195]
Is there a way to put a subquery into a join? I'm trying to figure out what is my mistake. Here's my raw query that I would like to convert:
```
SELECT m.*, kapcsolattartok
FROM megbizok m
	LEFT JOIN (
		SELECT k.megbizo_id, COUNT(k.kapcsolattarto_id) AS kapcsolattartok FROM megbizok_kapcsolattartok k GROUP BY k.megbizo_id
	) AS k ON m.megbizo_id = k.megbizo_id
WHERE
	m.torolve = 0
ORDER BY m.megbizo_megnevezes, m.megbizo_azonosito
```
This is how I tryied it with PHP-MySQLi-Database-Class:
```
$kapcsolattartok = $db->subQuery();
$kapcsolattartok
	->groupBy('k.megbizo_id')
	->get('megbizok_kapcsolattartok k', null, 'k.megbizo_id, COUNT(k.kapcsolattarto_id) AS kapcsolattartok');

$data = $db
	->join($kapcsolattartok, 'm.megbizo_id = k.megbizo_id', 'LEFT')
	->where('m.torolve', 0)
	->orderBy('m.megbizo_megnevezes')
	->orderBy('m.megbizo_azonosito')
	->get('megbizok m');
```

But it generates a fatal error:
Problem preparing query (SELECT * FROM megbizok m LEFT JOIN  on m.megbizo_id = k.megbizo_id WHERE   m.torolve = ?  ORDER BY m.megbizo_megnevezes DESC, m.megbizo_azonosito DESC )

It looks like the subquery's string missing from the join. I did not find any information about this kind of problem.

**Comment by avbdr** [comment]
unfortunately library do not support subquieres in join right now. You might cook a patch if you want as im pretty busy this days.
dup of https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/146

**Comment by Ettemlevest** [comment]
Sorry for the duplicate. Then I will use your rawQuery() method that works well for me in this situation.

**Comment by avbdr** [comment]
watch for updates. I might prepare a fix in the near future.

**Comment by avbdr** [comment]
Can you please try the following patch:

code will be (note new syntact for subQuery()):
$kapcsolattartok = $db->subQuery("k");
$kapcsolattartok
    ->groupBy('k.megbizo_id')
    ->where("qqq", 150)
    ->get('megbizok_kapcsolattartok k', null, 'k.megbizo_id, COUNT(k.kapcsolattarto_id) AS kapcsolattartok');

$data = $db
    ->join($kapcsolattartok, 'm.megbizo_id = k.megbizo_id', 'LEFT')
    ->where('m.torolve', 0)
    ->orderBy('m.megbizo_megnevezes')
    ->orderBy('m.megbizo_azonosito')
    ->get('megbizok m');

diff --git a/MysqliDb.php b/MysqliDb.php
index 3a9dfcb..b15d14f 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -117,7 +117,7 @@ class MysqliDb
         else
             $this->port = $port;
 
-        if ($host == null && $username == null && $db == null) {
+        if ($username == null && $db == null) {
             $this->isSubQuery = true;
             return;
         }
@@ -427,12 +427,14 @@ class MysqliDb
      {
         $allowedTypes = array('LEFT', 'RIGHT', 'OUTER', 'INNER', 'LEFT OUTER', 'RIGHT OUTER');
         $joinType = strtoupper (trim ($joinType));
-        $joinTable = filter_var($joinTable, FILTER_SANITIZE_STRING);
 
         if ($joinType && !in_array ($joinType, $allowedTypes))
             die ('Wrong JOIN type: '.$joinType);
 
-        $this->_join[$joinType . " JOIN " . self::$_prefix . $joinTable] = $joinCondition;
+        if (!is_object ($joinTable))
+            $joinTable = self::$_prefix . filter_var($joinTable, FILTER_SANITIZE_STRING);
+
+        $this->_join[] = Array ($joinType,  $joinTable, $joinCondition);
 
         return $this;
     }
@@ -587,7 +589,7 @@ class MysqliDb
         $subQuery = $value->getSubQuery ();
         $this->_bindParams ($subQuery['params']);
 
-        return " " . $operator . " (" . $subQuery['query'] . ")";
+        return " " . $operator . " (" . $subQuery['query'] . ") " . $subQuery['alias'];
     }
 
     /**
@@ -679,8 +681,16 @@ class MysqliDb
         if (empty ($this->_join))
             return;
 
-        foreach ($this->_join as $prop => $value)
-            $this->_query .= " " . $prop . " on " . $value;
+        foreach ($this->_join as $data) {
+            list ($joinType,  $joinTable, $joinCondition) = $data;
+
+            if (is_object ($joinTable))
+                $joinStr = $this->_buildPair ("", $joinTable);
+            else
+                $joinStr = $joinTable;
+
+            $this->_query .= " " . $joinType. " JOIN " . $joinStr ." on " . $joinCondition;
+        }
     }
 
     /**
@@ -946,7 +956,8 @@ class MysqliDb
 
         array_shift ($this->_bindParams);
         $val = Array ('query' => $this->_query,
-                      'params' => $this->_bindParams
+                      'params' => $this->_bindParams,
+                      'alias' => $this->host
                 );
         $this->reset();
         return $val;
@@ -1031,9 +1042,9 @@ class MysqliDb
     /**
      * Method creates new mysqlidb object for a subquery generation
      */
-    public static function subQuery()
+    public static function subQuery($subQueryAlias = "")
     {
-        return new MysqliDb();
+        return new MysqliDb ($subQueryAlias);
     }
 
     /**

**Comment by Ettemlevest** [comment]
After I removed the *->where* line from the subquery it worked as expected. Thanks for your great work!

**Comment by avbdr** [comment]
:) that was the testcase. sorry

**Comment by avbdr** [comment]
i will come up with some tests and will commit a patch

**Comment by avbdr** [comment]
thats fixed with a proper fix in https://github.com/avbdr/PHP-MySQLi-Database-Class. Should be merged here soon.
