### ISSUE TITLE
copy clears a part of a subquery

### ISSUE THREAD

**Issue by weha** [joshcam/PHP-MySQLi-Database-Class#196]
When I build up a query with a subquery and use a copy the first query will be good but the second query will miss the subquery itself.

Example:
$dbi_sub = $dbi->subQuery();
$dbi_sub->where('mycompany_members.active',1);
$dbi_sub->get('mycompany_members',null,'member');
$dbi->where('members.id',$dbi_sub,'IN');

This one works
$cnt = $dbi->copy();
$count_members = $cnt->getOne('members',"COUNT(members.id) AS count");

snip: members.id IN (  (SELECT member FROM mycompany_members WHERE   mycompany_members.active = 1 ) )

This one does not
$data = $dbi->get('members',array($limit_from,$itemsperpage),array("array","off","colums"));

snip: members.id IN (  () )

**Comment by avbdr** [comment]
huh. thank you. Indeed clone() will clone only the main object and will use a references for subqueries.
can you please try folowing patch:

```php
diff --git a/MysqliDb.php b/MysqliDb.php
index b15d14f..515a040 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -163,6 +163,9 @@ class MysqliDb
      */
     protected function reset()
     {
+        if ($this->isSubQuery)
+            return;
+
         $this->_where = array();
         $this->_join = array();
         $this->_orderBy = array();

```

**Comment by avbdr** [comment]
thats fixed with a proper fix in https://github.com/avbdr/PHP-MySQLi-Database-Class. Should be merged here soon.

**Comment by weha** [comment]
Looking good, thanks!

**Comment by avbdr** [comment]
fixed in master
