### ISSUE TITLE
Error when get() or rawQuery + select if the table is empty

### ISSUE THREAD

**Issue by ojoven** [joshcam/PHP-MySQLi-Database-Class#199]
Hey there Josh,

Not sure yet if this is a problem of the class, but I'm trying to **make a select statement over an empty table** and it stops working on binding results function, line 678:

call_user_func_array(array($stmt, 'bind_result'), $parameters);

I'll try to solve it by myself but anyway I wanted to let you know that there is a possible bug here.
By the way, I'm using your class for a database comparator that would help on version controlling over databases:
https://github.com/ojoven/sqldiffgenerator

I'll post here the fix if I find it, please let me know if this happens to you, too, and your way to solve it in that case.

Thanks,
Mikel

**Comment by joshcam** [comment]
In a quick test I haven't been able to duplicate the error, if I get some more time this weekend I'll try to dig a bit deeper if someone hasn't identified it by then.

**Comment by ojoven** [comment]
Hey Josh, not sure yet what the problem was.
As a workaround, I just overwrote the get() function's bind results call with this:

    protected function _bindResultsSelect(mysqli_stmt $stmt) {

        $results = array();
        $result = $stmt->get_result();
        while ($row = $result->fetch_assoc()) {
            array_push($results,$row);
        }
        return $results;

    } 

I think this issue will surely be caused by a particular feature on my side, so please don't worry at all.
Thanks man and good job!
