### ISSUE TITLE
NULL comparison not working properly (or documentation error)

### ISSUE THREAD

**Issue by weha** [joshcam/PHP-MySQLi-Database-Class#202]
Documentation:
$db->where ("lastName", NULL, '<=>');
$results = $db->get("users");
// Gives: SELECT * FROM users where lastName <=> NULL

Actually gives SELECT * FROM users where lastName <=> 
This works: $db->where ("lastName", 'NULL', '<=>');

**Comment by avbdr** [comment]
then it gives SELECT * FROM users where lastName <=> 'NULL'. what is wrong. 
this case is tested in tests.php so i do not think its not working. 

Please provide a real testcase if possible.

**Comment by weha** [comment]
PHP:
`$dbi = new MysqliDb ($dbhost, $dbuser, $dbpass, $dbname,null,null);`
`$dbi->where('ip.trans',NULL,'<=>');`
`$trans_range = $dbi->get('table ip',null,'YEAR(date) AS year');`
getLastquery: `SELECT YEAR(date) AS year FROM table ip WHERE ip.trans <=> `

Other question: is it possible to use "IS NOT"? If I use "IS NOT" as operator I get `WHERE ip.trans IS NOT ? ` (with or without quotes)

**Comment by avbdr** [comment]
getLastQuery () do not return 100% exact the same query as executed. Its written in the documentation. i will try to this case more next days

**Comment by avbdr** [comment]
have you solved your issue?

**Comment by avbdr** [comment]
should be fixed in master
