### ISSUE TITLE
Update with join statement get error

### ISSUE THREAD

**Issue by sopheak-ket** [joshcam/PHP-MySQLi-Database-Class#204]
Hello, I'm try to update statement with join with another table but it got error.

 $datas = array(
      'tkt5d_win_level'  => 0, 
  );
  $db->join("5d_sale_ticket","tkt5d_tsn=tkt5d_tkt5d_tsn","INNER");
  $db->where("tkt5d_d5d_draw_id", $draw_id);                    
  $updated = $db->update("5d_sale_ticket_detail", $datas);

echo $db->getLastQuery();

UPDATE tbl_5d_sale_ticket_detail SET  INNER JOIN tbl_5d_sale_ticket on tkt5d_tsn=tkt5d_tkt5d_tsn`tkt5d_win_level` = ? WHERE   rst5d_digit_1 = ?  AND rst5d_digit_2 = ?  AND rst5d_digit_3 = ?  AND rst5d_digit_4 = ?  AND rst5d_digit_5 = ?  AND tkt5d_d5d_draw_id = ? 

the correct statement should be:

UPDATE tbl_5d_sale_ticket_detail  INNER JOIN tbl_5d_sale_ticket on tkt5d_tsn=tkt5d_tkt5d_tsn
SET  `tkt5d_win_level` = ? WHERE   rst5d_digit_1 = ?  AND rst5d_digit_2 = ?  AND rst5d_digit_3 = ?  AND rst5d_digit_4 = ?  AND rst5d_digit_5 = ?  AND tkt5d_d5d_draw_id = ?

**Comment by avbdr** [comment]
can you please try following patch?
```php
diff --git a/MysqliDb.php b/MysqliDb.php
index 2e1c4a5..3ee47a7 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -358,7 +358,7 @@ class MysqliDb
         if ($this->isSubQuery)
             return;
 
-        $this->_query = "UPDATE " . self::$_prefix . $tableName ." SET ";
+        $this->_query = "UPDATE " . self::$_prefix . $tableName;
 
         $stmt = $this->_buildQuery (null, $tableData);
         $status = $stmt->execute();
@@ -723,7 +723,8 @@ class MysqliDb
         if ($isInsert !== false) {
             $this->_query .= '(`' . implode(array_keys($tableData), '`, `') . '`)';
             $this->_query .= ' VALUES(';
-        }
+        } else
+            $this->_query .= " SET ";
 
         foreach ($tableData as $column => $value) {
             if ($isUpdate !== false)

```

**Comment by sopheak-ket** [comment]
Thank you very much for fixed this error

**Comment by avbdr** [comment]
pushed to master
