### ISSUE TITLE
To many connections

### ISSUE THREAD

**Issue by Edig** [joshcam/PHP-MySQLi-Database-Class#206]
Hi, I'm trying to run a php file that runs another php file, this happens about 100 times.

each time y open a new DB connection, but before calling the next php file I close the last one like this
$db = null;

and I'm getting this message
'Too many connections in libs/MysqliDb.php on line 140'

Any idea how to solve it?

**Comment by ishr00m** [comment]
Interested also. 

Отправлено с моего ASUS

-------- Исходное сообщение --------
Отправитель:Eduardo Iglesias <notifications@github.com>
Отправленные:Thu, 05 Mar 2015 08:27:21 +0500
Получатель:joshcam/PHP-MySQLi-Database-Class <PHP-MySQLi-Database-Class@noreply.github.com>
Тема:[PHP-MySQLi-Database-Class] To many connections (#206)

**Comment by Izopi4a** [comment]
How many mysql connections do you actually have ?
In my case for my app I got 1.
Do you use MysqliDb::getInstance() ?

execute this query : ```SHOW STATUS WHERE `variable_name` = 'Threads_connected'```

to see how many open connections you got,

To see the maximum number of connetions

```
show variables like "max_connections";
```

hope that helps

**Comment by Edig** [comment]
Hi,

I'm opening over 50 connections and I get that error. I know that it's not a good practice to open that many connections, that why when my php file call another php file (I prefer to call php files than classes, so I can use shell commands and divide it in 4 CPUS the process, because this function execute once per day per user). 

But because the php file call another php file with ```exec('php phpfile.php')``` and wait until the other 100 calls finish (I do this so I can calculate the execution time of the full process) the connection to the database remains open, how can I close that connection or pass it throw parameter?

Or any other idea on how can I do this?

Note: IF i do it with a function and a loop calling a functions 100 times, will work but I will execute it only in one thread, and I'm very interested to divide it in more threads

**Comment by avbdr** [comment]
if you are calling 100 phpfiles at the same time that would require 100 mysql connections
The only way to fix this issue is to increase max connections limit in mysql itself. There is nothing mysqlidb can do for you to fix that.
