### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by alexa026** [joshcam/PHP-MySQLi-Database-Class#208]
Hello, 
I'am having inserts added into $sql string. how do i execute them all at once, i've already tried with 
rawQuery($sql), but it gives me an error. is there any other way?
Note: inserts are aiming for multiple tables

Thanks in advice.

**Comment by avbdr** [comment]
most likely you need to use rawQuery($sql, false) to disable input filter.

**Comment by alexa026** [comment]
Thank you, will give it a try.

**Comment by alexa026** [comment]
Still getting "PHP Fatal error:  Problem preparing query ", call looks like rawQuery($this->sql, false);

**Comment by avbdr** [comment]
sorry, rawQuery($this->sql, null, false);

**Comment by alexa026** [comment]
Tried that already, still the same.

**Comment by avbdr** [comment]
i think then your $this->sql is empty.

**Comment by alexa026** [comment]
That is not possible http://pastebin.com/F1fu9h8f

**Comment by avbdr** [comment]
thats weird. let me see

**Comment by alexa026** [comment]
Right now I'm getting syntax error, even if every single one of queries is executed correctly separately.

**Comment by avbdr** [comment]
huh mysqli->prepare cant prepare statements with multiple sql commands. 
you will need to execute them one by one. 
you can take a look at tests.php how multi insert is implemented there.

**Comment by alexa026** [comment]
Very well, thank you for your time.

**Comment by Izopi4a** [comment]
hmmm, this sintax is wrong.

I think the real query should be in (INSERT INTO product_data (product_id, data, value) VALUES ('50', 'price', '400', '51', 'price', '401','52', 'price', '402','53', 'price', '403','54', 'price', '404');

if this is supported by mysqli ( cuz i am not sure ) , there could be a nice implementation i think

**Comment by avbdr** [comment]
that would work indeed

**Comment by Izopi4a** [comment]
```
protected function _buildTableData ($tableData) {
        if (!is_array ($tableData))
            return;
        $isInsert = strpos ($this->_query, 'INSERT');
        $isUpdate = strpos ($this->_query, 'UPDATE');
        if ($isInsert !== false) {

            $columns = (isset($tableData['columns']) ? $tableData['columns'] : array_keys($tableData) );
            
            $this->_query .= ' (`' . implode($columns, '`, `') . '`)';
            $this->_query .= ' VALUES (';

            $tableData = $tableData['values'];
```

so after that we sohuld be able to call the insert method with a sintax like:

```
$this->DB->insert('products_data', [
            "columns" => ["product_id", "data", "value"],
            "values" =>  ['50', 'price', '400', '51', 'price', '401','52', 'price', '402','53', 'price', '403','54', 'price', '404']
        ]);
```

**Comment by avbdr** [comment]
good idea. Except that I believe something like this will be more readable
```
$this->DB->insert ('products_data', [
                 ['50', 'price', '400'],
                 ['51', 'price', '401'],
                 ['52', 'price', '402']
            ],
            ["product_id", "data", "value"]
);
```

**Comment by qahar** [comment]
+1 for the multi insert values

**Comment by avbdr** [comment]
Creation of a big insert () () () () statement wont be an optimal solution I believe so we should implement something like this internally:
1. startTransaction()
2. prepare a statement
3. iterate over array of data and execute bind && execute
All sounds pretty straightforward except handling of the special cases like db->func(), db->now() values.

**Comment by avbdr** [comment]
well, i have tried using different ways and for 100k variables prepared statements are very slow. 
Best difference is 25 secs ws 1sec with rawQuery() of unprepared data.

seems need to play with large single query more.

**Comment by avbdr** [comment]
fixed in master
