### ISSUE TITLE
Request: Update the release version

### ISSUE THREAD

**Issue by qahar** [joshcam/PHP-MySQLi-Database-Class#209]
I like this class and always use it since first met.

The only problem I have now is no official release version here.
Inside the file state version 2.0 but it's not quite usefull since we doesn't know the last commit marked as 2.0 and what change maked after that point.
Usually I end up change the version to "2.0 - 9026a39" where the last alpha-numeric is the commit identifier so I know what change is maded before use the latest version.

Please add this as consideration to make regular update to the release version.

**Comment by AlainD-** [comment]
+1
I would like that too please.
Thanks.

**Comment by avbdr** [comment]
good. I just tagged 2.1 release. Will try to keep this practice.
