### ISSUE TITLE
rawQuery changing parameter values automatically

### ISSUE THREAD

**Issue by 1banerjeesuman** [joshcam/PHP-MySQLi-Database-Class#210]
Consider the following set of code: 
```
$activeProjectsInformationDBParameters = array(10000,8);
$activeProjectsInformation = $activeProjectsInformationDBObject->rawQuery("SELECT * FROM Projects WHERE memberID = ? AND statusCode = ?", $activeProjectsInformationDBParameters);
```

When I echoed ```$activeProjectsInformationDBObject->getLastQuery();``` , it is showing the following:

```
SELECT * FROM Projects WHERE memberID = 10000 AND statusCode = 2
```

The *statusCode* is being changed to **2** automatically. But I sent **8** as *statusCode* from the parameters.

**Comment by avbdr** [comment]
i have a feeling that this is not an issue of a library but in your code somehow. 
Try to reduce your code to a minimum and check it once again.

I cant imagine a situation where such case can occure.

**Comment by 1banerjeesuman** [comment]
Hi @avbdr ,
Thank you for replying. :smile:

Yes, you are correct. probably I had some issues with the code.

So, I isolated the set of code to another page and tested it. The result it is showing now is correct. But the problem is when I echo ```$database->getLastQuery()```, it echoes nothing.

**Does this class support getLastQuery() object for rawQuery()?**

Here is the set of code I am testing with...
```
$activeProjectsInformationDBParameters = array(10001,8);
$activeProjectsInformation = $database->rawQuery("SELECT * FROM Projects WHERE memberID = ? AND statusCode = ?", $activeProjectsInformationDBParameters);
echo 'The last query processed is: '.$database->getLastQuery();
```
and here is the output:

![Image of Yaktocat](http://oi57.tinypic.com/2yzj02c.jpg)

**Comment by avbdr** [comment]
haha, indeed. 
please try this patch.

```php
$ git diff MysqliDb.php
diff --git a/MysqliDb.php b/MysqliDb.php
index edfa9fd..b23b04b 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -230,6 +230,7 @@ class MysqliDb
 
         $stmt->execute();
         $this->_stmtError = $stmt->error;
+        $this->_lastQuery = $this->replacePlaceHolders ($this->_query, $bindParams);
         $this->reset();
 
         return $this->_dynamicBindResults($stmt);
```
