### ISSUE TITLE
rawQuery returning object array

### ISSUE THREAD

**Issue by andreadompe** [joshcam/PHP-MySQLi-Database-Class#211]
Hello joshcam,
is there a way to get from the rawQuery an object array?

Something such like this

$params = Array(1, 'admin');
$users = $db->rawQuery("SELECT id, firstName, lastName FROM users WHERE id = ? AND login = ?", $params);

echo $param->firstName. ' ' . $param->lastName;

Kind regards

Andrea

**Comment by SanMane** [comment]
Meanwhile, why dont you try this

```php
$array = array("FirstName"=>"abc", "LastName"=>"xyz");
$object = (object)$array;
echo $object->FirstName;
```
this works!!

**Comment by andreadompe** [comment]
In the end i did something like this:
    
    if ($result = $database->rawQuery("SELECT * FROM members WHERE username = ? LIMIT 1",     $params)) { 
         $result = self::userobj_from_array(array_shift($result));
    }
    

Where userobj_from_array is

	public static function userobj_from_array($record) {
		return self::instantiate($record);
	}

	private static function instantiate($record) {
		$object = new self;
		foreach ($record as $attribute => $value) {
			if($object->has_attribute($attribute)) {
				$object->$attribute = $value;
			}
		}

		return $object;
	}	

	private function has_attribute($attribute) {
		$object_vars = $this->attributes();
		return array_key_exists($attribute, $object_vars);
	}

**Comment by SanMane** [comment]
not quality coding!!

**Comment by andreadompe** [comment]
I see, you did in 3 rows what i did in 200 

he he he

Thanks a lot SanMane

**Comment by avbdr** [comment]
to do it right way, it will be easier to patch _dynamicBindResults function and add $mysqlidb->objectOutput = true flag to determine if you want array or object output.
```
        while ($stmt->fetch()) {
            $x = new stdObject;
            foreach ($row as $key => $val) {
                $x->$key = $val;
            }
            $this->count++;
            array_push($results, $x);
        }
```

thats a start. then you would want to run tests.php.

**Comment by SanMane** [comment]
my pleasure @andreadompe

**Comment by avbdr** [comment]
thats the readme of the alpha i did. Still working on some updates. https://github.com/avbdr/PHP-MySQLi-Database-Class/blob/master/dbObject.md

**Comment by avbdr** [comment]
merged in master

**Comment by avbdr** [comment]
mysqlidb can return objects now as well. https://github.com/joshcam/PHP-MySQLi-Database-Class#defining-a-return-type
