### ISSUE TITLE
Wrong data return from select query having TIME_DIFF

### ISSUE THREAD

**Issue by bilaliqbal** [joshcam/PHP-MySQLi-Database-Class#214]
I am running this query in phpmyadmin and mysqli() and it gives me proper result. But on running it in MySQLi Database class it returns wrong data.

Query:
UPDATE table SET `status` = 0 WHERE   time <= DATE_ADD( NOW(), INTERVAL -2 MINUTE ) 

PHP Code:
$db->where('time', 'DATE_ADD( NOW(), INTERVAL -2 MINUTE )', '<=');
$db->update( 'table', array('status'=> '0') );

Also Tried:

$db->where('time', $db->now('-2m'), '<=');
$db->update( 'table', array('status'=> '0') );

Tell me how may i fix it or suggest me the right query.

**Comment by vesper8** [comment]
Have you checked what $db->getLastQuery(); contains after running the query, and comparing that sql to the raw query?

**Comment by avbdr** [comment]
Look at the readme ...
```
$db->where('time', $db->func('DATE_ADD( NOW(), INTERVAL -2 MINUTE )'), '<=');
$db->update( 'table', array('status'=> '0') );
```
