### ISSUE TITLE
are there any implementations of this class that uses caching?

### ISSUE THREAD

**Issue by vesper8** [joshcam/PHP-MySQLi-Database-Class#216]
Just found this wrapper today.. I really like its usability and syntax. I would like to use it but my current implementation involves a custom wrapper that uses memcache. I know I could add my own caching in there but figured since this is such a popular project that surely others must have already done it. Couldn't find anything on google however.

Was wondering if anyone had any insight on what seems like a proper way to add caching to the use of this class. And if some code could be provided by anyone who may have already done this in a branch or somewhre else.

Thanks!

**Comment by Izopi4a** [comment]
+1 for the mem cache.
I could implement it, but I am really busy for the next few months. 
Anyways, I hope i find some time to cook it.

**Comment by avbdr** [comment]
i think the best way is to do a wrapper class which overwrites an insert(), update(), get() and rawQuery methods. We could create an extra directory in the tree and host stuff like that there.

**Comment by thingNumber1** [comment]
Are you still planning to support that?

**Comment by neubreed** [comment]
I'm looking at doing this for myself but need some guidance as most of the key properties and methods are private for both MyssliDb dbObject. I'd like to generate a hash out of the query as the key and store the results data into memcahced .. Then intercept when calling any of the get methods.. Any pointers on how I would do that?

thanks

**Comment by vesper8** [comment]
@neubreed Why would you even try to do this 5 years later unless you are stuck having to support a 10 year old legacy system. You'll save yourself so much pain if you instead use something like Laravel/Lumen instead which has built-in caching and support for mysql, postgresql and sqlite through its Eloquent ORM out of the box.

**Comment by neubreed** [comment]
I'll have a lot of refactoring to do to switch db layer .. I'll look into it :-/

**Comment by vesper8** [comment]
Even though this was almost 5 years ago.. I actually remember the day I wrote this.. I was building a new project using a custom mvc legacy framework that had been built by a friend and that I had been using for a few projects because I didn't know any others. I was frustrated at having to replace the db layer because of the mysqli deprecations (if I remember correctly) and I was looking for an alternative. It was that day that I found out about composer and about Laravel which was still on 4.x release at the time. I had a lot of thinking to do and deciding on whether I would try to patch in my custom framework with custom solutions or if I would embrace the new modern way of pulling in dependencies and switch to a framework with a big community supporting it not to mention dozens (now hundreds) of awesome libraries on Github. I'm glad I went with Laravel.. the learning curve was steep and migrating the project along with learning a new framework took me almost a year but boy was that a great decision in the long run.

**Comment by neubreed** [comment]
Thanks for taking to the time to write .. Totally taking all that on board .. I've just spent the last week refactoring my project with Laravel Eloquent ORM (tonnes of queries!) only to find it's not compatible with Twig, which is what I'm using for my views .. lot's of magic loading conflicts and I eventually hit a dead end. I'm using Slim framework which allows the choice of ORM .. Eloquent has lot's of nice features and docs .. Next time I'll start with a full stack. So it looks like I'm back here ;)

**Comment by vesper8** [comment]
Hrmm.. not familiar with Twig. I imagine you've already had a look at https://github.com/rcrowe/TwigBridge ? I'm not even sure it's relevant to your case though.

For the first year and a half of using Laravel I was using Laravel's Blade for my views.. which I think it kind of similar to Twig. I'm sure there's a way to pass data from a Laravel controller to a twig template... if the data was produced by performing a raw DB query or using eloquent it should make no difference at all, it's just a PHP data container object and if you can pass even a simple $var from your controller to twig then you can pass it anything

For the past 2 years and going forward I've switched to a new flow where my front-end and back-end are always completely separate and my back-end which interacts with the DB is strictly a REST API which is consumed by my front-end. Laravel + Vue in these roles makes everything so easy and pleasant to work with and it opens up many possibilities such as developing hybrid apps and progressive web apps.

Anyway.. now that you've tasted modern.. let it simmer and maybe you'll come back to it and realize it's the best way forward

Good luck to you
