### ISSUE TITLE
How to bulid right query?

### ISSUE THREAD

**Issue by ishr00m** [joshcam/PHP-MySQLi-Database-Class#221]
Hi guys! I have following code: 
```
$LongIp = intval (ip2long ($_SERVER ['REMOTE_ADDR']));
$data = array ('uID'		=>	$uID,'uIP'		=>	$LongIp);
$db->insert ('user_log', $data);
```
Output of $LongIp in PHP for me is 3155300322 but in database it's always gonna be stored as 2147483647. I've use google already and  [have some useful info about that](http://stackoverflow.com/questions/10255724/incorrect-integer-2147483647-is-inserted-into-mysql). How can i add correct integer value with $db->insert?

**Comment by ishr00m** [comment]
Sorry, it was just problem of max length. I just set bigint(20) and it's fine now.

**Comment by ricwein** [comment]
Hey,
it's probably not a problem with the MySQLi Class but with your database variable type for the `'uIP'` row. As mentioned in your linked thread, the maximum size of a `INT` for MySQL is "2147483647".

You can simply try using `BIGINT` instead. Maybe also `unsigned INT` would do the trick, but you need to convert your ip first:
```php
$LongIp = ip2long ($_SERVER ['REMOTE_ADDR']);
$uIP = sprintf('%u', $LongIp);
```

**Comment by kenzouno1** [comment]
one vote to change type to string :+1:

**Comment by ishr00m** [comment]
It's quite nice to use bigint for now! Thanks, it's closed.
