### ISSUE TITLE
Is it possible somehow to see the full query output?

### ISSUE THREAD

**Issue by ishr00m** [joshcam/PHP-MySQLi-Database-Class#223]
I generate query with operators like $db->where etc. I would like to see full query before executing just to make sure that the query is correct. Is it possible to see full raw query by using this functions?

I enable general log but this is what i see: 
```SELECT * FROM lf_page_categories WHERE   CategorySlug = ?  AND ParentID = ?  AND recycled = ?  LIMIT 1```

So as you can see this is query without data.

Thanks.

**Comment by abunour22** [comment]
i don't now why you need that ,, 
anyway i made this for errors and its works fine to me ..
may it will help you !!

Add This function into your MysqliDb.php :

    /**
     * Allow the class to send admins a message alerting them to errors
     * on production sites
     *
     * @access public
     * @param string $error
     * @param string $query
     * @return mixed
     */
    public function log_db_errors( $error_in, $error, $query, $bindParams = array())
    {
                    $message = '<p>Error In: ' . $error_in.'</p>';
                    $message .= '<p>Error Time: '. date('Y-m-d H:i:s').'</p>';
                    $message .= '<p>bindParams: '. json_encode( $bindParams ).'</p>';
                    $message .= '<p>Query: '. htmlentities( $query ).'</p>';
                    $message .= '<p>Error: ' . $error.'</p>';
                    $message .= '<p>Related File: ' . $_SERVER['PHP_SELF'].'</p>';

                    if( defined( 'SEND_ERRORS_TO' ) && SEND_ERRORS_TO_EMAIL )
                    {
                            $headers  = 'MIME-Version: 1.0' . "\r\n";
                            $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
                            $headers .= 'To: Admin <'.SEND_ERRORS_TO.'>' . "\r\n";
                            $headers .= 'From: Database Department <db@'.$_SERVER['SERVER_NAME'].'.com>' . "\r\n";
                            mail( SEND_ERRORS_TO, 'Database Error', $message, $headers );   
                    }
                    if(DISPLAY_DEBUG)
                    {
                            echo $message;   
                    }
    }

made change in rawQuery  as example for :

       call_user_func_array(array($stmt, 'bind_param'), $this->refValues($params));

to : 

            if ( !call_user_func_array(array($stmt, 'bind_param'), $this->refValues($params)) ) {
                    // Send Errors To Email
                    $this->log_db_errors( 'bind_param',trim($stmt->error." ".$this->_mysqli->error), $this->_query, $bindParams );   
            }

**Comment by ishr00m** [comment]
Thanks but this is errors. I need full query log.

**Comment by ishr00m** [comment]
The best case if i can show all queries in the bottom of the page.

**Comment by avbdr** [comment]
Db->getLastQuery() is what you want

**Comment by nikkyandrei** [comment]
//use last update from few ours ago , and add to your script : 
// after you setup class  $mydb = new MysqliDb(.....)
// add next lines:

$mydb->setTrace(true);

// and for printing all queries at the end of script - this you can add where you want , recommend after line above 

if(!function_exists("get_shutdown")){
	function get_shutdown(){
		global $mydb; /// the variabile name used on defined class EX: $mydb = new MysqliDb(.....)
		echo "<pre>".print_r($mydb->trace,true)."</pre>"; // if u change the variable from global please change it here also 
	}
	// make sure the function is loaded at the end of execution of script -  this is usefull in case you have other register_shutdown_function();
	function prepare_get_shutdown(){
		register_shutdown_function('get_shutdown');
	}
	register_shutdown_function('prepare_get_shutdown');
}
	register_shutdown_function('prepare_get_shutdown');
}

**Comment by avbdr** [comment]
```
print_r($mydb->trace,true)
```
actually second parameter is optional. Its used to strip the prefix from the script path in the 3rd array value.

**Comment by nikkyandrei** [comment]
the second param from print_r is to return the output not to print it you can make something like 
$output=print_r($array,true);

**Comment by ishr00m** [comment]
@nikkyandrei Thank you very much! It works fine now!
