### ISSUE TITLE
simple table objects wrappers feedback needed

### ISSUE THREAD

**Issue by avbdr** [joshcam/PHP-MySQLi-Database-Class#225]
I have a class which implements mvc which i want to extend and publish as a helper class. 
Currently what could be done with it is:
```php
<?php
require_once "dbObject.php";

class accData extends dbObject {
    protected $dbTable = "acc_data";
    protected $primaryKey = "id";
    protected $dbFields = Array (
              'id' => 'int not null',
              'var' => 'varchar(20) not null unique',
              'var2' => 'varchar(20) not null unique',
    );
    protected $jsonFields = Array ("var2");
    protected $arrayFields = Array ("var2");
    protected $timestamps = Array ("created_at","updated_at");

    public function last () {
        $this->db->where ("id" , 1300, '>');
        return $this;
    }
}
?>
```
default functions including getOne,get,count,insert,update,delete and could be used in combination with where/orWhere/orderBy functions.

test.php
```php

Example:
<?
require_once ("MysqliDb.php");
require_once ("accData.php");

$db = new Mysqlidb('localhost', 'root', '', 'akorbi');

$accData = new accData();
$d = $accData->getOne(1288);
print_r ($d);

print_r ($accData->last()->get());

$accData->insert([
    'test' => 'var',
    'test2' => 'var2',
]);


$accData->update([
    'id' => 1,
    'test' => 'var3',
    'test2' => 'var4',
]);
```

**Comment by avbdr** [comment]
as well class supports simple validation and preInsert/preUpdate hook. 
thinking about adding pagination function here as well.

**Comment by nikkyandrei** [comment]
What i don't understand is why you must define $db = new ... and after that you use other objects... use extends and define the __consrtuct method an do 

function __construct($param){
      parrent::__construct($param);
      // also here you can add other things before or after parrent::__construct
}


When i implement the changes that i send to you  i create my  class to extends yours and overwrite what i wanted but also i overwrite the __construct.

**Comment by avbdr** [comment]
you will initialize MysqliDB once, and after that there is no need to carry db credentials around. 
You can download initial scripts and make your adjustments or paste them here. 
https://github.com/avbdr/PHP-MySQLi-Database-Class

**Comment by nikkyandrei** [comment]
are you sure  ? mysqlidb carry the credentials this is 1 of 2 reasons why at current project i couldn't use the class and create another to extends php mysqli class

what you can do is to improve a bit dbObject in __construct is to read the configs and to auto construct the MysqliDB also i suggest in MysqliDB to compress __construct() and connect() and then you can remove from class : 
$this->username 
$this->password 
$this->db 
$this->port 
$this->charset

**Comment by avbdr** [comment]
```php
<?
require_once ("../MysqliDb.php");

class test extends MysqliDB {

    public function __construct () {
        parent::__construct ('localhost', 'root', '', 'akorbi');
    }
}
$t = new test();
print_r ($t->get("users",1));
?>
```

**Comment by avbdr** [comment]
implemented api sample https://github.com/avbdr/PHP-MySQLi-Database-Class/blob/master/dbObject/test.php

**Comment by avbdr** [comment]
initial doc https://github.com/avbdr/PHP-MySQLi-Database-Class/blob/master/dbObject.md
