### ISSUE TITLE
Why returned type of get & getOne is array of array/array and not object

### ISSUE THREAD

**Issue by mainman** [joshcam/PHP-MySQLi-Database-Class#226]
All in the title ;-) Thanks for answering !

**Comment by avbdr** [comment]
because thats how it designed. There is couple issues posted here about this and there is some patches available to make them objects.
As for me I do not see any use of returning results as objects except to waste extra memory.

**Comment by mainman** [comment]
Ok, no problem. But objects are simplier to deal with, for me. I searched a bit and found nothing, I will search again.
Thans
