### ISSUE TITLE
empty value in where cause unexpected behavior

### ISSUE THREAD

**Issue by arcrest** [joshcam/PHP-MySQLi-Database-Class#229]
$con->where("id",NULL)->delete("table")
will generate statement: delete from table where id    , which remove everything in the table. This is dangerous.
I think "delete from table where id is null" is the correct result;

**Comment by avbdr** [comment]
please checkout latest master. I think that should be fixed in https://github.com/joshcam/PHP-MySQLi-Database-Class/commit/6c98f0ea7a570a868f91b3fe57538fc4544a50a1
