### ISSUE TITLE
Saved me heaps of time, thanks

### ISSUE THREAD

**Issue by listingslab** [joshcam/PHP-MySQLi-Database-Class#230]
Just wanted to say that. And also to thanks for making this work open source. I needed to migrate my PHP Applications to MySQLi prepared statements and this Class helped a lot.

Is it easy to set LIMIT with the class? I can't find it in a quick search of the docs, but I'm looking for a method like the the ->where statement which would allow me to set number of results.

And also, I'm wondering about the destruct method. Is it possible to call it explicitly at the end of my page so that I know that it's been cleanly closed and won't build up stress on the server.

Thanks for your time, and again for sharing your work

**Comment by avbdr** [comment]
see readme for a get() parameters. $db->get("table",Array($count,$offset))
library is not doing any background activities.
