### ISSUE TITLE
Problem Prepare statement with query data from Mysql Views

### ISSUE THREAD

**Issue by sopheak-ket** [joshcam/PHP-MySQLi-Database-Class#232]
When I try to query data from view using get function it found error ' Prepared statement need to be re-prepared .
Can anyone help me?

**Comment by avbdr** [comment]
works here. Are you doing lot of sql queueries in some loop?  Maybe something related to https://bugs.mysql.com/bug.php?id=42041?

**Comment by sopheak-ket** [comment]
I tried to find solution but get nothing.
I'm just do simple query data from view. it's not many sql queries in some loop.
But why I Select data without prepared statement it work fine.

**Comment by avbdr** [comment]
bug is missing test case. closing
