### ISSUE TITLE
IN returns only 1 row

### ISSUE THREAD

**Issue by EinKRieGeR** [joshcam/PHP-MySQLi-Database-Class#233]
where('id', Array('IN' => Array(1,2,3)));
get('table');

its create next query
SELECT * FROM table WHERE id IN ('1,2,3')

and returning only first row with id=1 (because variables inside '....')

other variants provide one result

**Comment by avbdr** [comment]
I doubt that thats the case. Please try to update library from master and recheck the code. Maybe you have where('id', Array('IN' => Array('1,2,3')));

**Comment by ttyazilim** [comment]
i have same issue

**Comment by avbdr** [comment]
there is a case in test, it should be working just fine
