### ISSUE TITLE
PHP-MySQLi-Database-Class

### ISSUE THREAD

**Issue by shamseerpari** [joshcam/PHP-MySQLi-Database-Class#238]
How can i do searching operation by using these class,no where you mentioned about the searching,so kindly respond ASAP with positive solution

**Comment by avbdr** [comment]
use where()
https://github.com/joshcam/PHP-MySQLi-Database-Class/

**Comment by tomitomas** [comment]
https://github.com/joshcam/PHP-MySQLi-Database-Class#where-method

**Comment by shamseerpari** [comment]
big thanks to both of you
