### ISSUE TITLE
Prepared rawQuery issue

### ISSUE THREAD

**Issue by imobdevkishan** [joshcam/PHP-MySQLi-Database-Class#239]
Can we user comparision operator like '<=' or '<' or etc ? 

Because in 'rawQuery' use with prepared statement its give me below error : 
Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement

If i will remove that greater or less than sign and run query only with equals than its working fine. 
Without prepared statement if we give direct value like traditional mysql than Limit function not working and its give me whole table records.

Please me.

**Comment by tomitomas** [comment]
you should give us a part of your query to see where the problem is .. 

Use : 
$db->where ('id', 50, ">=");
$results = $db->get ('users');
Gives: SELECT * FROM users WHERE id >= 50;

https://github.com/joshcam/PHP-MySQLi-Database-Class#where-method

**Comment by avbdr** [comment]
i think you are not calling rawQuery with false parameter to disable sanitizing. 
```
db->rawQuery ("select * from foo where bar <= ?", Array (10), false);
```
