### ISSUE TITLE
Return Type JSON?

### ISSUE THREAD

**Issue by svemirko** [joshcam/PHP-MySQLi-Database-Class#242]
Hello,

I found these classes very useful and I'm testing them out now to see if they will fit well for my projects. 
I have found a couple of things so far that would be really nice to have on top of all you already implemented:

1. Return type JSON to return results as JSON and
2. Setting prefix for db tables doesn't seem to work very well with the option of setting custom table name (ex. protected $dbTable = "users"; with an already set prefix will return an error performing a ::byId() select). Maybe I'm doing something wrong about this one, so please show me the right direction.

These are just a couple I have found so far, other than that scrips look amazing.

Thank you for providing such goodness!

**Comment by avbdr** [comment]
thanks for a feedback :) Looks like you are one of the first dbObject users as I have commited this addon couple weeks ago. 
1. use $obj->toJson() or echo $obj to serialize it to json()
2. Indeed somehow i forgot to test dbObject for prefix functionality. I will try to update master asap.

Thanks. Please keep openning issues in case you will find something.
Alex

**Comment by avbdr** [comment]
please update to a latest master. I have pushed prefix fix for everything except orderBy() method.

**Comment by svemirko** [comment]
hey Alex!

thanks for the answer and for the update! prefix works well now.
regarding json serialisation, $obj->toJson() returns an error in case of multiple results cause they come back as an array. heres an example of what I do:

$news = News::ArrayBuilder()->get();
$newsJson = json_encode($news);

using it without ArrayBuilder() returns some other things from the object itself besides the results which ArrayBuilder() cleans up nicely. my idea was to have something that would return json results in one line like ex. return News::get()->toJson() or why not News::JsonBuilder()->get();

using these two lines is not a big deal at all, I just think it can still be cleaner :)

thanks!
Mirko

**Comment by avbdr** [comment]
just pushed that into master. thank you.
