### ISSUE TITLE
WHERE return first record

### ISSUE THREAD

**Issue by murderaven** [joshcam/PHP-MySQLi-Database-Class#245]
Hi,

I've check user ID top of the page, if its not defined or its not numeric value return 0 like that;

$ID = ((!isset($_GET['ID']) || !is_numeric($_GET['ID'])) ? 0:intval($_GET['ID']));

in case this statement everytime return first record from database table when ID value 0;

$db->where('user_id',$ID);
$records = $db->getOne('users');

Whats wrong?

**Comment by avbdr** [comment]
im not sure where is the problem. If you have multiple rows with id 0 it will return first record.

**Comment by murderaven** [comment]
There 2 row available in table, also user_id column unique primary key. I've resolve it with 

$ID = ((!isset($_GET['ID']) || !is_numeric($_GET['ID'])) ? -1:intval($_GET['ID']));

and rawQuery works too. But I must change all pages like that :/

**Comment by avbdr** [comment]
im sorry, I do not understand what do you mean.

**Comment by murderaven** [comment]
user_id    username
1             admin
2             staff

user_id column unique and there no "0" id available in table. 

If any member call "0" id via querystring, admin profile will appear. 

----
rawQuery works fine like that

$ID = ((!isset($_GET['ID']) || !is_numeric($_GET['ID'])) ? 0:intval($_GET['ID']));
$params = Array($ID);
$q = "SELECT * FROM ". db_table_pref ."users WHERE user_id=? LIMIT 1";
$opUsrRs = $db->rawQuery($q,$params);

----
but where statement does not work
$db->where('user_id',$ID);
$opUsrRs = $db->getOne('users');

is that where call usage wrong for me?

**Comment by avbdr** [comment]
interesting. Thank you for a bug report. Please try latest master.

**Comment by avbdr** [comment]
fixed in master.
