### ISSUE TITLE
WHERE statement with 0 value does not give right result

### ISSUE THREAD

**Issue by arieffikhrie** [joshcam/PHP-MySQLi-Database-Class#247]
As stated on subject.

````
$db->where('_zero', 0);
$result = $db->get('tablea');
$lastQuery = $db->getLastQuery();
````
`//$result  = Array ( [0] => Array ( [_id] => 3 [_value] => 666 [_zero] => 2 ) )`
`//$lastQuery = SELECT * FROM tablea WHERE _zero`

It not showing all the result with 0 value

**Comment by avbdr** [comment]
can you please try latest master please? Should be fixed

**Comment by arieffikhrie** [comment]
Thanks
