### ISSUE TITLE
Replace Into

### ISSUE THREAD

**Issue by LouisBHirst** [joshcam/PHP-MySQLi-Database-Class#248]
Love MysqliDb!!  Thanks so much for this.  Question - do you have any plans to add REPLACE functions?   https://dev.mysql.com/doc/refman/5.0/en/replace.html

thanks!

**Comment by avbdr** [comment]
Thank you. Please update to latest master. I just commited support to replace()

**Comment by LouisBHirst** [comment]
Thanks, I'll test it!

**Comment by jackbrown1993** [comment]
Can't seem to get this to work, am I doing something wrong?

Using:

 $data = Array(
        'token' => $hash,
        'username' => $username
    );
    $db->replace('asl_password_reset_tokens', $data);

Error:

Fatal error: Problem preparing query (REPLACE INTO asl_password_reset_tokens SET ?, ?) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?, ?' at line 1

**Comment by avbdr** [comment]
i will look into it shortly

**Comment by jackbrown1993** [comment]
Thank you.

**Comment by avbdr** [comment]
fixed, thanks for a bugreport
