### ISSUE TITLE
Add method to fetch single column from multiple rows

### ISSUE THREAD

**Issue by LouisBHirst** [joshcam/PHP-MySQLi-Database-Class#249]
Hi, again great library - i'm luvin' it!! 

Question - get value is described as "@return array Contains the returned column from the select query" however it will only return the top 1 value.  Is that by design?  I thought it would return the whole column.

In the meantime i'm using get(<table>, null, <array("wanted column")) which is working fine.

thanks!

**Comment by avbdr** [comment]
thanks. Seems description were copypasted from getOne method. getValue always return a single value of 1 row. Not sure, maybe will be nice to have getColumn() method.

**Comment by LouisBHirst** [comment]
Ah ok, sure no problem understand.  I think getColumn would be a nice convenience function, your call.

**Comment by avbdr** [comment]
commited into master
