### ISSUE TITLE
Fatal error: Out of memory (allocated 1048576) (tried to allocate 4294967296 bytes

### ISSUE THREAD

**Issue by abdul202** [joshcam/PHP-MySQLi-Database-Class#251]
i use version   2.0
i get this error with some of my clients 
>Fatal error: Out of memory (allocated 1048576) (tried to allocate 4294967296 bytes) in public_html/shortme/includes/MysqliDb.php on line 628

 this error shows up not with of my clienet with just 2 of them
how to fix it

**Comment by nic-d** [comment]
Since no one has replied yet, I'll suggest a temporary solution. If you can't change the PHP.ini (shared hosting?) then you can set this line at the top of the script:

```php
ini_set('memory_limit', 'x');
```
Place this at the top of the script, where 'x' is the amount of memory you'd like to allocate. Otherwise you can change the memory limit in the PHP.ini file directly.

**Comment by abdul202** [comment]
Thank you for reply 
i have tried this solution but unfortunately it didn't work
> ini_set('memory_limit', '-1');
but it seems that my client is on shared hosting and he has limited memory 128MB and i think they disabled any  ini_set to be overridden  
Thanks

**Comment by avbdr** [comment]
1. how many rows you are getting in result?
2. do you have longtext fields in this result?
3. what php version you are running?

**Comment by abdul202** [comment]
they are 17 rows as the following
i'll try to change the text type to varchar and see maybe that could fix the issue

Column		|  Type		|	Null	
------------ | ------------- | ----------------
id (Primary)  |	int(255)	| No 	 	 	 
sitename	|  varchar(255)	| No 	 	 	 
siteurl  |	varchar(255)		| No 	 	 	 
sitetitle	| varchar(255)	| No 	 	 	 
time	|  int(255)			| No 	
email	|  varchar(255)		| No 	 	 	 
schema_version	|  varchar(10)	| Yes 		 
template	|  varchar(255)	| No 	 	 	 
keywords	|  text			|  No 	 	 	 
description	| text		|	No 	 	 	 
vistis	| int(255)		|	No 	0 	 	 
sitestate	| int(255)		|  No 	0 	 	 
sitestatemsg	| text		|  No 	 	 	 
analytics			|  text	Yes   |	NULL 	 	 
resend_activation_threshold	| varchar(150)	 | Yes 	 	 	 
activation 	|  varchar(150) 	|  Yes 		 	 
language	 |  varchar(250)	| Yes

**Comment by avbdr** [comment]
Can you please try this patch?

 ```
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -786,7 +786,7 @@ class MysqliDb
 
         // avoid out of memory bug in php 5.2 and 5.3
         // https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119
-        if (version_compare (phpversion(), '5.4', '<'))
+        //if (version_compare (phpversion(), '5.4', '<'))
              $stmt->store_result();
 
         call_user_func_array(array($stmt, 'bind_result'), $parameters);
```

**Comment by abdul202** [comment]
Thank you there was another filed with longtext and after optimizing the database to use less data types the error disappear for now
thank you for help

**Comment by avbdr** [comment]
If its not much troubles, can you please put longtext field back, and test the following patch? 

```php
diff --git a/MysqliDb.php b/MysqliDb.php
index 7b3b545..32fddc7 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -769,6 +769,9 @@ class MysqliDb
     {
         $parameters = array();
         $results = array();
+        // See http://php.net/manual/en/mysqli-result.fetch-fields.php
+        $mysqlLongType = 252;
+        $shouldStoreResult = false;
 
         $meta = $stmt->result_metadata();
 
@@ -780,13 +783,17 @@ class MysqliDb
 
         $row = array();
         while ($field = $meta->fetch_field()) {
+            if ($field->type == $mysqlLongType)
+                $shouldStoreResult = true;
+
             $row[$field->name] = null;
             $parameters[] = & $row[$field->name];
         }
 
-        // avoid out of memory bug in php 5.2 and 5.3
+        // avoid out of memory bug in php 5.2 and 5.3. Mysqli allocates lot of memory for long*
+        // and blob* types. So to avoid out of memory issues store_result is used
         // https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119
-        if (version_compare (phpversion(), '5.4', '<'))
+        if ($shouldStoreResult)
              $stmt->store_result();
 
         call_user_func_array(array($stmt, 'bind_result'), $parameters);
```

**Comment by abdul202** [comment]
unfortunately i can't the issue was to one of my customers and he changed the password of the cpanel
