### ISSUE TITLE
UPDATE after INSERT failing (Call to a member function execute() on a non-object))

### ISSUE THREAD

**Issue by jonnysmith1981** [joshcam/PHP-MySQLi-Database-Class#252]
I have a chuck of PHP code that does an initial insert and returns an id. This works fine. I then need to do some more processing then update that record. The code is as follows:

	$custid = $db->insert('Cust_T', $appdata);

        <do some more processing>

	$db->where('customer_id' ,$custid);
	$db->update('Cust_T', $referencedata);

So the initial INSERT work, but then the subsequent UPDATE fails with the following error:

Call to a member function execute() on a non-object in /var/www/www.mywebapp.com/public_html/lib/mysqlidb.php on line 444

**Comment by avbdr** [comment]
please try latest master and let us know

**Comment by jonnysmith1981** [comment]
Same result with the latest from master

**Comment by avbdr** [comment]
do you have any errors before this?

**Comment by jonnysmith1981** [comment]
No, nothing.

I am not sure if it#s clear from my first post, but the insert and update are being done in the same PHP file. This is ok isnt it? I had problems in the past with mysqli and multiple prepared statements if i did not use the Store_result() function.

**Comment by avbdr** [comment]
Thats what i did.

```php
$id = $db->insert("users", Array (
                'login' => 'user10',
               'customerId' => 10,
               'firstName' => 'John',
               'lastName' => 'Doe',
               'password' => $db->func('SHA1(?)',Array ("secretpassword+salt")),
               'createdAt' => $db->now(),
               'expires' => $db->now('+1Y'),
               'loginCount' => $db->inc()
));

$db->where("id", $id);
print_r ($db->getOne("users"));

$db->update ("users", Array ('login' => 'user11'));

$db->where("id", $id);
print_r ($db->getOne("users"));
```

```
Array
(
    [id] => 7
    [login] => user10
    [active] => 0
    [customerId] => 10
    [firstName] => John
    [lastName] => Doe
    [password] => 546f98b24edfdc3b9bbe0d241bd8b29783f71b32
    [createdAt] => 2015-07-01 12:16:30
    [expires] => 2016-07-01 12:16:30
    [loginCount] => 1
)
Array
(
    [id] => 7
    [login] => user11
    [active] => 0
    [customerId] => 10
    [firstName] => John
    [lastName] => Doe
    [password] => 546f98b24edfdc3b9bbe0d241bd8b29783f71b32
    [createdAt] => 2015-07-01 12:16:30
    [expires] => 2016-07-01 12:16:30
    [loginCount] => 1
)
```

**Comment by avbdr** [comment]
what php version you are using?

**Comment by jonnysmith1981** [comment]
5.4.16

**Comment by avbdr** [comment]
how do you initialize mysqlidb() ?

**Comment by jonnysmith1981** [comment]
$db = new MysqliDb ('localhost','lead',''passwordshhhhh,'leads');

**Comment by Izopi4a** [comment]
jonnysmith1981, may be just check if function "reset" is being called in thr MySQLi wrapper ?

**Comment by avbdr** [comment]
Can you run one more time with this patch and send an output of the print_r (). you can hide mysql creds from there :)
```php
diff --git a/MysqliDb.php b/MysqliDb.php
index 7b3b545..f09bd9f 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -438,6 +438,7 @@ class MysqliDb
         $this->_query = "UPDATE " . self::$prefix . $tableName;
 
         $stmt = $this->_buildQuery (null, $tableData);
+        print_r ($this);
         $status = $stmt->execute();
         $this->reset();
         $this->_stmtError = $stmt->error;
```

**Comment by avbdr** [comment]
have you managed to fix your problem?

**Comment by MohamedAmine-C** [comment]
i think this error happens when you try to excute wrong query

**Comment by nnarbone** [comment]
what is $referencedata?

**Comment by avbdr** [comment]
i will close this because of incomplete test case. Most likely bug were caused because of some additions to vanila mysqlidb code or some extends/overrided constructor
