### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by dev10calypso** [joshcam/PHP-MySQLi-Database-Class#253]
I'm tired to use rawQuery in class because not working and then if i try manual query it's work

this is mysql  code
$params=array('2015-07-02', '2015-07-03', '2015-07-02', '2015-07-03');
$qr=$db->rawQuery('SELECT roomtype.roomtypeid, roomtype.roomtypename, roomcategory . * , COUNT( booking.roomtypeid ) AS inhouse
FROM roomtype
LEFT JOIN (
    SELECT roomcategory.roomtypeid, (COUNT( roomcategory.roomno )-COUNT( roomclose.roomno )) AS availablerooms
    FROM roomcategory
    LEFT JOIN rooms ON rooms.roomno = roomcategory.roomno AND rooms.roomstatus =1
    LEFT JOIN roomclose ON roomclose.roomno=roomcategory.roomno AND roomclose.closedate BETWEEN ? AND ?
    GROUP BY roomcategory.roomtypeid
) AS roomcategory ON roomcategory.roomtypeid = roomtype.roomtypeid

LEFT JOIN booking ON booking.roomtypeid = roomtype.roomtypeid
AND (
booking.checkoutdate > ?
AND booking.checkindate <=  ?
)
AND booking.bookingstatus
IN ( 1, 2, 3, 5, 6, 8 ) 
GROUP BY roomtype.roomtypeid', $params);

**Comment by avbdr** [comment]
use rawQuery($sql,$params,false);

**Comment by dev10calypso** [comment]
what is false? why false? can u explain?

**Comment by avbdr** [comment]
its disabling query string filtering. I think this should be a default behavoir soon.

**Comment by dev10calypso** [comment]
ohh thank you very much.
