### ISSUE TITLE
dbObject get returning data with NULL

### ISSUE THREAD

**Issue by coolbalyan** [joshcam/PHP-MySQLi-Database-Class#254]
when i extends dbObject and called get method it was retuning object with DATA with NULL value but mysqli class returning data but when i pasted "$item->data = $this->data;" at line 332 it working fine please check if i was done wrong or it is a problem

**Comment by avbdr** [comment]
can you share some test code which is failing?

**Comment by avbdr** [comment]
can you please check following patch:
```php
diff --git a/dbObject.php b/dbObject.php
index d2a67f1..1a973d1 100644
--- a/dbObject.php
+++ b/dbObject.php
@@ -109,7 +109,7 @@ class dbObject {
         if (empty ($this->dbTable))
             $this->dbTable = get_class ($this);
 
-        if ($data)
+        if (is_array ($data) && count ($data) > 0)
             $this->data = $data;
     }

```

**Comment by coolbalyan** [comment]
I have created this changes to get work
    /********
        $item = new static ($results);
        $item->isNew = false;
     */
        $item = clone $this;
        $item->isNew = false;
 this is where i extends dbObject class
<?php
class Items extends dbObject{
protected $dbTable = 'items';
protected $primaryKey = 'ID';
 public function __construct($data=null){
parent::__construct($data=null);
}
 }
?>
And when i call it like this $items_obj have data Null
 $items_obj = new Items();
$items_obj = $items_obj->get();

and i will check your patch and give you reply thank you for view it

On Sat, Jul 4, 2015 at 12:48 PM, Alexander Butenko <notifications@github.com

**Comment by avbdr** [comment]
your problem is in constructor. you are calling parent::__construct() with $data set to null.
