### ISSUE TITLE
Fatal error: Problem preparing query (INSERT INTO

### ISSUE THREAD

**Issue by abdul202** [joshcam/PHP-MySQLi-Database-Class#258]
i always get this error with insert and to fix it i have to use Generic Query Method
i use class version version   2.1
mysql version  5.6.12

my code is
```php
    $table = 'sites';                              //this table name is  articles
    $update_site_array['last_vb_submitted']= "$last_processed_vb";
    $update_site_array['last_time_submitted']= time();
    $db->where ('url', $url_submitted);  // column name and value
    if($db->insert($table, $update_site_array)) echo 'success!';
```
the complete error is
```error
Fatal error: Problem preparing query (INSERT INTO sites (`last_vb_submitted`, `last_time_submitted`) 
VALUES (?, ?) WHERE url = ? ) You have an error in your SQL syntax; check the manual that 
corresponds to your MySQL server version for the right syntax to use near 'WHERE url = ?' at line 1 in 
F:\wamp\www\vb_submitter\includes\MysqliDb.php on line 1084
```

Thanks

**Comment by avbdr** [comment]
i have a feeling that you need to use update() instead of insert()?
what sql query do you expect to execute with this piece of code?

**Comment by abdul202** [comment]
you are right i should use  update() instead of insert() here
anyway sometimes i get this error with some queries and to fix it i used Generic Query Method
next time when i face the same error i will post all the code here
Thank you for your time and effort

**Comment by laratutoteam** [comment]
Solution here https://laratuto.com/insert-data-in-mysql-php/
