### ISSUE TITLE
Replace INTO

### ISSUE THREAD

**Issue by jackbrown1993** [joshcam/PHP-MySQLi-Database-Class#260]
Can't seem to get this to work, am I doing something wrong?

Using:

$data = Array(
'token' => $hash,
'username' => $username
);
$db->replace('asl_password_reset_tokens', $data);

Error:

Fatal error: Problem preparing query (REPLACE INTO asl_password_reset_tokens SET ?, ?) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?, ?' at line 1

**Comment by avbdr** [comment]
dup of #248
