### ISSUE TITLE
not working where < in rawquery method

### ISSUE THREAD

**Issue by doitajin** [joshcam/PHP-MySQLi-Database-Class#261]
$this->query = "SELECT a.vehicleid, b.vehiclename, b.registrationno FROM tp_fc a INNER JOIN tp_vehicle b ON a.vehicleid = b.id WHERE a.totalnoofdays < ?";

$this->result = $this->db->rawQuery($this->query, array(30));

return $this->db->getLastQuery();

This is my code, this code returns an warning and query like below

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in C:\xampp\htdocs\transport\Classes\db.class.php on line 251
SELECT a.vehicleid, b.vehiclename, b.registrationno FROM tp_fc a INNER JOIN tp_vehicle b ON a.vehicleid = b.id WHERE a.totalnoofdays

**Comment by avbdr** [comment]
$this->result = $this->db->rawQuery($this->query, array(30), false);
