### ISSUE TITLE
mysqli_stmt::bind_param() error 

### ISSUE THREAD

**Issue by dev10calypso** [joshcam/PHP-MySQLi-Database-Class#262]
I have error in rawQuery  how to fix it i'm using php 5.3.24
$sql='SELECT * FROM  promotions WHERE  roomtypeid='.$roomtypeid.'
                                    AND bookfrom <= ? AND bookto >=  ?
                                    AND arrival <= ? AND departure >= ?
                                    AND '.$numnight.' >= minstay  AND '.$numnight.' <= maxstay
                                    AND activestatus = 1';

$params = array('2015-07-17', '2015-07-17', '2015-07-17', '2015-07-17');

Warning: mysqli_stmt::bind_param() [mysqli-stmt.bind-param]: Number of variables doesn't match number of parameters in prepared statement in MysqliDb.php on line 252

**Comment by avbdr** [comment]
$db->rawQuery($sql, $params, false);
