### ISSUE TITLE
Cannot query int = 0

### ISSUE THREAD

**Issue by LouisBHirst** [joshcam/PHP-MySQLi-Database-Class#265]
Hi!  Loving the library but ran into a problem tonight - I can't query an int for 0.

Here's the setup:

                $this->db->where ('x1', $x, ">=");
                $this->db->where ('x2', $x, "<=");
                $this->db->where ('z1', $z, ">=");
                $this->db->where ('z2', $z, "<=");                                
                $this->db->where ('serverid', 0);
                $this->db->where ('world', $world);
                $result = $this->db->get("plots");

here is db->getLastQuery() : 

Last Query = SELECT  * FROM plots WHERE  x1 >= '4'  AND x2 <= '4'  AND z1 >= '6'  AND z2 <= '6'  AND serverid AND world = 'factionszone' 

So you can see it just puts "AND serverid" ... w/o an equals sign.  

thanks!

**Comment by LouisBHirst** [comment]
I may have found a work around by doing this:

$this->db->where ('serverid', 0 . "");

**Comment by avbdr** [comment]
are you sure that you are using latest version from master?  I were fixing this recently.

**Comment by LouisBHirst** [comment]
is it safe to get from master?  I thought you would have a release?

**Comment by avbdr** [comment]
yes, there were no major changes

**Comment by avbdr** [comment]
new version tagged. Please confirm that your issue could be closed. thanks

**Comment by avbdr** [comment]
closing as fixed
