### ISSUE TITLE
Column alias

### ISSUE THREAD

**Issue by shahab74** [joshcam/PHP-MySQLi-Database-Class#266]
Is there anyway I can use column alias without using raw query? For example column is called Author in DB but I want to display it as artist? 

Also using rawquery I cannot get "if statement" to work for example : 

$this->db->rawQuery("SELECT ItemName AS title, if( length( ItemAuthor ) < 2 || ISNULL( ItemAuthor ) , 'Unknown', ItemAuthor ) AS author from tblBooks")", false)

The error I get : Problem preparing query (SELECT ItemName AS title, if( length( ItemAuthor )  '20150721100146')) 

Please help

**Comment by avbdr** [comment]
Use get('tbl',null,"cola as a, colB as b").

As for second issue please update from master

**Comment by shahab74** [comment]
Thank you it now works great!
