### ISSUE TITLE
Fatal error: Call to undefined method MysqliDb::ObjectBuilder()

### ISSUE THREAD

**Issue by nx679** [joshcam/PHP-MySQLi-Database-Class#268]
I have included "MysqliDb.php" into my project. When writing an [Object Query](https://github.com/joshcam/PHP-MySQLi-Database-Class#select-query) I' am getting the following error.

###### Error Message:
> Fatal error: Call to undefined method MysqliDb::ObjectBuilder()

###### Object Query (Doesn't Work):
```
$get_pages = $db->ObjectBuilder()->getOne("pages");
echo $get_pages->id;
```

###### Normal Query (This Works):
```
$get_pages = $db->getOne("pages");
echo $get_pages["id"];
```

I' am using it on Windows Machine with XAMPP. MySQLI Extension is available.

**Comment by avbdr** [comment]
Do you have latest source from master?

**Comment by nx679** [comment]
Yes I do

**Comment by nx679** [comment]
Sorry my bad, I downloaded it few weeks ago and the latest copy is 6 days ago. I downloaded the latest copy and it started to work. Thanks!
