### ISSUE TITLE
$db->where doesn't use the clause if empty

### ISSUE THREAD

**Issue by DanieleRatti** [joshcam/PHP-MySQLi-Database-Class#269]
If you forget to set a variable and try to use a $db->where clause on an update, instead of giving error "missing XXX" it execute the query without the where!

It can cause extremely problematic results.

Is it possible to get an error in this case?

**Comment by avbdr** [comment]
I agree. Will try to figure out something in couple days

**Comment by avbdr** [comment]
oh, i forgot that I already fixed this issue in https://github.com/joshcam/PHP-MySQLi-Database-Class/commit/03e5d76867ac400041926b0e66d858659adfc7cc

Please make sure you are using latest master.

**Comment by DanieleRatti** [comment]
Thank you!
