### ISSUE TITLE
Support for ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#270]
I would love to see support for ON DUPLICATE KEY UPDATE in this library. Perhaps it could look something like this?

```php
  $insert = array(
    'id'=> $id, 
    'address' => $address,
    'city' => $city,
    'state' => $state);
    
  $update = array(
    'address' => $address,
    'city' => $city,
    'state' => $state);
  
  $db
    ->onDuplicate($update)
    ->insert('people', $insert);

```

Which would translate into:
```sql
INSERT INTO people (id, address,city,state)
VALUES (?,?,?,?)
ON DUPLICATE KEY UPDATE
  address=?,city=?,state=?
```

Currently I use rawQuery() to do this. Have I missed another way?

Also, the code above points out an obvious optimization for this case, but I don't know if it would be generally applicable or not, but I'll mention it anyway. String format routines in a lot of languages have the ability to do param replacement, and also have a way of resetting the param index pointer in order to re-use params previously declared. So the above case could be simplified to:

```php
$db
  ->onDuplicate(1)
  ->insert('people', $insert);
```

The onDuplicate method would check for an array (1st case), or an integer. When an integer is used, it's interpreted as a parameter array index on the original insert data, and the sql generator basically starts at that offset in the insert params, and repeats those columns/values in the ON DUPLICATE KEY UPDATE portion (with its annoying different syntax).

Just some ideas! Thanks for a great library - I used this library on all my projects, and love it.

Thanks!
Dave

**Comment by avbdr** [comment]
thats a nice spec :) thank you. I like proposed API. Will try to implement that during the week.

**Comment by scoman81** [comment]
Wow, thank you!

My original example has a flaw in it, as compared to typical real-world usage. That is, the "id" field is probably not something someone would insert! A more realistic case is where there is an auto-increment ID field, and the key violation might instead occur on another field, say "name" for example. It's quite common to want "insert this row, but if it already exists, update these columns, AND give me back the ID of the existing row." MySQL has a very useful (but perhaps not well known) feature for this usage case.

Their example from https://dev.mysql.com/doc/refman/5.0/en/insert-on-duplicate.html:

```sql
INSERT INTO table (a,b,c) VALUES (1,2,3)
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id), c=3;
```
This causes LAST_INSERT_ID to return the row's ID (auto-increment) column, which is brilliant. 

This is really useful if you're using a fully normalized database. For example:

```php
$sales->insertSale($productName, $customerName, $amount);
```
If you have a products table, a customers table, and a sales table, you'd need to:
a) insert/update the product, and get its ID
b) insert/update the customer, and get their ID
c) insert $productID, $customerID, $amount into the sales table

The tricky part here would be how to express this LAST_INSERT_ID(id) concept in your library, but if there is a way, it would be incredibly useful.

Thinking out loud ...
```php
$data = array("name"=>$customerName, "lastseen"=>$db->now());
$id = $db
  ->onDuplicate(1)
  ->insert("customers", $data);
```
Now $id is only valid if the row was inserted. It's useless if it was updated. So here's a couple (possibly horrible) ideas:

```php
$id = $db
  ->onDuplicate()
  ->insertID("id")
  ->insert("customers", $data);
```
or
```php
$id = $db
  ->onDuplicate()
  ->idColumn("id")
  ->insert("customers", $data);
```

Or maybe something totally different?

```php
$insertData = array(
  "name"=>$customerName,
  "lastseen"=>$db->now()
);
$updateData = array(
  "lastseen"=>$db->now(),
  "id" => $db->insertID("id")
);

```

If it's possible, getting this "id = LAST_INSERT_ID(id)" concept in there would make this addition incredibly useful!

Anyway, just more ideas :) Thanks again for your consideration and time. Your work is very much appreciated!
Dave

**Comment by rongzhj1990** [comment]
Hello, I've implemented a simple version of the on duplicate function.
usage:
```PHP
$video_info = array();
$video_info["ctime"] = $video_info["utime"] = time();
$video_info["like_count"] = 999;
$video_info["code"] = "abcd";
$updateColumns = array("utime", "like_count");
$db->onDuplicate($updateColumns, "id");
$db->insert("video_info", $video_info);
```
[My Fork](https://github.com/rongzhj1990/PHP-MySQLi-Database-Class)
Hope it helps.

**Comment by avbdr** [comment]
looks great except you need to clearout updateColumns and lastInsertId in reset() function.
Can you please update readme, tests/mysqlidbtests.php and submit a pull request? 
I will commit it as is.

**Comment by rongzhj1990** [comment]
Sure, it's my pleasure.

**Comment by avbdr** [comment]
looks great. I will review tomorrow and will commit. Thank you for your time.

**Comment by rongzhj1990** [comment]
Cool, I am not sure if my modification would break something which works previously, please let me know if I am doing something wrong :)

**Comment by avbdr** [comment]
thanks. I have landed you patch and as well removed your copypaste of the insert stuff + fixed a bug you have made in last_insert_id() generation. 
thank you.

**Comment by rongzhj1990** [comment]
Great ! I have little question for the test case of this method in tests/mysqlidbtests.php
```php
if ($nUser[0]['createdAt'] == $nUser[0]['updatedAt']) {
    echo "onDuplicate2 update failed. ";
    exit;
}
```
I am afraid that this will be always true, because the interval between the previous insertion of user3  and this one should be too short to reflect changes, would it be better to choose another column, e.g. password?

You are really hard working, thanks for your appreciation

**Comment by avbdr** [comment]
good point. I will address this later on
