### ISSUE TITLE
More information on replace function

### ISSUE THREAD

**Issue by joshbenhamou** [joshcam/PHP-MySQLi-Database-Class#276]
Hi! Absolutely fantastic library, thanks very much!

I was looking to implement a replace query but the documentation just says to use the same as the insert function. I don't understand how this would work as I am trying to replace a specific string with another string in a column value.

I've implemented this as a raw query for the moment but it would be great to use the library, if possible

Thanks!

**Comment by avbdr** [comment]
replace () is for https://dev.mysql.com/doc/refman/5.0/en/replace.html
you are looking for db->update(['field' => $db->func('replace(...)')])

**Comment by joshbenhamou** [comment]
Thanks! Works perfectly
