### ISSUE TITLE
Different query executed (wrong)

### ISSUE THREAD

**Issue by DanieleRatti** [joshcam/PHP-MySQLi-Database-Class#285]
Hello, I don't understand why if I run this rawQuery:

$db->rawQuery("SELECT * FROM users WHERE signup_date >= '$date_from' AND signup_date <= '$date_to' GROUP BY YEAR(date)");

I obtain this other one in the last executed query:

Last executed query was SELECT * FROM users WHERE signup_date >= '2015-01-01' AND signup_date

How can I run the exact query I ask for?

**Comment by avbdr** [comment]
please update mysqlidb to 2.2 or master
