### ISSUE TITLE
Native code not store in Mysql DB

### ISSUE THREAD

**Issue by darshancodepix** [joshcam/PHP-MySQLi-Database-Class#291]
I am trying to store IOS and Android native emojis code store in Mysql DB but it's not working.
It's making blank value.

Please help me where i am wrong.

Thanks.

**Comment by avbdr** [comment]
please post the code which is storing data into the table.

**Comment by darshanopenxcell** [comment]
Thanks for reply..

Here is update query, which is store emojis Native value from IOS. But is store in DB like  "????"
You can take native value from this site http://apps.timwhitlock.info/emoji/tables/unicode


require_once ('MysqliDb.php');
$db = new MysqliDb ('xxxxx', 'xxxxx', 'xxxxx', 'xxxx');



$data = array(
    'content' => 'test 😊'
);
$db->where ('id', 15);
if ($db->update ('posts', $data))
    echo $db->count . ' records were updated';
else
    echo 'update failed: ' . $db->getLastError();

**Comment by avbdr** [comment]
https://dev.mysql.com/doc/refman/5.0/en/charset-column.html

**Comment by darshanopenxcell** [comment]
I already done.
posts table character set utf8mb4_unicode_ci and content column character set utf8mb4_unicode_ci

**Comment by avbdr** [comment]
then your emoticon is in the wrong encoding. try http://unicodeemoticons.com/

**Comment by darshanopenxcell** [comment]
Ok, Thanks.
