### ISSUE TITLE
Why does this class dont use mysqli_free_result

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#295]
Hi Team,

I have almost replaced my existing mysqli class with this great and nicely written class. I use so many sql queries in my website, and when i looked into this class i did not see uses of mysqli_free_result - Frees the memory associated with a result when your result object is not needed anymore.

is there any reason why we are not using in this class? 
how this class frees the memory.

Thank you

**Comment by avbdr** [comment]
we are fetching results by references. Thats why its not needed to mysqli_stmt_free_result in the most cases. 
In fact after looking at the code I found that we are not closing prepared statement when not needed.
I have fixed that in master. Thanks.

**Comment by rajjanorkar** [comment]
Thank you very much @avbdr

**Comment by rajjanorkar** [comment]
Hi @avbdr, I can see there are so many changes since last release, If it is fully tested then please do next release.

Thank you in advance.

**Comment by avbdr** [comment]
you can use master. Its always safe to use. I have some more features to implement before release, so it wont happen till next month.

**Comment by rajjanorkar** [comment]
ok no worries.. thank you so much.. it's really great mysqli class.
