### ISSUE TITLE
Get a matching return status after an UPDATE

### ISSUE THREAD

**Issue by sp-kilobug** [joshcam/PHP-MySQLi-Database-Class#297]
Hi, 
I would like to convert this code to use a MysqliDb connection.
I need to know exactly what failed during an update.
Thanks

```php
$stmt = $mysqli->prepare("UPDATE mytable SET data = ? WHERE id = ? AND username = ?");
$stmt->bind_param('sis', $data, $id, $username);
$stmt->execute();

if (!isset($stmt->id)) {
   error('id not found');
}
elseif (!isset($stmt->username)) {
   error('username not matching record');
}

```

**Comment by avbdr** [comment]
are you sure that this code is working? :)

**Comment by sp-kilobug** [comment]
you're right this code is totally wrong ! ;) 
I need to know if the record exist (key "id" = $id), and if the given $username match the record. 
Can we do that in only one request (UPDATE) and check the result ?

**Comment by avbdr** [comment]
its impossible to know that. update returns only number of the rows affected. 
Maybe you interested in onDuplicate() functionality? 
https://dev.mysql.com/doc/refman/5.0/en/insert-on-duplicate.html

**Comment by sp-kilobug** [comment]
thank you :)
