### ISSUE TITLE
MySQL operator <>

### ISSUE THREAD

**Issue by HarpyWar** [joshcam/PHP-MySQLi-Database-Class#30]
It doesn't work with operator "<>" in sql query.

**Comment by PetengDedet** [comment]
I have tried to replace "FILTER_SANITIZE_STRING" with "FILTER_SANITIZE_MAGIC_QUOTES" in class file. that is occur for 3 times, right?

but this code didn't shows anything in browser. i don't know why.
```php
<?php
ini_set('display_errors',1);  error_reporting(E_ALL);

include'class/MysqliDb.php';
$crud = new MysqliDb();
$result = $crud -> rawQuery('SELECT * FROM user WHERE iduser<5');
foreach ($result as $key => $value) {
	print_r($value);
}
?>
```

**Comment by avbdr** [comment]
with latest version you can disable filtering. 
 $crud -> rawQuery('SELECT * FROM user WHERE iduser<5', null, false);
also for a security reasons you might want to use bind variables instead of adding them into sql.
 $crud -> rawQuery('SELECT * FROM user WHERE iduser< ?', Array(5), false);

**Comment by avbdr** [comment]
could be closed already
