### ISSUE TITLE
rawQueryValue only returns Ids

### ISSUE THREAD

**Issue by brad13x** [joshcam/PHP-MySQLi-Database-Class#300]
Upgrading some old code to mysqli and I can't get this to return correct values. What am I missing.

$test = "SELECT *, ER.email_ip as er_ip, E.email_ip as e_ip FROM emails_received ER LEFT JOIN emails E ON ER.email_id = E.email_id WHERE ER.email_status != 10 order by ER.email_received_id DESC LIMIT 0,100";
 
 $emails = $db->rawQueryValue($test);
only gives me a list of emails_received Ids.

**Comment by avbdr** [comment]
use rawQuery () to get all the rows. rawQueryValue() is a helper function which returns only first column of the result.
