### ISSUE TITLE
$db->insert method adding slashes to the post value string 

### ISSUE THREAD

**Issue by rahul-spartan** [joshcam/PHP-MySQLi-Database-Class#301]
When a i use a insert method like $db->insert($tableName, $insertData); if there are quotes in any string in post variable, this method is automatically adding slashes. It should be or it shouldn't be according to you gurus. what you gurus suggest?

**Comment by avbdr** [comment]
i dont think this is caused by the library. Maybe you have magic_quotes_gpc enabled? Or you are calling addslashes or escape() function before insert() somewhere.

**Comment by rahul-spartan** [comment]
require("SRAdmin/MySqlDb.php");

$db=new MySqlDb();

$text="This isn't joking";

$text=$db->escape($text);

$q=$db->query("insert into dummy (Dum_text) values ('$text')");

echo $db->getInsertId();

The above query doesn't put slashes. But the below one does put slashes. I have test these two queries in the same localhost server.


$insertData=array("Dum_text"=>"$text");

$db->insert("dummy", $insertData);

**Comment by rahul-spartan** [comment]
This is the server config
![test](https://cloud.githubusercontent.com/assets/13449713/9379798/6aa7664c-4749-11e5-9bdd-ef7a839e2a09.JPG)

**Comment by avbdr** [comment]
Set magic quotes to off and retry your test.
You are using very old php :)

**Comment by rahul-spartan** [comment]
ya i disabled magic quotes and tried it without escaping the $_post variables. Now its working. Thanks Alexander.
