### ISSUE TITLE
delete with inner join

### ISSUE THREAD

**Issue by Menusito** [joshcam/PHP-MySQLi-Database-Class#302]
the class breaks or dont have support with delete and the join method

**Comment by avbdr** [comment]
Can you provide a sniplet of code which doesn't work?

**Comment by Menusito** [comment]
$db->join("images ima", "ima.idUser=u.idUser", "INNER");
$db->where("u.idUser", $idUserToDelete);
$db->delete("users u");

something like this

**Comment by avbdr** [comment]
i see, indeed, syntax here will be slightly diferent. I will work it out later on. 
thanks for a bugreport

**Comment by avbdr** [comment]
please try latest master. i have commited a fix
