### ISSUE TITLE
getValue() returns array() instead of NULL

### ISSUE THREAD

**Issue by jackbrown1993** [joshcam/PHP-MySQLi-Database-Class#304]
Hi,

When using the getValue function the class seems to be returning an empty array instead of just returning NULL, anyone else seen this?

Thanks,

Jack.

**Comment by avbdr** [comment]
Hello,

Can you try this patch? 
```
diff --git a/MysqliDb.php b/MysqliDb.php
index 4d91176..f4ac4fa 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -497,7 +497,7 @@ class MysqliDb
     {
         $res = $this->ArrayBuilder()->get ($tableName, $limit, "{$column} AS retval");
 
-        if (!$res)
+        if ($this->count == 0)
             return null;
 
         if (isset($res[0]["retval"]) && $limit == 1)
```

**Comment by jackbrown1993** [comment]
Thanks for quick reply, will take a look now.

**Comment by jackbrown1993** [comment]
Still doesn't looks like it works

SELECT project_manager AS retval FROM projects WHERE id = '1318'

The value in the database is NULL;

Result:
Array ( [0] => ) 


This is the current getValue function:

public function getValue ($tableName, $column, $limit = 1)
    {
        $res = $this->ArrayBuilder()->get ($tableName, $limit, "{$column} AS retval");

        if ($this->count == 0)
            return null;

        if (isset($res[0]["retval"]) && $limit == 1)
            return $res[0]["retval"];

        $newRes = Array ();
        for ($i = 0; $i < $this->count; $i++)
            $newRes[] = $res[$i]['retval'];
        return $newRes;
    }

**Comment by avbdr** [comment]
can you see what is the value of $this->count ?

**Comment by madnutter56** [comment]
Hi, I'm working with Jack on this.

$this->count = 1 when it returns Array ( [0] => )

**Comment by avbdr** [comment]
can you do print_r ($res)?

**Comment by madnutter56** [comment]
Array ( [0] => Array ( [retval] => ) )

**Comment by avbdr** [comment]
and what does raw sql returns in the mysql cli?

**Comment by madnutter56** [comment]
mysql> SELECT project_manager AS retval FROM projects WHERE id = '1318';
+--------+
| retval |
+--------+
| NULL   |
+--------+
1 row in set (0.00 sec)

**Comment by avbdr** [comment]
also how do you call getValue()?

**Comment by madnutter56** [comment]
Call is as follows:

require_once ($_SERVER['DOCUMENT_ROOT'] . '/includes/database.class.php');
    $db->where('id', '1318');
    
    print_r($db->getValue('projects', 'project_manager'));
    echo $db->getLastQuery();

**Comment by avbdr** [comment]
ok, let me try to reproduce. weird.

**Comment by avbdr** [comment]
thanks. fixed in https://github.com/joshcam/PHP-MySQLi-Database-Class/commit/239730f4796976addbbfdcb7b961bd5009f479f9

**Comment by jackbrown1993** [comment]
Thank you!

**Comment by avbdr** [comment]
welcome. :)
