### ISSUE TITLE
Insert using select

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#307]
Hi Team,

I am struggling to prepare query, i dont want to use raw query.

INSERT INTO tab_module (uniq_id, posx, posy, module_id) 
        SELECT uniq_id, posx, posy, module_id FROM tab_module WHERE user_id = 1 and tab_id = 3

Any suggestion please.

Thank you.

**Comment by avbdr** [comment]
mysqlidb do not support insert from select unfortunately. use rawQuery() for this

**Comment by rajjanorkar** [comment]
Thank you @avbdr 
will use raw for this.
May be it is future enhancement then.

**Comment by avbdr** [comment]
marking as duplicate
