### ISSUE TITLE
Using CASE WHEN

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#308]
Hi Team,

I am trying to use CASE WHEN like below.

$next_seq = $db->subQuery();
        $next_seq->where("t.user_id", $user_id);
        $next_seq->getOne ("tab t", "CASE WHEN seq > 0 THEN MAX(t.seq) + 1 ELSE 1 END AS nextSeq");

$add_tab = array(
            "user_id" => $user_id,
            "name" => "$tab_name",
            "seq" => $next_seq
        );
        $new_tab_id = $db->insert("tab", $add_tab);

Is it correct way of using it.

Thank you.

**Comment by avbdr** [comment]
that should work. what error you are getting? Just in case make sure you are using latest stable version or master.

**Comment by rajjanorkar** [comment]
I use stable release now, and all good.
Thank you @avbdr
