### ISSUE TITLE
Using SET option for TEMP variable

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#311]
Hi Team,

Day by day i am getting very much familiar with this class so far it is really great class.

Today i am trying to use SET option for TEMP variable i read document but my situation is different.

First  "SET @count = 0"
then execute below query  to Reset uniq id of tab_id
"UPDATE IGNORE tab_module SET uniq_id = @count := @count + 1 WHERE user_id = 3 and tab_id = %1 ORDER BY uniq_id "

Anybody know how i should do it.

Thank you

**Comment by avbdr** [comment]
you do 2 separate queries. 
```
$db->rawQuery('set @count = ?', 0);
$db->where ...
$db->setQueryOptions ('IGNORE')->update ('tab_module', [
         'uniq_id' => $db->func ('@count + 1')
]);
```

**Comment by rajjanorkar** [comment]
Thank you @avbdr 
the first rawquery is fine but second query does not work. (i corrected typo). I think db->func does not deal with temp variable.
so i end up using another raw query.
# Initialise temp variable @count = 0
        $db->rawQuery("SET @count = ?", Array(0));
        # Re-Sequence the uniq_id for current tab
        $db->rawQuery("UPDATE IGNORE tab_module SET uniq_id = @count := @count + 1 WHERE tab_id = ? ORDER BY uniq_id ASC", Array($tab_id));

**Comment by avbdr** [comment]
hm, yes, you seems right, ' := ' seems is the issue

**Comment by avbdr** [comment]
oh, sorry, 
```
$db->rawQuery('set @count = ?', 0);
$db->where ...
$db->setQueryOptions ('IGNORE')->update ('tab_module', [
         'uniq_id' => $db->func ('@count := @count + 1')
]);
```
that should work.

**Comment by rajjanorkar** [comment]
Perfect... closing this now.
