### ISSUE TITLE
Inserting 50+ records using LOOP

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#312]
Hi Team,

I am inserting records in one of the table inside foreach loop. Now if i correctly understand in mysqli the advantage of using prepared query is it run fast once prepared and it is secure.(no sql injections)

But if my understanding is correct then in this class we are preparing query and at the end of the query we are deleting/freeing memory associated with prepared query. 

In my situation above i am running insert in loop, so every time i insert it prepares the query and then delete it.

So is there any way to retain prepared statement until i finish then at last delete it or when php script finished.

Thank you

**Comment by avbdr** [comment]
i suggest to sanitize your input by yourself and manually build insert sql query with multiple rows in 1 query. I were trying to reuse statement for this, but binding still makes huge overhead over a single insert.
if you still want to stick with regular insert (), to significantly save insert time you can do
```
$db->startTransaction();
serie of insert()
$db->commit();
```

take a look at https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/312

**Comment by avbdr** [comment]
if you have time and want to participate feel free to code fast multi insert for the lib :)

**Comment by rajjanorkar** [comment]
Thank you @avbdr ,
i think #312 is this issue i think it is typo.

Yes i love to contribute, i would see when time permit i will try to do something about it.

**Comment by rajjanorkar** [comment]
Can i use something like this?

       $this->DB->insert ('products_data', [
                 ['50', 'price', '400'],
                 ['51', 'price', '401'],
                 ['52', 'price', '402']
            ],
            ["product_id", "data", "value"]
       );

**Comment by avbdr** [comment]
closing as dup of https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/208
