### ISSUE TITLE
FOR UPDATE Test Result

### ISSUE THREAD

**Issue by rajjanorkar** [joshcam/PHP-MySQLi-Database-Class#315]
Hi @avbdr ,

I thought of testing it but it doesn't work. I am yet to find the why? will let you know.

          $db->startTransaction();
            $db->where('status', __DELETED);
            $db->setQueryOption('FOR UPDATE');
            $seminar = $db->getOne('seminar', 'id');
            if (!empty($db->count)) {
                # Update seminar status to submitting
                $seminar_update_status = array("status" => __SUBMITTING);
                $db->where('id', $seminar['id']);
                if ($db->update('seminar', $seminar_update_status)) {
                    # Change ownership of the seminar
                    $upload_update_user_id = array("user_id" => $user_id);
                    $db->where('seminar_id', $seminar['id']);
                    if ($db->update('upload', $upload_update_user_id)) 
                        $seminar_id = $seminar['id'];    
                } 
            }
            # either commit or rollback
            if(!empty($seminar_id)) 
                $db->commit();
            else 
                $db->rollback();     
        }

**Comment by avbdr** [comment]
can you please identify which part is failing?

**Comment by rajjanorkar** [comment]
Hi @avbdr ,

It gives error "wrong query option: FOR UPDATE mysql"

i search lot on google but no luck.. so I am simply not using it.

If you have any idea please let me know.

Thank you

**Comment by avbdr** [comment]
I think you havent updated library to the latest master. Please check.

**Comment by rajjanorkar** [comment]
I am using current library.
It just dont work.
