### ISSUE TITLE
How to use simple query without binding parameters?

### ISSUE THREAD

**Issue by rrricci** [joshcam/PHP-MySQLi-Database-Class#316]
Hello friends.. 

Is there any way to use simple queries like:

$user = 'admin';
$db->query("select * from users where username = $user");

I have tried to do it, but it came up with an error..

Thanks..

**Comment by KTP95** [comment]
I Think you can with rawQuery Method , i not sure about this.

    $db->rawQuery("select * from users where username = $user");

**Comment by rrricci** [comment]
Great!

I appreciate your help and fast response.

Thanks
Renato Ricci

**Comment by KTP95** [comment]
horever please note that rawQuery without bind parameter can be a bad idea in login form, I invite you to ead some article/documentation about SQL Injection https://it.wikipedia.org/wiki/SQL_injection

italian,
Occho, che puoi fare una grande cavolata. ;-)

**Comment by rrricci** [comment]
Ohh yes! I am aware of it.. Thanks for the advise!
Have a good weekend.
Renato Ricci
