### ISSUE TITLE
orderBy count(*)

### ISSUE THREAD

**Issue by LouisBHirst** [joshcam/PHP-MySQLi-Database-Class#317]
Hi!  Thanks again for the great library, I upgraded to the latest version and it's going nicely.  Lifesaver!

Found a small issue, when I try to orderBy count(*) I see your code is stripping the * out:

$db->orderBy("count(*)","desc");

Final output is "ORDER BY count()" ... which throws an error.

thanks!!

**Comment by avbdr** [comment]
Indeed. I will push a fix today. Thanks for a bugrepirt

**Comment by LouisBHirst** [comment]
Cool thanks!!

**Comment by avbdr** [comment]
please try this patch
```
diff --git a/MysqliDb.php b/MysqliDb.php
index 84011ad..f3cebd1 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -713,7 +713,7 @@ class MysqliDb
     {
         $allowedDirection = Array ("ASC", "DESC");
         $orderbyDirection = strtoupper (trim ($orderbyDirection));
-        $orderByField = preg_replace ("/[^-a-z0-9\.\(\),_`]+/i",'', $orderByField);
+        $orderByField = preg_replace ("/[^-a-z0-9\.\(\),_`\*]+/i",'', $orderByField);
```

**Comment by LouisBHirst** [comment]
Boom!   Works!  Thanks!

Bart Hirst
(484) 802-4798
http://www.linkedin.com/in/louisbhirst

**Comment by avbdr** [comment]
ok. fixed in master
