### ISSUE TITLE
onduplicate not working

### ISSUE THREAD

**Issue by weha** [joshcam/PHP-MySQLi-Database-Class#321]
I specify an onduplicate but it does not get used in the query:

`$sql['created']='NOW()';`
`$sql['year'] = date('o',$moment);`
`$sql['week'] = date('W',$moment);`
`$sql['text'] = $dbi->escape($text);`
`$dbi->onDuplicate('text');`
`$sql_result = $dbi->insert('calendar_weekcomments',$sql);`

$sql_result is empty/null/false

getlastquery: INSERT  INTO calendar_weekcomments (`created`, `year`, `week`, `text`)  VALUES ('NOW()', '2015', '37', 'testjedd')

So year & week are a key and a row already exists so in this scenario I can't save the new text for that week.
If there is no duplicate the query works.

**Comment by avbdr** [comment]
are you using latest stable/master?

**Comment by weha** [comment]
2.4, downloaded 3 days ago

**Comment by rajjanorkar** [comment]
$sql['created']=$db->now();
$sql['year'] = date('o',$moment);
$sql['week'] = date('W',$moment);
$sql['text'] = $db->escape($text);
$update_col = array("text");
$db->onDuplicate($update_col);
$db->insert('calendar_weekcomments', $sql);

**Comment by weha** [comment]
You are correct sir, I forgot the array part.
Maybe a feature request then, when it's a string convert to array?
Anyway, case closed.

Thank you
