### ISSUE TITLE
Never closing the connection

### ISSUE THREAD

**Issue by AbuJunayd** [joshcam/PHP-MySQLi-Database-Class#322]
Hello,

I am not sure if this is a bug or not.

I noticed that in the destructor the close function was never called:

    /**
     * Close connection
     */
    public function __destruct()
    {
        if (!$this->isSubQuery)
            return;
        if ($this->_mysqli)
            $this->_mysqli->close();
    }

Since the connections I open always have a username and password this->isSubQuery is always false.

So the close is never reached.

Is it the intended behavior?

Shouldn't the 1st condition be reversed, ie:

if ($this->isSubQuery)

?

Thank you

**Comment by avbdr** [comment]
thank you, you are correct. fixed in master

**Comment by AbuJunayd** [comment]
Great! I'm glad I could contribute a little bit :)
