### ISSUE TITLE
Update Query Sometimes clears whole table.

### ISSUE THREAD

**Issue by ashu7575** [joshcam/PHP-MySQLi-Database-Class#325]
Below is the code sample which i use for updating my table,
i get rest_id from request parameter and i pass it in where condition.
it works perfectly fine most of the times, but sometimes all the data from the table gets erased.
can anyone please guide me to track this issue at least.
- Thanks & Regards

$data = Array (
				"rest_time" => $rest_time,   
				"rest_cost_for_two" => $rest_cost_for_two,   
				"rest_is_affiliated" => $rest_is_affiliated,
				);
		$db->where('rest_id', $rest_id);
		$db->update('tb_restaurant_detail', $data);

**Comment by ATouhou** [comment]
Try debug $rest_id  if you depend on user input.  
Maybe it is not set :-)

**Comment by avbdr** [comment]
yes, most likely $rest_id sometimes gets empty and it updates whole table.
You need to upgrade to latest stable or latest master as this issue were fixed a while ago.

**Comment by ashu7575** [comment]
thanks for the reply and help :),
$rest_id was not passed by user from any input field, it was fetched and add to the url as parameter.
i was using at least 9-10 months old MysqliDb.php.
i'll upgrade it and try.
Thanks again :)
