### ISSUE TITLE
When using rawQuery results come empty

### ISSUE THREAD

**Issue by lewis-almeyda** [joshcam/PHP-MySQLi-Database-Class#327]
Hi:

I use this on my local but when I deploy it to the server, it performs the query with no errors, but the array the returns from rawQuery has the right column names, but everything is set the default value. 0 for ints and empty for the strings. THe only difference is the version (local 5.5 server 5.3). Would that be the problem? 

Thanks,

Luis

![image](https://cloud.githubusercontent.com/assets/6909245/9964852/e179b484-5def-11e5-926c-f5d7b953c4a4.png)

**Comment by avbdr** [comment]
i dont think its an issue of a library, more looks like your code. seems thats the result you are getting from the database.

**Comment by lewis-almeyda** [comment]
I don't think it's the library or the code, since it works on my local. Is still connecting to the database because the correct number of records are returned, my guess is that when converting the result of the query into the array (_dynamicBindResults function), something silently breaks and I can't figure out what it is.

**Comment by lewis-almeyda** [comment]
I should also mention that I tested the local apache calling the remote mySql and it worked, that's why I think is related to the php version. Do you have a minimum php version?

Thanks a lot, I really like the plugin.

**Comment by lewis-almeyda** [comment]
<?php
require_once('MysqliDb.php');
function nextSaleDatesMenu(){
    try
    {
    	global $db;
        $saleDates = $db->rawQuery('SELECT * FROM sales S WHERE S.show = 1 ORDER BY sale_date');
        echo '<ul class="dropdown-menu">';

        if($db->count == 0){
            echo '<li><a>No Sales Dates Available</a></li>';
        }
        else
        {	
		$currentYear = "";
            foreach ($saleDates as $date)
            {
		$d = DateTime::createFromFormat('Y-m-d',$date['sale_date']);

                if ($d->format('Y')!= $currentYear)
                {
                    
                    echo '<li><h4 class="text-center">'.$d->format('Y').'<h4></li> <div class="divider"></div>';
                    $currentYear = $d->format('Y');
               }
                
               echo '<li><a href="nextsale.html?date='.$d->format('Y-m-d').'">'.$d->format('F jS').'</a></li>';

                
            }
            
        }

        echo '</ul>';
    }
    catch (Exception $e)
    {
        echo 'Message: ' .$e->getMessage();
    }
}

**Comment by lewis-almeyda** [comment]
I'm also getting this warning on phpMyAdmin on the remote server:

Your PHP MySQL library version 4.1.22 differs from your MySQL server version 5.1.34. This may cause unpredictable behavior.

**Comment by avbdr** [comment]
most likely thats what causing you a problem. your php-mysqli were compiled with way too old mysql-client. maybe thats related. 

also please try the following patch:
```
diff --git a/MysqliDb.php b/MysqliDb.php
index 0fb936d..0e77ffc 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -969,7 +969,7 @@ class MysqliDb
         // avoid out of memory bug in php 5.2 and 5.3. Mysqli allocates lot of memory for long*
         // and blob* types. So to avoid out of memory issues store_result is used
         // https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/119
-        if ($shouldStoreResult)
+        //if ($shouldStoreResult)
              $stmt->store_result();
 
         call_user_func_array(array($stmt, 'bind_result'), $parameters);
```

**Comment by avbdr** [comment]
btw, im using library with php 5.3 on some servers and rawQuery works just fine there.

**Comment by avbdr** [comment]
have you found a problem?

**Comment by lewis-almeyda** [comment]
I'm still working with the ISP on the issue, I just had a question, this library uses a native php mysql library right? What's the exact name? (Sorry, I'm a little bit new on php)
The problem is that he does not want to upgrade their php server now, but maybe upgrade that particular library fixes everything.

**Comment by tommyknocker** [comment]
You need mysqli php extension (or mysqlnd if php >= 5.4)

**Comment by avbdr** [comment]
ill close this one as bug is more related to php configuration on a server side.
