### ISSUE TITLE
How to close the $db connect?

### ISSUE THREAD

**Issue by SimonWang2014** [joshcam/PHP-MySQLi-Database-Class#328]
I have already created a db connect , but how to close the connect when it's not been used any more?

**Comment by J2TeaM** [comment]
The class will auto close the connection for you.

![image](https://cloud.githubusercontent.com/assets/5250117/10014620/c4096cfc-6144-11e5-8449-6dbc267f5d34.png)

**Comment by tommyknocker** [comment]
You may set your MysqliDb object to null and this will call __destruct() method before script ends its execution.
