### ISSUE TITLE
Float precision in php 5.5.9

### ISSUE THREAD

**Issue by kopaygorodsky** [joshcam/PHP-MySQLi-Database-Class#330]
In php 5.5.9 (Ubuntu 14.04)
I  have problems with float values when select from db.
For example:
0,3 converted to 0.03000040430405. 
235.94 converted to 235.94000244141
Why?
This problem solved in php 5.6.13

**Comment by tommyknocker** [comment]
It's not the MysqliDb or mysqli object bug cause it's php core floating point bug based on floating point internal representation. See http://php.net/manual/en/language.types.float.php for details.
You may specify the desired presion of float value (using vsprintf, for example) or use BC Math functions: http://php.net/manual/en/ref.bc.php

**Comment by avbdr** [comment]
closing as not a library bug. as well you might try to workaround by defining precission in field type
like add fieldName double (10,2)
