### ISSUE TITLE
There is no $prefix declaration  on the MysqliDb  class 

### ISSUE THREAD

**Issue by beshoo** [joshcam/PHP-MySQLi-Database-Class#333]
Dear all

i did declare prefix  at the object creation 

                 $usersdb = new MysqliDb (Array (
                'host' => $data_DBhost,
                'username' => $users_DBuser, 
                'password' => $users_DBpassword,
                'db'=> $users_DBName,
                'port' => 3306,
                'prefix' => 'mytable_',
                'charset' => 'utf8'));

but if you look to the __construct on the MysqliDb you find no " $prefix " declaration 

    public function __construct($host = NULL, $username = NULL, $password = NULL, $db = NULL, $port = NULL, $charset = 'utf8')

and there is no

        $this->prefix = $prefix; 

after 

        $this->username = $username;
        $this->password = $password;
        $this->db = $db;
        $this->port = $port;
        $this->charset = $charset;

A FIX available here : 
http://pastebin.com/wUyYwvQs

**Comment by ATouhou** [comment]
It is currently done like this:
$db->setPrefix ('bs_');

**Comment by avbdr** [comment]
More then that, proposed fix as already available in master long time ago.

**Comment by avbdr** [comment]
It's even in your patched version :)
