### ISSUE TITLE
Foreign character problem on insert record

### ISSUE THREAD

**Issue by abasnet** [joshcam/PHP-MySQLi-Database-Class#335]
Hi 

I am having problem on inserting foreign character in the table.

$db->rawQuery("UPDATE table SET fieldname=''龙岗区中心" WHERE . ..... ");

There is no problem with the query but it saves as ?????? in the table.

Has anyone experienced this? The charset is set as UTF-8. 

Any help would be much appreciated.

Regards

Ash

**Comment by tommyknocker** [comment]
Check the character set in your database for this field `fieldname`. It should be smth like utf8_general_ci.

**Comment by abasnet** [comment]
Thanks for your help. It is collation: latin1_swedish_ci
