### ISSUE TITLE
Database table search

### ISSUE THREAD

**Issue by inavz** [joshcam/PHP-MySQLi-Database-Class#338]
I was not able to find any function about searching the database table. I was hoping if someone can help me out. I' am using the following query.

$songs = $db->ObjectBuilder()->rawQuery('SELECT * FROM songs WHERE song_name LIKE ?', array('%test%'));

The above query returns empty results whereas in the database table there are data that should match the keyword.

Thanks

**Comment by avbdr** [comment]
$songs =$db->where ('songs', '%test%', 'like');

**Comment by inavz** [comment]
Thanks!
