### ISSUE TITLE
Query works in pma, but not in php

### ISSUE THREAD

**Issue by trayanstoyanov** [joshcam/PHP-MySQLi-Database-Class#339]
I have this query : 
SELECT * from `polici_meta` u LEFT JOIN `polici_meta` u1 on u.polica_id = u1.polica_id WHERE u.meta_key='type_polica' and u.meta_value='1' GROUP BY u.polica_id

It works when i run it in pma, but in php code it doesn't. I run it like this : 
$query = "SELECT * from `polici_meta` u LEFT JOIN `polici_meta` u1 on u.polica_id = u1.polica_id WHERE u.meta_key='type_polica' and u.meta_value='1' GROUP BY u.polica_id"
$results = $db->query($query);
It gives me the following error :

 Fatal error: Problem preparing query (SELECT * from `polici_meta` u LEFT JOIN `polici_meta` u1 on u.polica_id = u1.polica_id WHERE u.meta_key='type_polica' and u.meta_value='1' GROUP BY u.polica_id) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''type_polica' and u.meta_value='1' GROUP BY u.polica_id' at line 1 in /home/moetobij/public_html/globallife/includes/MysqliDb.php on line 981

**Comment by avbdr** [comment]
You need to use rawQuery()

**Comment by trayanstoyanov** [comment]
Thanks, it worked :)
