### ISSUE TITLE
More coherent (num_rows)

### ISSUE THREAD

**Issue by iStocker** [joshcam/PHP-MySQLi-Database-Class#34]
Hello,

I've been looking for ways to get the data and that it can not be accessed with rawQuery class using the functions that come within the class, so I edited the class was as follows

/**
     * Pass in a raw query and an array containing the parameters to bind to the prepaird statement.
     *
     * @param string $query      Contains a user-provided query.
     * @param array  $bindParams All variables to bind to the SQL statment.
     * @param bool   $nr         Return num_rows or not...
     *
     * @return array Contains the returned rows from the query and if you want the num_rows.
     */
    public function rawQuery($query, $bindParams = null, $nr = false)
    {
        $this->_query = filter_var($query, FILTER_SANITIZE_STRING);
        $stmt = $this->_prepareQuery();

        if (is_array($bindParams) === true) {
            $params = array(''); // Create the empty 0 index
            foreach ($bindParams as $prop => $val) {
                $params[0] .= $this->_determineType($val);
                array_push($params, $bindParams[$prop]);
            }

            call_user_func_array(array($stmt, 'bind_param'), $this->refValues($params));

        }

        $stmt->execute();
        $stmt->store_result();
        $this->reset();

        $data[] = $this->_dynamicBindResults($stmt);

        if($nr)
            $data[] .= $stmt->num_rows;

        return $data;
    }

This works but I would like to know a better way to do it, if you can direct me I would appreciate it.

Thank you,
iStocker.

**Comment by avbdr** [comment]
$db->count variable stores resultset count now. Could be closed.
