### ISSUE TITLE
problem with get join and fields in table with the same name

### ISSUE THREAD

**Issue by Menusito** [joshcam/PHP-MySQLi-Database-Class#340]
i detect a problem when you make a join two tables that share field names.

example:

table 1:
idcategory (int)
name (varchar)
description (varchar)

table 2:
iduser (int)
idcategory (int)
name (varchar)
description (varchar)

if i make a join() between this two tables the fields name and description They will overwrite

when you make a raw query you solve this with something like this table1.name AS "new name" table1.description AS "new description name"

example code:

$db->join("categories ca","us.idCategory=ca.idCategory","LEFT");
$users = $db->get("users us");

**Comment by avbdr** [comment]
do the same with a lib :)
```php
$db->join("categories ca","us.idCategory=ca.idCategory","LEFT");
$users = $db->get("users us", null, "*, us.description as userDescription");
```

**Comment by Menusito** [comment]
@avbdr works perfect!
