### ISSUE TITLE
Is this query possible with the current OnDuplicate()?

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#344]
INSERT INTO pubs (ownerid, pubtype, revision)
    VALUES (?, ?, ?)
    ON DUPLICATE KEY UPDATE revision = revision + 1;

I'm not finding a way to accomplish this with the current OnDuplicate() implementation. Have I missed something?

**Comment by avbdr** [comment]
seems documentation needs to be updated.
$updateColumns could be an array like a regular data array. 

```php
$updateColumns = array ('revision' => $db->inc())
```

**Comment by scoman81** [comment]
I actually tried exactly that, and it didn't work - I got an error in the query text. I think the word "array" actually showed up in the SQL. When I looked at the code it seemed to me that what it is expecting is an array of column names only (which does seem to work) but not an array of column=>data values ... but admittedly, I didn't dig too deeply to confirm that for sure.

**Comment by avbdr** [comment]
can you please test the following patch:
```php
diff --git a/MysqliDb.php b/MysqliDb.php
index e0a3926..f435634 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -1094,7 +1094,14 @@ class MysqliDb
             if ($this->_lastInsertId)
                 $this->_query .= $this->_lastInsertId . "=LAST_INSERT_ID (".$this->_lastInsertId."), ";
 
-            $this->_buildDataPairs ($tableData, $this->_updateColumns, false);
+            foreach ($this->_updateColumns as $key => $val) {
+                if (is_numeric ($key)) {
+                    $this->_updateColumns[$val] = '';
+                    unset ($this->_updateColumns[$key]);
+                } else
+                    $tableData[$key] = $val;
+            }
+            $this->_buildDataPairs ($tableData, array_keys ($this->_updateColumns), false);
         }
     }
```

**Comment by avbdr** [comment]
i have pushed a fix to master
