### ISSUE TITLE
anyway I can get result in object

### ISSUE THREAD

**Issue by circuitmamu** [joshcam/PHP-MySQLi-Database-Class#351]
When I use this syntax
$users = $db->get('users'); //contains an Array of all users 

but I need result in totally object not an associative array or a objects inside array.

So this kind of function or help is available in this class or need to implement own function.

Because when we getting result in array and check it's length or necessary key for validation but if key is not exist it gives warning in phpcode so as per my suggestion return value in object using mysqli_fetch_object is better.

Because we can use for and while loop for the object but we can't use while loop for array properly everytime we have to check it's length and key is not empty before display.

**Comment by avbdr** [comment]
all you need is to read the doc. Search for ObjectBuilder(), JsonBuilder(), map().

$db->objectBuilder()->get('users');

**Comment by circuitmamu** [comment]
@avbdr 
Child is object but parent is still array. you can see it below link as you suggest code
http://prntscr.com/8ywha3

But I need everything in object no signle array so is it any possibilities in this class without using custom function. this result I want.
http://prntscr.com/8ywhxg

**Comment by avbdr** [comment]
i dont understand why its so important. that wont be implemented. 
I still cant understand why its so important. while and foreach works just perfert on arrays.
