### ISSUE TITLE
How can I use the paginate function?

### ISSUE THREAD

**Issue by jk-1001** [joshcam/PHP-MySQLi-Database-Class#352]
Thanks for this class, it's been very helpful in my development. I need to add some paging and I see in the dbObject.php that there is a paginate function but I am not entirely sure how to use it and I can't seem to find anything about it in the readme. Please, does somebody have an example of how to use the paginate function or how to add some pagination to this class? Thanks.

**Comment by avbdr** [comment]
good bugreport. I have added a placeholder function for the pagination but never managed to test it :)
I have commited fixed version and a readme update to master.
https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.md#pagination

**Comment by jk-1001** [comment]
Thanks for that but I still don't fully understand how to utilise this code. Is it possible for you to give a more in-depth example? For example, how do I use it with the $db->get function in order to show the results of that particular page? Also, how to create the page numbers at the bottom of the table? Thanks for your help.

**Comment by avbdr** [comment]
paginate() duplicates the get() behavoir. 
prototype is paginate($pageNum, $fieldsList)
where pagenum  is a page number and fieldslist is an optional parament for the list of fields to select.

library wont generate you a pager, you will need to do it by youself. after paginate() execution product::$totalPages will contain a total amount of pages.

**Comment by avbdr** [comment]
user::where('type','admin')->paginate(1) will return you the first page of 20 items. 
to conctrol rows amount per page use user::$pageLimit.

**Comment by jk-1001** [comment]
This is the code I'm using based on your readme. How can I paginate this?
$db->join("location", "article.location_id=location.id", "LEFT");
$db->join("service", "article.service_id=service.id", "LEFT");
$db->join("user", "article.user_id=user.id", "LEFT");
$db->orderBy("created_date", "desc");
$articles=$db->get("article", null, "article.*, location.name as location, service.name as service, user.name as user");

I really do appreciate the help.

**Comment by avbdr** [comment]
paginate is available for dbObject only :) Good catch, i need to move it to mysqlidb. give me couple days to do that.

**Comment by jk-1001** [comment]
Thanks! I look forward to it. :)

**Comment by jk-1001** [comment]
Have you managed to make any progress on this? Thanks.

**Comment by avbdr** [comment]
commited to master. thanks
