### ISSUE TITLE
HOW IS GOOD IF WE HAVE TO CHANGE MYSQLI TO PDO

### ISSUE THREAD

**Issue by dev10calypso** [joshcam/PHP-MySQLi-Database-Class#356]
HOW IS GOOD IF WE HAVE TO CHANGE MYSQLI TO PDO
FYI : Just concept.

**Comment by avbdr** [comment]
i were thinking about that, but not sure if we want to have this extra overhead as pdo is heavier then mysqli.
from another hand, im looking a lot and php 5.5+ 'yeld' feature and more and more thinking to create separate 5.5+ branch.

**Comment by emman-ok** [comment]
I would really love to see the support for PDO and native MySQL

**Comment by tommyknocker** [comment]
You may check my PDODb wrapper. It almost compactible with MySQLiDb. You may find it here - https://github.com/tommyknocker/PDO-database-class

**Comment by avbdr** [comment]
Tommy , would you mind to merge our codebases and participate in the mysqlidb development?

**Comment by tommyknocker** [comment]
Yep, I would. I'll think about what can I do.
