### ISSUE TITLE
get maked query before execute it

### ISSUE THREAD

**Issue by Menusito** [joshcam/PHP-MySQLi-Database-Class#362]
its possible to get the maked query before execute it?

**Comment by tommyknocker** [comment]
No, it's not, afaik. But you can get your last executed query by calling getLastQuery() method.

**Comment by avbdr** [comment]
its impossible as you cant build a query without a final get/update/insert(). And there is no 'dry run' in them.

**Comment by Menusito** [comment]
when i work with several joins sometimes i get malformed errors, but i don't know how to depurate the query, for this reason i want the query formed for the class before execute it.

**Comment by avbdr** [comment]
In the prepare error you should see where the problem is. As well, in exception you should be able to run getlastquery() just fine.
