### ISSUE TITLE
Subquery FROM

### ISSUE THREAD

**Issue by arieffikhrie** [joshcam/PHP-MySQLi-Database-Class#364]
Hi,

```` 
SELECT *
FROM (
	SELECT *
	FROM table
	ORDER BY _time DESC
) a
GROUP BY a._foreignID
ORDER BY a._time DESC
````

http://sqlfiddle.com/#!9/f44ecb/1

Is there any way to do that query without using rawQuery?

**Comment by avbdr** [comment]
i forgot about this one. Will add to a TODO for next release.

**Comment by arieffikhrie** [comment]
Ok cool.. Will waiting for that
