### ISSUE TITLE
Why use $db->update does not exist always return 1

### ISSUE THREAD

**Issue by mbdmt** [joshcam/PHP-MySQLi-Database-Class#365]
Why use $db->update does not exist always return 1

$db->where("aid", 2);//2 does not exist
$data = Array ("pass" => "111111","edit_date" => $db->now());
$rs=$db->update("staffdb", $data); // return 1

**Comment by avbdr** [comment]
update will return true even if no rows were affected. You need to check $db->count after update() to check how many rows were affected by an update

**Comment by mbdmt** [comment]
Thank you!
