### ISSUE TITLE
update() does not support limit

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#367]
It's currently not possible to execute this query without using rawQuery

    update table
    set processed=1
    where processed=0
    limit 2

Could update() get a limit param like get() has?

**Comment by avbdr** [comment]
please try the following patch and let me know. This will allow to use same limit array/variable as in get(). ex $db->update ('table', $data, array ($count, $offset))

```php
diff --git a/MysqliDb.php b/MysqliDb.php
index 00e01f8..22776c3 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -663,7 +663,7 @@ class MysqliDb
      *
      * @return bool
      */
-    public function update($tableName, $tableData)
+    public function update($tableName, $tableData, $limit = null)
     {
         if ($this->isSubQuery) {
             return;
@@ -671,7 +671,7 @@ class MysqliDb
 
         $this->_query = "UPDATE " . self::$prefix . $tableName;
 
-        $stmt = $this->_buildQuery(null, $tableData);
+        $stmt = $this->_buildQuery($limit, $tableData);
         $status = $stmt->execute();
         $this->reset();
         $this->_stmtError = $stmt->error;
```

**Comment by scoman81** [comment]
Thanks for the quick reply. To be perfectly honest, I'm the ultimate Git noob, and don't really know how to apply a git patch. I guess I could do it by hand but maybe someone else will jump in and try it the right way ... whatever that is!

**Comment by avbdr** [comment]
save this to the file to the directory with Mysqlidb.php
then run in linux shell: patch -p1 < file

On Wed, Nov 25, 2015 at 12:43 AM, scoman81 <notifications@github.com> wrote:

> Thanks for the quick reply. To be perfectly honest, I'm the ultimate Git
> noob, and don't really know how to apply a git patch. I guess I could do it
> by hand but maybe someone else will jump in and try it the right way ...
> whatever that is!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/367#issuecomment-159414064>
> .
>



-- 
Alex

**Comment by avbdr** [comment]
I have commited a patch to my private repo for you to test. Get a file from
https://github.com/avbdr/PHP-MySQLi-Database-Class/blob/master/MysqliDb.php.

On Wed, Nov 25, 2015 at 1:35 AM, Alexander Butenko <a.butenka@gmail.com>
wrote:

> save this to the file to the directory with Mysqlidb.php
> then run in linux shell: patch -p1 < file
>
> On Wed, Nov 25, 2015 at 12:43 AM, scoman81 <notifications@github.com>
> wrote:
>
>> Thanks for the quick reply. To be perfectly honest, I'm the ultimate Git
>> noob, and don't really know how to apply a git patch. I guess I could do it
>> by hand but maybe someone else will jump in and try it the right way ...
>> whatever that is!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/367#issuecomment-159414064>
>> .
>>
>
>
>
> --
> Alex
>



-- 
Alex

**Comment by scoman81** [comment]
Thanks - I'm on Windows, but the GitShell has a patch command that I was able to use.

I was unsure about the syntax, and tried $db->update('x', $data, array($pageSize,0)) but this fails - probably isn't correct syntax. However ... $db->update('x', $data, $pageSize); worked great!

Thanks again for all your work on this library!

**Comment by avbdr** [comment]
yes, update do not support offset. ill update readme. thanks for testing
