### ISSUE TITLE
Implement support for multiple db connections

### ISSUE THREAD

**Issue by warmwinter** [joshcam/PHP-MySQLi-Database-Class#370]
In the class, attribute "$prefix" is static. When build two different instances, the prefix been setted last instance. Others instances except the last , generate fatal error! Need fixed!

**Comment by avbdr** [comment]
the idea of the library is singleton. I think we just need to workout api with multiple databases.
For now, you can overwrite prefix in constructor when you initiating second connection.

**Comment by avbdr** [comment]
huh, i think there is a way to make it just protected. :) give me couple days, ill try to work it out.

**Comment by warmwinter** [comment]
I think we can't init a new db connection, if the library is singleton. The variable self::$_instance is enough.:)

**Comment by avbdr** [comment]
that is used only for a getInstance() function. So you still can create multiple instances if you wont be using getInstance()

**Comment by warmwinter** [comment]
Uh, the static variable point the same address space.In the same php process, the getInstance() function can return the last instance when create multiple instances.

**Comment by avbdr** [comment]
as I told, you still can create multiple mysqlidb object if you wont be using getInstance().
getInstance() is not used inside the library at all.

**Comment by avbdr** [comment]
closing as a dup of #373
