### ISSUE TITLE
how can get data with LIKE?

### ISSUE THREAD

**Issue by iZume** [joshcam/PHP-MySQLi-Database-Class#374]
hello, i need apply this instruction with this framework:

SELECT id,name FROM users WHERE name LIKE '%$q%' ORDER BY id LIMIT 5

**Comment by iZume** [comment]
I succeeded

    $users = $sql->rawQuery("SELECT id,name FROM users WHERE name LIKE '%$q%' ORDER BY id LIMIT 5");
    print_r($users);

**Comment by ricwein** [comment]
or you can use something like this:

```php
$sql->where('name', '%' . $q . '%', 'LIKE');
$sql->orderBy('id');
$user = $sql->get('users', 5, ['id', 'name']);
```

also see issue [#168](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/168)

**Comment by iZume** [comment]
thanks! it work :smile:
