### ISSUE TITLE
<= problem when using rawQuery 

### ISSUE THREAD

**Issue by LUFCMOT** [joshcam/PHP-MySQLi-Database-Class#376]
Hello,

I have a problem when using <= with rawQuery..

I get the following mysql error:
Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement

I cannot understand this because >= works absolutely fine !

Regards

**Comment by avbdr** [comment]
i think you are using very old version of mysqlidb. Please update to the latest release and try again.
