### ISSUE TITLE
Integers being converted to strings.

### ISSUE THREAD

**Issue by JonnyNineToes** [joshcam/PHP-MySQLi-Database-Class#377]
I seem to be having a problem, when I'm doing an UPDATE, I submit an array made up of both strings and integer values. After the query is run, I check the database, and I see that numeric fields are wrong (they're tinyint(3)). The numeric values I'm trying to submit are 0 (zeroes) and 1 (ones). I always  end up with a 1 in those fields. After I look at the query using getLastQuery(), I see that those numeric values are being inserted into the query as strings.

Is there any way around this, besides writing a raw query?

**Comment by avbdr** [comment]
can you submit a code sample with a sample data to reproduce the problem. its quite impossible to have such an issue. 
Just in case can you update to the latest master?

**Comment by avbdr** [comment]
call the print_r () on the array you are trying to pass to update() i think your issue is somewhere before an update() 

getLastQuery() do not return an exact sql which was executed.

**Comment by JonnyNineToes** [comment]
I can try updating from master...

In the meantime, here's an example of what I'm doing. Here is a var_dump of my array:
> array(12) {
>   ["product"]=>string(9) "client"
>   ["cfu_number"]=>string(11) "15192439898"
>   ["cfna_number"]=>string(0) ""
>   ["cfb_number"]=>string(11) "15192439899"
>   ["cfnr_number"]=>string(11) "15192439898"
>   ["cw_profile_status"]=>int(0)
>   ["sms_profile_status"]=>int(0)
>   ["clip_profile_status"]=>int(0)
>   ["cfu_profile_status"]=>int(1)
>   ["cfna_profile_status"]=>int(0)
>   ["cfb_profile_status"]=>int(1)
>   ["cfnr_profile_status"]=>int(1)
> }

Which is output, right before I use it with `->update()`.

Here's how I use the query...

    if ( $db->update('subscriber', $update) )  {...

Here is the query that is output right after I run the query....

> UPDATE aspenta_subscriber 
> SET `product` = 'client', `cfu_number` = '15192439898', `cfna_number` = '', `cfb_number` = '15192439899', `cfnr_number` = '15192439898', `cw_profile_status` = '0', `sms_profile_status` = '0', `clip_profile_status` = '0', `cfu_profile_status` = '1', `cfna_profile_status` = '0', `cfb_profile_status` = '1', `cfnr_profile_status` = '1' 
> WHERE imsi = '302340000000303' 
> AND msisdn = '15196027015'

Notice that fields, such as "cw_profile_status" are being wrapped in single quotes; denoting that they  have been inserted as strings.

**Comment by JonnyNineToes** [comment]
Wait... you said that "getLastQuery" doesn't return the exact SQL query that was used...?

**Comment by avbdr** [comment]
that should work fine. what values you are getting in *_status fields in the database? 
mysqlidb uses prepared statements to submit query for executing. getLastQuery() fakes the sql output and can be used only for debugging purposes. Im quite sure all ints were submitted as ints.

**Comment by JonnyNineToes** [comment]
I see... I'm still currently trying to get a legitimate "last query" from my database to see what really was submitted. I may have to continue this on Monday.

As for what value is in those fields, either they're blank, 0 (zero), or they're 1. As per DESCRIBE, that field is an unsigned tinyint(3).

**Comment by JonnyNineToes** [comment]
Okay. I have to apologize for pulling the fire alarm on you, but thank  you for trying to help. The issue ended up being a user issue... was something wrong with the way they were inputting the data into the form. I'll close this and leave it be. Thanks again.
