### ISSUE TITLE
Select with foreign key value

### ISSUE THREAD

**Issue by ugurozturk** [joshcam/PHP-MySQLi-Database-Class#378]
Hi. I have two table like projects and project_type.

I am using like
* $projects = $db->get('products'); // and it works good but the result returns
- Project name | project_type_id

I want to get like 
+ Project name | Project_type_name

is there has any way to do get both values foreign key and the row ? I do better if i can all in one line you know.

Edit : I think i would use "Running raw SQL queries" method to do that. If there any other way, someone can comment here. I would like to know

**Comment by avbdr** [comment]
```
$db->join('project_type pt','p.project_type = pt.id')
      ->get("projects p",null, "$needed fields")
```
