### ISSUE TITLE
two tables have the same column name only returns one column

### ISSUE THREAD

**Issue by troy351** [joshcam/PHP-MySQLi-Database-Class#379]
I have two tables like t1 and t2 which both have column id and name.
I'm using like
      $db->join('t2','t2.id = t1.id','inner')->get("t1",null, Array ("t1.name", "t2.name"));
but only return the name of t1.
How could I solve this?

**Comment by avbdr** [comment]
$db->join('t2','t2.id = t1.id','inner')->get("t1",null, Array ("t1.name as t1_name", "t2.name as t2_name"));
