### ISSUE TITLE
Parse error: syntax error, unexpected T_FUNCTION in D:\www\webroot\phpclass\MysqliDb.php on line 1835

### ISSUE THREAD

**Issue by rahul-spartan** [joshcam/PHP-MySQLi-Database-Class#381]
<b>Parse error:</b> syntax error, unexpected T_FUNCTION in D:\www\webroot\phpclass\MysqliDb.php on line 1835

**Comment by avbdr** [comment]
Looks like you are using modified version of the library. Please update
from trunk

**Comment by rahul-spartan** [comment]
update from trunk, where?

**Comment by avbdr** [comment]
here on github. update to latest master version

**Comment by rahul-spartan** [comment]
ya im testing it out now. please wait

**Comment by rahul-spartan** [comment]
hmm that was a version issue which i had. it seems that anonymous function are available from and after php version 5.3. :) .Got some reference http://stackoverflow.com/questions/3197853/php-anonymous-function-with-array-walk

**Comment by avbdr** [comment]
oh, i see. Im not sure if library will be working fine on php 5.3. If you want to make sure, you can try to run tests/*php to see if they will pass.
As for array_walk, you can comment it out if you do not plan to use prefixes

**Comment by rahul-spartan** [comment]
Ya. Done Something like this, gets the answer

function myfunction($value, $key){
		
			$value = MysqliDb::$prefix.$value;
		}
		
		array_walk($tables, "myfunction");
