### ISSUE TITLE
dbObject delete with where not working

### ISSUE THREAD

**Issue by VipSaran** [joshcam/PHP-MySQLi-Database-Class#387]
Model:
```
class CustomerProjectModel extends dbObject {

  protected $dbTable = "customer_project";

  protected $dbFields = Array (
    'customer_id' => Array ('int', 'required'),
    'project_id' => Array ('int', 'required')
    );
}
```

Call:
```
$customerProject = CustomerProjectModel::
  where('project_id', $project_id)->
  where('customer_id', $customer_id)->
  getOne();
// a proper dbObject is shown here with correct data array (of one) and with no errors (see below)
$id = $customerProject->delete();
```
`$id` is empty and `$db->getLastError()` returns "mysqli is null".

This is the `$customerProject` object (prior to `delete()`):
```
customerProject=CustomerProjectModel Object
(
    [dbTable:protected] => customer_project
    [dbFields:protected] => Array
        (
            [customer_id] => Array
                (
                    [0] => int
                    [1] => required
                )

            [project_id] => Array
                (
                    [0] => int
                    [1] => required
                )

        )

    [db:dbObject:private] => MysqliDb Object
        (
            [_mysqli:protected] => mysqli Object
                (
                    [affected_rows] => -1
                    [client_info] => mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
                    [client_version] => 50011
                    [connect_errno] => 0
                    [connect_error] => 
                    [errno] => 0
                    [error] => 
                    [error_list] => Array
                        (
                        )

                    [field_count] => 2
                    [host_info] => localhost via TCP/IP
                    [info] => 
                    [insert_id] => 0
                    [server_info] => 5.5.5-10.1.8-MariaDB
                    [server_version] => 50505
                    [stat] => Uptime: 186221  Threads: 3  Questions: 6534  Slow queries: 0  Opens: 8  Flush tables: 1  Open tables: 19  Queries per second avg: 0.035
                    [sqlstate] => 00000
                    [protocol_version] => 10
                    [thread_id] => 304
                    [warning_count] => 0
                )

            [_query:protected] => 
            [_lastQuery:protected] => SELECT  * FROM customer_project WHERE  project_id = '15'  AND customer_id = '1'  LIMIT 1
            [_queryOptions:protected] => Array
                (
                )

            [_join:protected] => Array
                (
                )

            [_where:protected] => Array
                (
                )

            [_having:protected] => Array
                (
                )

            [_orderBy:protected] => Array
                (
                )

            [_groupBy:protected] => Array
                (
                )

            [_bindParams:protected] => Array
                (
                    [0] => 
                )

            [count] => 1
            [totalCount] => 0
            [_stmtError:protected] => 
            [host:protected] => localhost
            [username:protected] => x
            [password:protected] => y
            [db:protected] => z
            [port:protected] => 
            [charset:protected] => utf8
            [isSubQuery:protected] => 
            [_lastInsertId:protected] => 
            [_updateColumns:protected] => 
            [returnType] => array
            [_nestJoin:protected] => 
            [_tableName:MysqliDb:private] => 
            [_forUpdate:protected] => 
            [_lockInShareMode:protected] => 
            [_mapKey:protected] => 
            [traceStartQ:protected] => 
            [traceEnabled:protected] => 
            [traceStripPrefix:protected] => 
            [trace] => Array
                (
                )

            [pageLimit] => 20
            [totalPages] => 0
        )

    [data] => Array
        (
            [customer_id] => 1
            [project_id] => 15
        )

    [isNew] => 
    [returnType] => Object
    [_with:dbObject:private] => Array
        (
        )

    [errors] => 
    [primaryKey:protected] => id
)
```
(possibly something to do with "id" being always set as implicity PK?)

Yet, when I execute this:
```
$this->db->where('project_id', $project_id)->where('customer_id', $customer_id);
$id = $this->db->delete('customer_project');
```
it works as expected!

**Comment by avbdr** [comment]
it seems that you need to define a primary key in your object. if your
table doesnt have one, you need to create it.

by default primary key name is set to 'id', but you can redefine it
with $primaryKey obj variable.


On Mon, Dec 21, 2015 at 5:49 PM, Robert Šarić <notifications@github.com>
wrote:

> Model:
>
> class CustomerProjectModel extends dbObject {
>
>   protected $dbTable = "customer_project";
>
>   protected $dbFields = Array (
>     'customer_id' => Array ('int', 'required'),
>     'project_id' => Array ('int', 'required')
>     );
> }
>
> Call:
>
> $customerProject = CustomerProjectModel::
>   where('project_id', $project_id)->
>   where('customer_id', $customer_id)->
>   getOne();
> // a proper dbObject is shown here with correct data array (of one) and with no errors (see below)
> $id = $customerProject->delete();
>
> $id is empty and $db->getLastError() returns "mysqli is null"
>
> This is the $customerProject object:
>
> customerProject=CustomerProjectModel Object
> (
>     [dbTable:protected] => customer_project
>     [dbFields:protected] => Array
>         (
>             [customer_id] => Array
>                 (
>                     [0] => int
>                     [1] => required
>                 )
>
>             [project_id] => Array
>                 (
>                     [0] => int
>                     [1] => required
>                 )
>
>         )
>
>     [db:dbObject:private] => MysqliDb Object
>         (
>             [_mysqli:protected] => mysqli Object
>                 (
>                     [affected_rows] => -1
>                     [client_info] => mysqlnd 5011-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
>                     [client_version] => 50011
>                     [connect_errno] => 0
>                     [connect_error] =>
>                     [errno] => 0
>                     [error] =>
>                     [error_list] => Array
>                         (
>                         )
>
>                     [field_count] => 2
>                     [host_info] => localhost via TCP/IP
>                     [info] =>
>                     [insert_id] => 0
>                     [server_info] => 555-1018-MariaDB
>                     [server_version] => 50505
>                     [stat] => Uptime: 186221  Threads: 3  Questions: 6534  Slow queries: 0  Opens: 8  Flush tables: 1  Open tables: 19  Queries per second avg: 0035
>                     [sqlstate] => 00000
>                     [protocol_version] => 10
>                     [thread_id] => 304
>                     [warning_count] => 0
>                 )
>
>             [_query:protected] =>
>             [_lastQuery:protected] => SELECT  * FROM customer_project WHERE  project_id = '15'  AND customer_id = '1'  LIMIT 1
>             [_queryOptions:protected] => Array
>                 (
>                 )
>
>             [_join:protected] => Array
>                 (
>                 )
>
>             [_where:protected] => Array
>                 (
>                 )
>
>             [_having:protected] => Array
>                 (
>                 )
>
>             [_orderBy:protected] => Array
>                 (
>                 )
>
>             [_groupBy:protected] => Array
>                 (
>                 )
>
>             [_bindParams:protected] => Array
>                 (
>                     [0] =>
>                 )
>
>             [count] => 1
>             [totalCount] => 0
>             [_stmtError:protected] =>
>             [host:protected] => localhost
>             [username:protected] => x
>             [password:protected] => y
>             [db:protected] => z
>             [port:protected] =>
>             [charset:protected] => utf8
>             [isSubQuery:protected] =>
>             [_lastInsertId:protected] =>
>             [_updateColumns:protected] =>
>             [returnType] => array
>             [_nestJoin:protected] =>
>             [_tableName:MysqliDb:private] =>
>             [_forUpdate:protected] =>
>             [_lockInShareMode:protected] =>
>             [_mapKey:protected] =>
>             [traceStartQ:protected] =>
>             [traceEnabled:protected] =>
>             [traceStripPrefix:protected] =>
>             [trace] => Array
>                 (
>                 )
>
>             [pageLimit] => 20
>             [totalPages] => 0
>         )
>
>     [data] => Array
>         (
>             [customer_id] => 1
>             [project_id] => 15
>         )
>
>     [isNew] =>
>     [returnType] => Object
>     [_with:dbObject:private] => Array
>         (
>         )
>
>     [errors] =>
>     [primaryKey:protected] => id
> )
>
> (possibly something to do with "id" being always set as implicity PK?)
>
> Yet, when I execute this:
>
> $this->db->where('project_id', $project_id)->where('customer_id', $customer_id);
> $id = $this->db->delete('customer_project');
>
> it works as expected!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/387>.
>



-- 
Alex

**Comment by VipSaran** [comment]
This is my table:

![image](https://cloud.githubusercontent.com/assets/995948/11934713/23ab4102-a804-11e5-91e4-afc0f0c1efac.png)

Created with:
```
CREATE TABLE IF NOT EXISTS `customer_project` (
  `customer_id` INT(12) NOT NULL,
  `project_id` INT(12) NOT NULL,
  PRIMARY KEY (`customer_id`, `project_id`),
  INDEX `customer_project_ibfk_2_idx` (`project_id` ASC),
  CONSTRAINT `customer_project_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `customer_project_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `project` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;
```

I've added the `$primaryKey` to model:
```
class CustomerProjectModel extends dbObject {

  protected $dbTable = "customer_project";

  protected $primaryKey = "PRIMARY";

  protected $dbFields = Array (
    'customer_id' => Array ('int', 'required'),
    'project_id' => Array ('int', 'required')
    );
}
```
but, without effect.

This is the dbObject (before delete):
```
customerProject=CustomerProjectModel Object
(
    [dbTable:protected] => customer_project
    [primaryKey:protected] => PRIMARY
    [dbFields:protected] => Array
        (
            [customer_id] => Array
                (
                    [0] => int
                    [1] => required
                )

            [project_id] => Array
                (
                    [0] => int
                    [1] => required
                )

        )

    [db:dbObject:private] => MysqliDb Object
        (
            [_mysqli:protected] => mysqli Object
                (
                    [affected_rows] => -1
                    [client_info] => mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
                    [client_version] => 50011
                    [connect_errno] => 0
                    [connect_error] => 
                    [errno] => 0
                    [error] => 
                    [error_list] => Array
                        (
                        )

                    [field_count] => 2
                    [host_info] => localhost via TCP/IP
                    [info] => 
                    [insert_id] => 0
                    [server_info] => 5.5.5-10.1.8-MariaDB
                    [server_version] => 50505
                    [stat] => Uptime: 190372  Threads: 3  Questions: 7277  Slow queries: 0  Opens: 8  Flush tables: 1  Open tables: 19  Queries per second avg: 0.038
                    [sqlstate] => 00000
                    [protocol_version] => 10
                    [thread_id] => 338
                    [warning_count] => 0
                )

            [_query:protected] => 
            [_lastQuery:protected] => SELECT  * FROM customer_project WHERE  project_id = '15'  AND customer_id = '1'  LIMIT 1
            [_queryOptions:protected] => Array
                (
                )

            [_join:protected] => Array
                (
                )

            [_where:protected] => Array
                (
                )

            [_having:protected] => Array
                (
                )

            [_orderBy:protected] => Array
                (
                )

            [_groupBy:protected] => Array
                (
                )

            [_bindParams:protected] => Array
                (
                    [0] => 
                )

            [count] => 1
            [totalCount] => 0
            [_stmtError:protected] => 
            [host:protected] => localhost
            [username:protected] => x
            [password:protected] => y
            [db:protected] => z
            [port:protected] => 
            [charset:protected] => utf8
            [isSubQuery:protected] => 
            [_lastInsertId:protected] => 
            [_updateColumns:protected] => 
            [returnType] => array
            [_nestJoin:protected] => 
            [_tableName:MysqliDb:private] => 
            [_forUpdate:protected] => 
            [_lockInShareMode:protected] => 
            [_mapKey:protected] => 
            [traceStartQ:protected] => 
            [traceEnabled:protected] => 
            [traceStripPrefix:protected] => 
            [trace] => Array
                (
                )

            [pageLimit] => 20
            [totalPages] => 0
        )

    [data] => Array
        (
            [customer_id] => 1
            [project_id] => 15
        )

    [isNew] => 
    [returnType] => Object
    [_with:dbObject:private] => Array
        (
        )

    [errors] => 
)
```

**Comment by avbdr** [comment]
```
alter table customer_project add customer_project_id INT(9) UNSIGNED PRIMARY KEY AUTO_INCREMENT
```
and your primary key will be customer_project_id

**Comment by VipSaran** [comment]
How come this works correctly:
```
$this->db->where('project_id', $project_id)->where('customer_id', $customer_id);
$id = $this->db->delete('customer_project');
```

Sorry, but what you suggest seems (to me) to be just a workaround for dbObject currently not supporting definition of PK to be a combination of several columns.

**Comment by avbdr** [comment]
from what i know there is no such thing as a 'several columns as PK' but yes, library do not support that. More then that its a bad practice to have tables without an unique id field. 

In your case what you need to do is to overwrite delete() method in your CustomerProjectModel and call mysqli->delete with a custom where() conditions.

**Comment by VipSaran** [comment]
Close the issue? This is definitely a shortcoming and dbObject implementation assuming each table should have 1 column defined as PK is absurd.

I'm a SQL novice, but at least I know that having the dummy ID column defined PK is not mandatory and least of all "a good practice".

A quick internet search seems to backs this up:
http://stackoverflow.com/questions/1207983/in-general-should-every-table-in-a-database-have-an-identity-field-to-use-as-a

So, please, recognize that the library is missing support for composite PKs and then fix this shortcoming.
