### ISSUE TITLE
Problem when I update the class (currently 2.4) to 2.6,2.5 or the 2.4 version hosted here

### ISSUE THREAD

**Issue by weha** [joshcam/PHP-MySQLi-Database-Class#388]
When I update to the new version I get an error: Problem preparing query 
Not everywhere so it is a specific problem.
The query that it spat out works fine in phpmyadmin and it works with a previous version of the class.

## Does not work:
`// count the pages`
`$count = $dbi->copy();`
`$count = $count->getValue('companies',"COUNT(companies.id)");`
`$count = ceil($count / $itemsperpage);`
Lastquery: SELECT COUNT(companies.id) AS retval FROM companies LIMIT 1
`// active`
`$temp = $dbi->copy();`
`$temp->where('companies.active',1);`
`$active = $temp->getValue("companies","count(companies.id)");`
Error: 'Problem preparing query (SELECT  count(companies.id) AS retval FROM companies WHERE  companies.active = ?  LIMIT 1) 
## Does not work either:
`// count the pages`
`$count = $dbi->copy();`
`$count = $dbi->getValue('companies',"COUNT(companies.id)");`
`$count = ceil($count / $itemsperpage);`
`// active`
`//$temp = $dbi->copy();`
`$dbi->where('companies.active',1);`
`$active = $dbi->getValue("companies","count(companies.id)");`

Error: 'Problem preparing query (SELECT  count(companies.id) AS retval FROM companies WHERE  companies.active = ?  LIMIT 1) ' 
## works
`// count the pages`
`//$count = $dbi->copy();`
`$count = $dbi->getValue('companies',"COUNT(companies.id)");`
`$count = ceil($count / $itemsperpage);`
Lastquery:  SELECT COUNT(companies.id) AS retval FROM companies LIMIT 1
`// active`
`$temp = $dbi->copy();`
`$temp->where('companies.active',1);`
`$active = $temp->getValue("companies","count(companies.id)");`
Lastquery: SELECT count(companies.id) AS retval FROM companies WHERE companies.active = '1' LIMIT 1

## Also works
`// count the pages`
`//$count = $dbi->copy();`
`//$count = $count->getValue('companies',"COUNT(companies.id)");`
`//$count = ceil($count / $itemsperpage);`
`// active`
`$temp = $dbi->copy();`
`$temp->where('companies.active',1);`
`$active = $temp->getValue("companies","count(companies.id)");`

For testing: Above this code, no where or anything as been set, there have been other queries though.

**Comment by avbdr** [comment]
thats very strange. can you please make a simple testcase for me to reproduce the problem? 
i have pretty much the same testcase in tests/mysqliDbTests.php and its passsing just fine.

**Comment by weha** [comment]
ok so I stripped down my php.
What I think it might be is when copy() is used and some variables are not cleared in the class internally from the previously executed query.

I've attached a zip with 3 scripts where 1 fails and 2 don't.
For it to fail you require a normal query and 2 queries which use copy()
If one is commented out, you get a close error at the end of the script (after echo done):
 Warning: mysqli::close(): Couldn't fetch mysqli in MysqliDb.php on line 1497

I did leave a part out in my last post which I forgot, it says more than just problem preparing query:

Warning: mysqli::prepare(): Couldn't fetch mysqli in MysqliDb.php on line 1472

Warning: MysqliDb::_prepareQuery(): Couldn't fetch mysqli in MysqliDb.php on line 1473

Fatal error: Uncaught exception 'Exception' with message 'Problem preparing query (SELECT COUNT(members.id) AS retval FROM members LIMIT 1) ' in MysqliDb.php:1475 Stack trace: #0 MysqliDb.php(1090): MysqliDb->_prepareQuery() #1 MysqliDb.php(550): MysqliDb->_buildQuery(1) #2 MysqliDb.php(598): MysqliDb->get('members', 1, 'COUNT(members.i...') #3 test.php(16): MysqliDb->getValue('members', 'COUNT(members.i...') #4 {main} thrown in MysqliDb.php on line 1475


I hope this helps, for the script you just need an empty table so you can change it to whatever test database you have or create a table called members with the column id.
[php.zip](https://github.com/joshcam/PHP-MySQLi-Database-Class/files/72428/php.zip)

**Comment by avbdr** [comment]
you are right. I can reproduce this one. Can you please try the following patch?

```
diff --git a/MysqliDb.php b/MysqliDb.php
index f64c00a..2b2d660 100644
--- a/MysqliDb.php
+++ b/MysqliDb.php
@@ -1731,7 +1731,7 @@ class MysqliDb
     public function copy()
     {
         $copy = unserialize(serialize($this));
-        $copy->_mysqli = $this->_mysqli;
+        $copy->_mysqli = null;
         return $copy;
     }
 ```

**Comment by weha** [comment]
That works, thanks!

**Comment by avbdr** [comment]
fixed in master. thank you.
