### ISSUE TITLE
dbObject.php - Join choose On ...column 

### ISSUE THREAD

**Issue by KTP95** [joshcam/PHP-MySQLi-Database-Class#390]
There are a bug:

Is impossible make Join To ad Not-primary Key.
example structure:
Object Files adn Disks have primary Key ID.
Every "Files" hasMany Disks, Every Disk Has Many Files.

Relationish Files-Disk" is declared in "FilesDisk" table, WITHOUT A PRIMARY KEY, but with colum "fileid" and "diskid" in relationiship "UNIQUE"

----------
So, Files can't join Disks....and Disks can't join Files because "FilesDisk" not have primary key.... so, for solve this, i propose add parameter $primaryKey to join() method.

I have Solving,Commit  https://github.com/KTP95/PHP-MySQLi-Database-Class/commit/148302e9f6f6861179e60549b5af9dd11526f4de

**Comment by avbdr** [comment]
thank you for a bugreport. can you please fix style issue and file a pull request?

**Comment by KTP95** [comment]
https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/392
Done
