### ISSUE TITLE
Inserting empty dbObject with default values and Index autoincrement - error

### ISSUE THREAD

**Issue by KTP95** [joshcam/PHP-MySQLi-Database-Class#391]
$MyObject= new MyObject;
$MyObject->save();

but if call
$MyObject= new MyObject;
$MyObject->var;
$MyObject->save();
is ok...strange,

I Try debug this, when i call save() method, the var $this->isNew is FALSE

**Comment by avbdr** [comment]
do you have __construct() in your myobject? 
as well, after save() isNew will be set to false.

**Comment by KTP95** [comment]
no...not have contructor

<?php

class MyObject extends dbObject {

    protected $dbTable = 'table';
	protected $primaryKey = 'ID';
	protected $dbFields = array(
    'ID' 				=> array('int'),
  .....
......
	);
	protected $relations = array(
		......
	);

}

**Comment by avbdr** [comment]
and $myObject->errors is empty?

**Comment by avbdr** [comment]
also check if you have error_reporting set to E_ALL to see if you are getting any errors.

**Comment by KTP95** [comment]
I Don't need check $object->error because it produce a fatal error:

    $nfile = new file;
    $nid = $nfile->save();

print:

    <br />
    <b>Fatal error</b>:  Uncaught exception 'mysqli_sql_exception' with message 'Column count     doesn't match value count at row 1' in ...MysqliDb.php:1472
    Stack trace:
    #0 ...MysqliDb.php(1472): mysqli-&gt;prepare('INSERT  INTO vs...')
    #1 ...MysqliDb.php(1090): MysqliDb-&gt;_prepareQuery()
    #2 ...MysqliDb.php(1037): MysqliDb-&gt;_buildQuery(NULL, Array)
    #3 ...MysqliDb.php(628): MysqliDb-&gt;_buildInsert('files', Array, 'INSERT')
    #4 ...dbObject.php(236): MysqliDb-&gt;insert('files', Array)
    #5 ...dbObject.php(278): dbObject-&gt;insert()
    #6 ...run-from-this-file.php(21): dbObject-&gt;save()
    #7 {main}
    thrown in <b>...MysqliDb.php</b> on line <b>1472</b><br />

**Comment by KTP95** [comment]
Anyway, i really don't want insert blank object in database, but only I show This bug and want report It

**Comment by avbdr** [comment]
yes, i were able to reproduce an error. Will come up with a fix shortly

**Comment by avbdr** [comment]
ok, pushed a fix to master. thank you
