### ISSUE TITLE
best way for check if dbObject has result.

### ISSUE THREAD

**Issue by KTP95** [joshcam/PHP-MySQLi-Database-Class#394]
Dear,
For example

    //when user not exist...
    $user = user::ById(999); 

    // Always is 0,
    echo (int) empty($user); 
    // Only checking a prop work
    echo (int) empty($user->ID);  // can be 1 or 0

but I DisLike checking every time a prop...is bad,

Maybe is possible implement a method ?
example:
   echo (int) $user->isEmpty(); or isIsset(), or...maybe bettercorrest $user->hasResult()...

thanks,

**Comment by avbdr** [comment]
get and byId always will return null if nothing were found. 

```
if ($user)
     // exists
else
   // not exist
```

**Comment by KTP95** [comment]
uhm, year...alright,

But...on object joined with method "Join" don't WITH() , not work...

example
    $file = file::with('realFile')->ById($fileId);
    print_r((int)(bool)$file->realFile);

also when $file->realFile not exists print 1,
relation File -> fileReal is HasOne type,

.... you can fix this maybe by checking if PrimaryKey is set in $fileReal object and if no, set it to null

**Comment by KTP95** [comment]
So, from what I understand you intention was return null object if not exists...
so, i Write this fix.

https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/395

**Comment by avbdr** [comment]
nice. have you tried to run test/dbObjectTests.php?

**Comment by avbdr** [comment]
you understood everything correctly. Sounds like you hit a bug here.

**Comment by avbdr** [comment]
merged with a typo fix :)
