### ISSUE TITLE
Is it usefull for Prevent Sql injection?

### ISSUE THREAD

**Issue by ttyazilim** [joshcam/PHP-MySQLi-Database-Class#400]
How about prevent sql injection?

Can we use this database  for prevent sql injection, is it based on this topic above.

http://stackoverflow.com/a/60496/3380449

**Comment by tommyknocker** [comment]
Short answer: yes :)
Long answer: This class is based on mysqli::prepare() and mysqli_stmt::bind_param methods.

**Comment by ttyazilim** [comment]
When i add single quotes ' to the input value and  POST it,  it adds backslash  /' to the database value.. 
How can i deny to adding backslashes to post value while i am using single quotes ?

**Comment by avbdr** [comment]
I think its a php magic quotes. You can disable that in php.ini

**Comment by ttyazilim** [comment]
Please can you help?

https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/451

2016-01-09 9:30 GMT+02:00 Alexander Butenko <notifications@github.com>:

> Closed #400
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/400>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/400#event-510129540>
> .
>



-- 

___________________________________________
Saygılarımla
Taner MACİT
Ttyazilim.com | sehirrehberiscripti.com
