### ISSUE TITLE
how can insert in db with null value 

### ISSUE THREAD

**Issue by hosamalzagh** [joshcam/PHP-MySQLi-Database-Class#403]
how can insert in db with null value 

$this->db->insert('singers', $data)

$data = Array(
    'name' => $name,
	'nationality' => $nationality,
	'photo_id' => null  ,              ------------------------------------  null or  ""
	'birthdate' => $birthdate
);

**Comment by avbdr** [comment]
null should work

**Comment by hosamalzagh** [comment]
i see Field 'photo_id' doesn't have a default value

**Comment by hosamalzagh** [comment]
if set to null value  i see     Column 'photo_id' cannot be null

**Comment by hosamalzagh** [comment]
sir i applied this 
http://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values  

"Open phpmyadmin and goto 'More' Tab and select 'Variables' submenu. Scroll down to find sql mode. Edit sql mode and remove 'STRICT_TRANS_TABLES' Save it."


and now work thank you sir
