### ISSUE TITLE
how can pass array to  escape()

### ISSUE THREAD

**Issue by hosamalzagh** [joshcam/PHP-MySQLi-Database-Class#404]
$a  = array([name] => www
    [nationality_id] => 1
    [birthdate] => 402278400
    [status] => 1)

i want pass escape($a)

**Comment by tommyknocker** [comment]
```php
// $db = new MysqliDb above

foreach($a as &$value) {
    $db->escape($value);
}
```

**Comment by hosamalzagh** [comment]
i edit  function escape 

from
  public function escape($str)
    {
        return $this->mysqli()->real_escape_string($str);
    }

to

    public function escape($str){
        if(is_array($str))
        {
           // return array_map(array(self,'escape'),$str);
            return array_map(__METHOD__, $str);
        }else
        {
            return $this->mysqli()->real_escape_string(trim(strip_tags($str)));
        }
    }
