### ISSUE TITLE
_bind_params -> query

### ISSUE THREAD

**Issue by KpuTuK** [joshcam/PHP-MySQLi-Database-Class#406]
Предлагаю заменить подготавливаемые выражения на

``` php
vsprintf($sql, array_filter($params, function ($param){
                return $this->_mysqli->real_escape_string($param);
            }));
```

например

``` php
public function query($sql, array $params = []) {
        if ($params) {
            $sql = vsprintf($sql, array_filter($params, function ($param){
                return $this->_mysqli->real_escape_string($param);
            }));
        }
        return $this->_mysqli>query($sql);
    }
```

p.s.

> Каждый подготавливаемый запрос использует ресурсы сервера. Если запрос больше не нужен, его необходимо сразу закрыть. Если не сделать этого явно, запрос закроется сам, но только когда PHP освободит его дескриптор, как правило это происходит при выходе запроса из области видимости или при завершении работы скрипта.
> 
> Использование подготавливаемых запросов не всегда приводит к повышению эффективности. Если параметризованный запрос запускается лишь раз, это приводит к большему количеству клиент-серверных обменов данными, нежели при выполнении простого запроса. Именно по этой причине в примере выше выражение SELECT выполнялось, как обычный запрос.
> 
> Также, имеет смысл рассмотреть SQL синтаксис вставки множества значений в выражении INSERT. В примере выше мультивставка (значения для вставки перечисляются через запятую) в предложении INSERT обошлась бы дешевле, чем подготовленный запрос.

http://php.net/manual/ru/mysqli.quickstart.prepared-statements.php Пример №3

**Comment by avbdr** [comment]
это уже давно извесно. Проблема в том, что подготавливаемые выражения сами по себе отлично предотвращают sqli иньекции, когда в вашем варианте будет нужно заботится об этом самому.

**Comment by KpuTuK** [comment]
посмотрите повнимательней код 
```php
array_filter($params, function ($param){
                return $this->_mysqli->real_escape_string($param);
            }
```
с этой целью и написал что не нужно заботиться об экраннировании и танцев с перебором массивов

будет что то типо
```php
$db->query('select * from users where id = %s', [1])->fetch_array(); 
```
`vsprintf` подставит значения а `array_filter` обойдет каждое `real_escape_string`

**Comment by avbdr** [comment]
real_escape_string не избавляет от sql injection на 100% без предварительной валидации ввода данных, увы.

**Comment by KpuTuK** [comment]
также как и bind_param ибо bind_param аналогична моему методу за исключением того что идет еще привязка к типам
