### ISSUE TITLE
How to use RAND?

### ISSUE THREAD

**Issue by Xusanbek** [joshcam/PHP-MySQLi-Database-Class#407]
Hello.
Tell me, please, how you can use ORDER by RAND()?
Now I using 
$db->orderBy("RAND", "ASC");
But an error, please, help me. Thanks!

**Comment by avbdr** [comment]
```
 $db->orderBy("RAND()", "ASC");
```

**Comment by Xusanbek** [comment]
Как быстро ответили. :)
Скажите, пожалуйста, а значение ASC обязательно или можно только RAND()?

**Comment by avbdr** [comment]
хороший вопрос. по-умолчанию будет DESC. для RAND() хорошо было бы добавить без ничего.

**Comment by Xusanbek** [comment]
Как я понял, это Вы создатель данного класса MySQLi?
Просто я впервые пользуюсь Github'ом и этим классом.
В моем скрипте оказывается имеется MysqliDb.class.php, вот и оттуда попал сюда.
Была версия 2.4, отсюда взял и поставил самую последнюю версию. Будет ли работать все полноценно как и раньше на новых версиях? То есть изменять ничего не надо? 
P.S.: Спасибо Вам за помощь с Rand().

**Comment by avbdr** [comment]
я продолжаю разработку. Новая версия должна работать так же, как и старая.

**Comment by Xusanbek** [comment]
Ясно.
Еще один вопрос, есть ли для этого класса, нормальный класс постраничной навигации?
А то свой как-то странно работает. И если несложно, объясните, пожалуйста, как его установить.

**Comment by avbdr** [comment]
есть функция paginate() для постраничного выбора данных. а в гуи пейджер нужно будет самому рисовать

**Comment by Xusanbek** [comment]
"а в гуи пейджер нужно будет самому рисовать"

Не могли бы более детальней уточнить все это?

**Comment by tommyknocker** [comment]
Имеется ввиду реализация пагинации во фронтенде. Класс предоставляет все данные. А то, как она будет выглядеть на фронтенде нужно реализовывать. Например, так - http://esimakin.github.io/twbs-pagination/
