### ISSUE TITLE
SQL Injection, question.

### ISSUE THREAD

**Issue by iZume** [joshcam/PHP-MySQLi-Database-Class#408]
hello, i have a one question, that class is protected of SQL Injection? i did many test, and not know if i am wrong

i test that >

id=-4' or 1=1#

and the query not get results of row affected, 

in that case the character # was ignored.

http://prntscr.com/9mhdeq

and if i delete # and add ' before of 1' ('1') is same (or '1' = '1')

**Comment by avbdr** [comment]
with prepared statements such injections wont work.
