### ISSUE TITLE
Using this class within my own OOP class

### ISSUE THREAD

**Issue by jk-1001** [joshcam/PHP-MySQLi-Database-Class#409]
Hi,

Really like this class. I am trying to create my own class and call the mysqli-class externally in order to insert my data but I am receiveing this error:

 Call to a member function insert() on a non-object in on line 37

The relevant line is $this->id=$db->insert("property", $data);

This is the full class:

<?
	//database connection
	require_once("../../config/db.php");
	
	class Property
	{
		public $id;
		public $account_id;
		public $town_id;
		public $type_id;
		public $created_date;
		public $modified_date;
		public $reference;
		public $price;
		public $bedrooms;
		public $bathrooms;
		public $build;
		public $plot;
		public $pool;
		
		public function insert()
		{
			$data=array(
				"account_id" => $this->account_id,
				"town_id" => $this->town_id,
				"type_id" => $this->type_id,
				"created_date" => $this->created_date,
				"modified_date" => $this->modified_date,
				"reference" => $this->reference,
				"price" => $this->price,
				"bedrooms" => $this->bedrooms,
				"bathrooms" => $this->bathrooms,
				"build" => $this->build,
				"plot" => $this->plot,
				"pool" => $this->pool
			);
			$this->id=$db->insert("property", $data);
			return $this->id;
		}
	}
?>

this is where I am calling it in my code: $property->insert();

Maybe it's just a lack of understanding for me but can anyone help me? Thanks.

**Comment by avbdr** [comment]
i think you are missing $db = MysqliDb::getInstance() to get an initialized mysqlidb object inside your class

**Comment by avbdr** [comment]
also i think you might want to take a look on a dbObject class as seems that what you are trying to do :)

**Comment by jk-1001** [comment]
Thanks,

I tried to adjust it by adding your line at the top:

public function insert()
		{
			$db = MysqliDb::getInstance();
			
			$data=array(
				"account_id" => $this->account_id,
				"town_id" => $this->town_id,
				"type_id" => $this->type_id,
				"created_date" => $this->created_date,
				"modified_date" => $this->modified_date,
				"reference" => $this->reference,
				"price" => $this->price,
				"bedrooms" => $this->bedrooms,
				"bathrooms" => $this->bathrooms,
				"build" => $this->build,
				"plot" => $this->plot,
				"pool" => $this->pool
			);
			$this->id=$db->insert("property", $data);
			return $this->id;
		}

However, now I get the following error:

Warning: mysqli_stmt::bind_param(): Number of elements in type definition string doesn't match number of bind variables in on line 1094

Thanks for your help.

**Comment by jk-1001** [comment]
Nevermind, that last error was my own error. Many thanks for your help.
