### ISSUE TITLE
START TRANSACTION - COMMIT

### ISSUE THREAD

**Issue by yansentan** [joshcam/PHP-MySQLi-Database-Class#41]
How do I use START TRANSACTION - COMMIT?

I received this error when using rawQuery function 

- Problem preparing query (START TRANSACTION) This command is not supported in the prepared statement protocol yet

Here is the query : 
$db->rawQuery("START TRANSACTION");
$db->rawQuery("INSERT INTO......");
$db->rawQuery("UPDATE tablet SET coloumn = 'value'");
$db->rawQuery("COMMIT");

Thank you~

**Comment by avbdr** [comment]
This API already landed. Could be closed
