### ISSUE TITLE
NULL comparison

### ISSUE THREAD

**Issue by nilsgraustins** [joshcam/PHP-MySQLi-Database-Class#410]
In the readme.md file the NULL comparison example is given
`$db->where ("lastName", NULL, '<=>');` but its executes wrong query like 
`WHERE  lastName  <=>  NULL`, but the right one will be `WHERE  lastName  IS NOT  NULL`, so  `$db->where ("lastName", NULL, 'IS NOT');` can be used.

**Comment by avbdr** [comment]
thanks, fixed
