### ISSUE TITLE
Echo MySQL value

### ISSUE THREAD

**Issue by AlbertMN** [joshcam/PHP-MySQLi-Database-Class#414]
Probably not really an issue, but I just can't seem to find the documentation on how to echo a simple MySQL table value.

Also, if I want a list of 6 records, with the highest "id" first - how would I do this?

Thank you :)

**Comment by avbdr** [comment]
is it what you are looking for?
```php
$maxId = $db->getValue("users", "max(id)")? 
//select max(id) from users limit 1 
```

```php
$maxIds = $db->orderBy("id", 'desc')->getValue("users", "id", 6)? 
///select max(id) from users order by id desc limit 6
````

**Comment by AlbertMN** [comment]
Well, not really - the two questions doesn't have anything to do with eachother. I just want to 'echo' a table's value. Fx. echo a users' username.

**Comment by avbdr** [comment]
im sorry, i do not understand you at all.

**Comment by AlbertMN** [comment]
Like this; echo escape($user->data()->username);

**Comment by avbdr** [comment]
```
$user = $db->ObjectBuilder()->where('id', 1)->getOne('users');
echo $user->username;
```

**Comment by AlbertMN** [comment]
Thank you - will try that asap.
