### ISSUE TITLE
'Problem preparing query (SELECT * FROM monthly_hits WHERE date = ? AND month = ?

### ISSUE THREAD

**Issue by AlbertMN** [joshcam/PHP-MySQLi-Database-Class#416]
I am getting this error;
Today exists - updating views
Fatal error: Uncaught exception 'Exception' with message 'Problem preparing query (SELECT * FROM monthly_hits WHERE date = ? AND month = ? LIMIT 1) Unknown column 'date' in 'where clause'' in C:\xampp\htdocs\Planestorm\mysql\MysqliDb.php:1479 Stack trace: #0 C:\xampp\htdocs\Planestorm\mysql\MysqliDb.php(1092): MysqliDb->_prepareQuery() #1 C:\xampp\htdocs\Planestorm\mysql\MysqliDb.php(552): MysqliDb->_buildQuery(1) #2 C:\xampp\htdocs\Planestorm\mysql\MysqliDb.php(576): MysqliDb->get('monthly_hits', 1, '*') #3 C:\xampp\htdocs\Planestorm\statics.php(78): MysqliDb->getOne('monthly_hits') #4 {main} thrown in C:\xampp\htdocs\Planestorm\mysql\MysqliDb.php on line 1479

From this code; (when updating)
http://hastebin.com/pitecapuvi.coffee

I can't seem to find the reason.

**Comment by igor-silva** [comment]
I'm with a similar problem:

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /home/XXXX/www/vendas/classes/conexao.class.php on line 128

$params = Array(0, $data_venda_i, $data_venda_f, $var_vmin, $var_vmax);
	$results = $db->rawQuery("SELECT
	Dados_comprador.idDados_comprador,
	Dados_comprador.nome,
	Dados_comprador.dt_nasc,
	Dados_comprador.tel,
	Dados_comprador.cel,
	Dados_comprador.email,
	Dados_comprador.cpf,
	Dados_comprador.rg,
	Dados_comprador.rua,
	Dados_comprador.num_resid,
	Dados_comprador.bairro,
	Dados_comprador.cidade,
	Dados_comprador.uf,
	Dados_comprador.porque_h,
	Dados_imovel.idDados_imovel,
	Dados_imovel.ref,
	Dados_imovel.imovel,
	Dados_imovel.edificio,
	Dados_imovel.rua,
	Dados_imovel.num,
	Dados_imovel.cidade,
	Dados_imovel.bairro,
	Dados_imovel.uf,
	Dados_imovel.apto,
	Dados_venda.idDados_venda,
	Dados_venda.valor_imovel,
	Dados_venda.nf,
	Dados_venda.pos_venda,
	Dados_venda.total_despesas,
	Dados_venda.dt_venda,
	Dados_venda.dt_receb,
	Dados_venda.exclusividade,
	Dados_venda.comissao_corretor1,
	Dados_venda.comissao_corretor2,
	Dados_venda.nome_corretor1,
	Dados_venda.nome_corretor2,
	Dados_venda.comissao_agenc,
	Dados_venda.nome_agenc,
	Dados_venda.comissao_imob,
	Dados_venda.comissao_bruta,
	Dados_venda.comissao_liq,
	Dados_venda.data_pag,
	Dados_venda.form_pag,
	Dados_venda.valor_pag,
	Dados_venda.comissao_bruta,
	Dados_venda.Dados_comprador_idDados_comprador,
	Dados_venda.Dados_imovel_idDados_imovel,
	Dados_venda.usuarios_idUser
	FROM 
	Dados_venda 
	INNER JOIN Dados_comprador ON Dados_comprador.idDados_comprador = Dados_venda.Dados_imovel_idDados_imovel
	INNER JOIN Dados_imovel ON Dados_imovel.idDados_imovel = Dados_venda.Dados_imovel_idDados_imovel 
	WHERE Dados_venda.idDados_venda > 0 
	AND Dados_venda.dt_venda >= ?
	AND Dados_venda.dt_venda <= ?
	AND (Dados_venda.valor_imovel BETWEEN ? AND ?) ", $params);

   print_r($results);

	die();
