### ISSUE TITLE
Change of inserted nordic letters (æ, ø, å)

### ISSUE THREAD

**Issue by AlbertMN** [joshcam/PHP-MySQLi-Database-Class#417]
Title says it all, when I try to update/insert any "special" letters, in this case "æ, ø" and "å", it ends up looking like this;
Ã¦, Ã¸, Ã¥

I don't know if this is a problem with this MySQLi database class, or MySQL.

**Comment by avbdr** [comment]
do you use utf8?

**Comment by AlbertMN** [comment]
Where would I clarify this?

**Comment by avbdr** [comment]
1. mysqlidb sets db charset to utf8.
2. you need to check what charset your tables are using
3. you need to check what input charset is used in your HTML.
to avoid problems just set utf-8 everywhere.

ill close that as not a bug.

**Comment by AlbertMN** [comment]
All my phpmyadmin/MySQL tables are utf8, so is my php document & my <textarea>.
