### ISSUE TITLE
a rawQuery problem Wrong parameter count for php5.5.28 

### ISSUE THREAD

**Issue by mbdmt** [joshcam/PHP-MySQLi-Database-Class#418]
I upgrade php5.5.28,but found error.
rawQuery function inside , about call_user_func_array a error
# error info:
# Warning: Wrong parameter count for mysqli_stmt::bind_param() in D:\web\htdocs\webcc\lib\MysqliDb.php

I tried to modify it to work: Add a determine => count($bindParams)>0 
added check for zero arguments to avoid unnecessary call
# But the uncertainty will have other problems.

```
    if (is_array($bindParams)) {
        $numberOfbindParams = count($bindParams);
        if ($numberOfbindParams>0) {
            foreach ($bindParams as $prop => $val) {
                $params[0] .= $this->_determineType($val);
                array_push($params, $bindParams[$prop]);
            }

            call_user_func_array(array($stmt, 'bind_param'), $this->refValues($params));
        }
    }
```

**Comment by avbdr** [comment]
i think one of your bind params is an array. thats why you are getting this error

**Comment by avbdr** [comment]
please post a testcase to reproduce it

**Comment by johnvanhulsen** [comment]
I get the same warning. My code:

`$mysqli = new mysqli('localhost', 'root', 'pass', 'db');
$db = new MysqliDb ($mysqli);

function getProducts($id) {
	$db = MysqliDb::getInstance();
	$product_ingredients = $db->rawQuery('SELECT * etc...', Array (10));
	foreach ($product_ingredients as $pi) {
		print_r($pi);
	}
}

getProducts(1);`
