### ISSUE TITLE
Return Array In Separated values

### ISSUE THREAD

**Issue by abunour22** [joshcam/PHP-MySQLi-Database-Class#42]
i make this Update For Class .. by adding this function

    /**
     * @param array $arr
     *
     * @return array
     */
    public function reValue($query,$data_ref)
    {
            if(is_array($query) === true)
            {
                foreach ($query as $value) {
                    $data = $value[$data_ref];
                }
                return $data;
            }
    }

usage: 

            $params = array('name', 'city');
            $results= $db->rawQuery("SELECT username, user_id, user_email FROM users WHERE name = ? AND city = ?", $params);
                $UserEmail = $db->reValue($results,'user_email');
   

this return value " user_email " for this user from database ..
 insted of print_r($results);

**Comment by avbdr** [comment]
getValue() is available in master
