### ISSUE TITLE
Limit in update() is not working

### ISSUE THREAD

**Issue by jefvhal** [joshcam/PHP-MySQLi-Database-Class#420]
According to readme.md you should be able to use "Limit" in update()
```
update() also support limit parameter:
$db->update ('users', $data, 10);
// Gives: UPDATE users SET ... LIMIT 10
```

However, this is not working. The limit is completely ignored

**Comment by avbdr** [comment]
do you have a mysqlidb from master?  that were fixed recently

**Comment by jefvhal** [comment]
Hi, I was using the online readme.md as a reference while coding . I used 2.5 (latest release) and not master. When using 2.6 master, the problem is solved indeed.

Clearly I was too quick and have to wait for next release. Thanks for the prompt reply.

**Comment by avbdr** [comment]
you can use master as im about to release new version.
