### ISSUE TITLE
"MySQL host is not set"  on copy()" when creating mysqlidb from mysqli object

### ISSUE THREAD

**Issue by iHaMoo** [joshcam/PHP-MySQLi-Database-Class#422]
Sorry for my English.

I've got " Fatal error: Uncaught exception 'Exception' with message 'MySQL host is not set'  " error response. When used a "copy()" method.

What's problem in my Code?
###### 

$db->where ( 'p.status', '1' ); 

//###### Copy#######
$temp = $db->copy();
$active = $temp->getValue("products p","count(p.code_group)");
print_r($active);

//###### get Data #######
$cols = Array ("p.code_group", "p.code", "p.brand", "p.status");  
$products = $db->withTotalCount()->get ("products p", null, $cols );
print_r($products);
###### 

Thank you for everyone.

**Comment by avbdr** [comment]
please try the latest master. I think this issue is fixed in one of the previous  releases

**Comment by iHaMoo** [comment]
I've already update to lasted release. But still got same error.

**Comment by pieczarkazsolt** [comment]
I get same error, when I use copy() method (in ver2.5)

$db->where('T.delete', null, '<=>');
$dataQuery = $db->copy()
$sum = $db->getValue('test T', 'count(T.test_id)');
$testData = $dataQuery->withTotalCount()->where('T.date', null, '<=>')->get('test T', array($_POST['start'], $_POST['length']), 'T.test_id, T.test_desc);

In this case $testData is: PHP Warning: mysqli::close(): Couldn't fetch mysqli....
(same code works fine in ver2.2)

**Comment by avbdr** [comment]
guys, how do you initialize mysqlidb?

On Wed, Jan 27, 2016 at 10:30 PM, pieczarkazsolt <notifications@github.com>
wrote:

> I get same error, when I use copy() method (in ver2.5)
>
> $db->where('T.delete', null, '<=>');
> $dataQuery = $db->copy()
> $sum = $db->getValue('test T', 'count(T.test_id)');
> $testData = $dataQuery->withTotalCount()->where('T.date', null,
> '<=>')->get('test T', array($_POST['start'], $_POST['length']), 'T.test_id,
> T.test_desc);
>
> In this case $testData is: PHP Warning: mysqli::close(): Couldn't fetch
> mysqli....
> (same code works fine in ver2.2)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/422#issuecomment-175811763>
> .
>



-- 
Alex

**Comment by pieczarkazsolt** [comment]
$db = new MysqliDb ('127.0.0.1', 'user', 'pass', 'dbase');

**Comment by pieczarkazsolt** [comment]
sample:
http://pastebin.com/yThM4E7k

https://cordova.nanosoft.hu/test/test.php?ver=2.2 working
https://cordova.nanosoft.hu/test/test.php?ver=2.5 wrong

**Comment by iHaMoo** [comment]
## My mysqlidb initialize ##
$mysqli = new mysqli (DB_HOST, DB_USER, DB_PASS, DB_NAME);
$mysqli->set_charset ( 'utf8' );
$db = new MysqliDb ($mysqli);

**Comment by avbdr** [comment]
should be working now
