### ISSUE TITLE
Where equals 0 not working correctly

### ISSUE THREAD

**Issue by jk-1001** [joshcam/PHP-MySQLi-Database-Class#423]
I'm trying to include a bit parameter in my query as 0 and the query is not recognising the 0 and selecting everything. This is the code:

$db->where("active", $active);
$props=$db->get("property");
return $db->getLastQuery();

It works fine when specifying 1 for true but not 0 for false. I have also tried with true and false and it seems to give the same output.

**Comment by jk-1001** [comment]
It works if I specify quotes around the 0 so i'll just use that. Is it intended to work that way?

**Comment by avbdr** [comment]
long overdue, but seems thats not a problem for a recent mysqlibd
