### ISSUE TITLE
Order BY Feild No directory

### ISSUE THREAD

**Issue by Toyz** [joshcam/PHP-MySQLi-Database-Class#426]
With the OrderBy function you cannot just do a query of OrderBy with out a direction like 

SELECT * FROM table WHERE id IN (1,5,2,13,4)
ORDER BY FIELD(id, 1,5,2,13,4)

You cannot do that which when using In perserves the order of the IDs which sometimes is needed

**Comment by avbdr** [comment]
were you reading readme? 
```
order by values example:

$db->orderBy('userGroup', 'ASC', array('superuser', 'admin', 'users'));
$db->get('users');
// Gives: SELECT * FROM users ORDER BY FIELD (userGroup, 'superuser', 'admin', 'users') ASC;
```

**Comment by Toyz** [comment]
Tried that, it uses a directory and with my query your losing the keep order with perserving the values

**Comment by avbdr** [comment]
Try a version from master. I think you are using an old version

**Comment by Toyz** [comment]
I am using the version from Master there is force validation for direction in the orderBy

**Comment by Toyz** [comment]
Fixed by using rawQuery

**Comment by avbdr** [comment]
We can fix an actual problem if you will report it precisely.
Can you please show an actual code, what you are expecting to get and what
you are actually getting.
