### ISSUE TITLE
Issue with UPDATE and JOIN

### ISSUE THREAD

**Issue by thingNumber1** [joshcam/PHP-MySQLi-Database-Class#427]
Hi,

I'm trying someting like this:

	$data = Array (
		'a.status' => 'Unlinked',
	);
	$db->join("post p", "a.post_id=p.id", "INNER");
	$db->where("p.id", '58');
	$db->where("a.filename", 'image.jpg');
	$db->where("a.status", 'Linked');
	$db->where("p.status", 'Deleted', '!=');
	$done = $db->update("attachment a", $data);

Im getting a query like this one:

	UPDATE attachment a INNER JOIN post p on a.post_id=p.id SET `a.status` = 'Unlinked' WHERE p.id = '58' AND a.filename = 'image.jpg' AND a.status = 'Linked' AND p.status != 'Deleted'

The problem is on `a.status` that come with this symbol (`) on each side, when it is suppoused to be in the and after the point. So MySQL is looking for a field named 'a.status' deside a field name 'status' in table 'a'.

I need to use [a.status] and not only [status] because as you see table 'a' and table 'p' has a 'status' field and I could get this error: the Column 'status' in where clause is ambiguous.

**Comment by thingNumber1** [comment]
If usefull for someone, that how to solve the problem:

FIND (line 1096 in my file, in function _buildDataPairs):

	if (!$isInsert) {
		$this->_query .= "`" . $column . "` = ";
	}

REPLACE IT FOR:

	if (!$isInsert) {
		if(strpos($column,'.')===false){
			$this->_query .= "`" . $column . "` = ";
		}else{
			$this->_query .= str_replace('.','.`',$column) . "` = ";
		}
	}

**Comment by avbdr** [comment]
can you please file a pull request with this fix? ill merge that.

On Thu, Jan 21, 2016 at 10:16 PM, thingNumber1 <notifications@github.com>
wrote:

> If usefull for someone, that how to solve the problem:
>
> FIND (line 1096 in my file, in function _buildDataPairs):
>
> if (!$isInsert) {
>     $this->_query .= "`" . $column . "` = ";
> }
>
> REPLACE IT FOR:
>
> if (!$isInsert) {
>     if(strpos($column,'.')===false){
>         $this->_query .= "`" . $column . "` = ";
>     }else{
>         $this->_query .= str_replace('.','.`',$column) . "` = ";
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/427#issuecomment-173678566>
> .
>



-- 
Alex

**Comment by thingNumber1** [comment]
Well... It's my first time creating a Pull Request. I don't know how to upload my file or the right way to create it.

**Comment by avbdr** [comment]
pushed to master. thanks
