### ISSUE TITLE
Post array of rows to <td>

### ISSUE THREAD

**Issue by AlbertMN** [joshcam/PHP-MySQLi-Database-Class#428]
I can't really figure out how I would select, and output multiple SQL/MySQL values, and post them in to a HTML Table, wanting it to look like this:
https://i.gyazo.com/83c34db0db1ada40180f49679723b996.png
All except "No." are actual values in my database, but how would I do this?

I get this;
foreach ($x as $x)
    echo '<td>' . $x . '</td>';

But that would only output one value, are there variables for every selected value or something?

**Comment by avbdr** [comment]
this is not a helpdesk. please stop posting newbish questions. 
look the sources of https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/index.php
