### ISSUE TITLE
Concat with CURDATE and CURTIME

### ISSUE THREAD

**Issue by DarylJG** [joshcam/PHP-MySQLi-Database-Class#43]
It's becoming a problem with this API that the following query: 

$Update_Parameter = array("Sophie");
        mysqli_report(MYSQLI_REPORT_ALL ^ MYSQLI_REPORT_STRICT);
        $Database->rawQuery("UPDATE users_login SET LastLogin = CONCAT(CURDATE(), ' ', CURTIME() ) WHERE Username=?"
            ,$Update_Parameter);

is returning the following error: 

Fatal error: Problem preparing query (UPDATE users_login SET LastLogin = CONCAT(CURDATE(), ' ', CURTIME() ) WHERE Username=?) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' ', CURTIME() ) WHERE Username=?' at line 1 in C:\xampp\htdocs\EntireProj\Core\DatabaseWrapper.php on line 444

Running this query through PHPMYADMIN returns that there is nothing wrong with the query, and running a Raw instance of MySQLi will complete this query. SO the problem lies within the API it's self

**Comment by avbdr** [comment]
this should be working now. I think could be closed
