### ISSUE TITLE
2 where conditions  > Fatal Error

### ISSUE THREAD

**Issue by gordielachance** [joshcam/PHP-MySQLi-Database-Class#430]
Hi !
I read the doc and i'm trying to setup some _where_ conditions.

        $results = $this->db->where('FBID', NULL, 'IS NOT')->where('email', $email)->getOne('users');

Makes it crash :

> Fatal error: Uncaught exception 'Exception' with message 'Problem preparing query (SELECT * FROM users WHERE FBIDIS NOT NULL AND email = ? LIMIT 1)

while this works (extra space before "IS NOT")

        $results = $this->db->where('FBID', NULL, ' IS NOT')->where('email', $email)->getOne('users');

Shouldn't this be handled by MySQLi-Database-Class ?

**Comment by avbdr** [comment]
thanks, ill work this out

**Comment by ricwein** [comment]
It should be enough, to add a single space in before the `$operator` at [`L1399`](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/MysqliDb.php#L1399).

```php
} elseif ($val === null) {
	$this->_query .= ' ' . $operator . ' NULL';
}
```

Patch: [is_null.patch](https://files.ricwein.com/drop/is_null.patch)

**Comment by avbdr** [comment]
can you make sure that tests are passing and submit a pull request?

**Comment by ricwein** [comment]
Sure, done: #457
