### ISSUE TITLE
How can i manage date format in json array

### ISSUE THREAD

**Issue by erpankajsood** [joshcam/PHP-MySQLi-Database-Class#432]
Firstly thanks for making this wonder resource.
My question is how to manage date format in json array.
for example: my query is:

`
$cols = Array('rs.rsid', 's.site_name', 's.site_address', 'u.user_name', 'rs.r_date', 'rs.r_time_start', 'rs.r_time_end');
$db->join("sites s", "s.site_id = rs.r_site_id", "INNER");
$db->join("users u", "u.user_id = rs.r_user_id", "INNER");
$rostring_schedule = $db->get ("rostring_sites rs", null, $cols);
$list = array('data' => $rostring_schedule);
echo json_encode($list);
`

its response is: `{"data":[{"rsid":3,"site_name":"Site1","site_address":"assfasd\r\nfasdfasdfoahosgaiga","user_name":"pankajs","r_date":"2016-01-05","r_time_start":"07:00","r_time_end":"12:00"}]}`

My basic requirement is change the date format in json result set. I am trying lots for method to work with but no way found.

Is it i am working wrong.

**Comment by avbdr** [comment]
why dont use use mysql data formatting capabilities?
