### ISSUE TITLE
php 5.2 version get error 

### ISSUE THREAD

**Issue by everblue83** [joshcam/PHP-MySQLi-Database-Class#435]
I am using php 5.2.17 on CentOS 6.5,
but I got error below ->
Parse error: syntax error, unexpected T_FUNCTION in MysqliDb.php on line 1848

if i comment out tableExists function , it works fine.
how can i use this library?
only comment out this function ?

can you review this issue ?
thank you.

**Comment by avbdr** [comment]
fixes in latest release
