### ISSUE TITLE
Add method to export data

### ISSUE THREAD

**Issue by cyberwani** [joshcam/PHP-MySQLi-Database-Class#436]
Hi @joshcam ,
It will very helpful, if you add support to export and import database.

**Comment by Noneatme** [comment]
See https://github.com/Noneatme/PHP-MySQLi-Database-Class/commit/487c461832f5e9a55cb987a5224b33e11b6d4758 for importing CSV files

**Comment by avbdr** [comment]
import feature was added in master. no export feature yet

**Comment by avbdr** [comment]
added

**Comment by TwinMist** [comment]
Did export get added as can not see any code for it?

thanks
