### ISSUE TITLE
delete() returns false, when affected rows is zero

### ISSUE THREAD

**Issue by pieczarkazsolt** [joshcam/PHP-MySQLi-Database-Class#439]
I have 2 tables
USERS:
id | username | name
1 | test_1 | John Doe
2 | test_2 | Test User 2

LOG:
user_id | log_msg | date
2 | delete task | 2016....
2 | create task | 2016....

My problem: When I delete John Doe's LOG entries, the query returns with _false_:

```php
$db->where('user_id', 2);
if($db->delete('log')) echo 'successfully deleted';
```
(i think ) In this case, the _false_ is a wrong value

```php
public function delete($tableName, $numRows = null)
{
...
return ($stmt->affected_rows > 0)
}
```

thx

**Comment by Noneatme** [comment]
There seems to be some errors in your code. I tired to reproduce your problem, but I failed to do so.

`require_once  "MysqliDb.php";

$db = new MysqliDb ('localhost', 'noneatme', '12345', 'db_test');
$db->where('user_id', 2);
if($db->delete('log')) echo 'successfully deleted';`

> php test.php
> successfully deleted

Do you have more info, e.G. more code lines?

**Comment by pieczarkazsolt** [comment]
sorry sorry sorry :(

`$db->where('user_id', 1);`
not
`$db->where('user_id', 2);`

**Comment by Noneatme** [comment]
Well, in that case it makes sense, because there is no data row with the user_id 1.

**Comment by avbdr** [comment]
ill close that as it doesnt looks like a bug
