### ISSUE TITLE
Insert from select?

### ISSUE THREAD

**Issue by scoman81** [joshcam/PHP-MySQLi-Database-Class#441]
Is it possible to do this with the class?

INSERT INTO table1 (col1, col2)
SELECT a as col1, b as col2 FROM table2

I see the subquery insert example, but it's a bit different in that the subquery is a single column of the single-row insert data, and i'm trying to make a multi-row select be the entire insert data.

Thanks!

**Comment by fryiee** [comment]
I recently had to do this as well, and this was the closest I got. I don't think it's possible to run multiple separate columns in the single subquery. Let me know if there's a particular reason this is bad! (It's worked in my test cases):

```php
$data = [
        "col1" => $db->subQuery()->getOne("table1", null, "col1 as a")->getLastQuery(),
        "col2" => $db->subQuery()->getOne("table1", null, "col2 as b")->getLastQuery(),
    ];
$id = $db->insert("table2", $data);
```
Attempting to use getValue in the subquery returned an error for using an array from L605.

**Comment by VeNoMouS** [comment]
How would you go about this for all columns?

For instance.
```
INSERT INTO <table> SELECT * FROM <othertable> WHERE <othertable>.id=?
```

I'm trying to get the insert ID without having to fluff about too much, but rawquery obviously does not return the insert id.

**Comment by avbdr** [comment]
i dont think you need getLastQuery() 

```
$data = [
        "col1" => $db->subQuery()->getOne("table1", null, "col1 as a"),
        "col2" => $db->subQuery()->getOne("table1", null, "col2 as b"),
    ];
$id = $db->insert("table2", $data);
```
