### ISSUE TITLE
Is it any way to get sql query generated by this class

### ISSUE THREAD

**Issue by iamtechplayer** [joshcam/PHP-MySQLi-Database-Class#442]
Hi

I need to check, which query is generated and running at present. Such as sql query:

`SELECT * FROM TBL_NAME WHERE ????`

**Comment by Stewe21** [comment]
[https://github.com/joshcam/PHP-MySQLi-Database-Class#query-exectution-time-benchmarking](url)
Something like "Query exectution time benchmarking"?

**Comment by ricwein** [comment]
I don't know about a *present* realtime (or befor execution) solution, but you can fetch the generated query after executing it with `$db->getLastQuery();`. Also see the readme section for [helper methods](https://github.com/joshcam/PHP-MySQLi-Database-Class#helper-methods)

```php
$db->get('users');
echo "Last executed query was ". $db->getLastQuery();
```

**Comment by circuitmamu** [comment]
please view this link of codeignitor framework
http://www.codeigniter.com/user_guide/database/query_builder.html

$this->db->get_compiled_select()

can we make jus like that Compiles the selection query just like $this->db->get() but does not run the query. This method simply returns the SQL query as a string.
