### ISSUE TITLE
Order by default sorting method

### ISSUE THREAD

**Issue by bazzila** [joshcam/PHP-MySQLi-Database-Class#445]
Why is the default DESC sorting? Typically, the default ASC.

**Comment by PetengDedet** [comment]
I think the reason is people want to know newly inserted data rather than the old data first.
This is non technical, but it's up yo you. Feel free to use ASC order by 
`$this->db->orderBy('filed','type');`

**Comment by avbdr** [comment]
library is already in use by lot of peoples, so hard to change old defaults. sorry
