### ISSUE TITLE
How to use this query by php-mysqli-database-class

### ISSUE THREAD

**Issue by alihesari** [joshcam/PHP-MySQLi-Database-Class#446]
How to use this query by php-mysqli-database-class:
`SELECT * FROM `xs_orders` WHERE (`date` BETWEEN '' AND '') AND (`status`='incomplete') AND (`order_id` LIKE '%d%' OR `siteName` LIKE '%d%' OR `productTitle` LIKE '%d%' OR `date` LIKE '%d%' OR `status` LIKE '%d%' OR `totalPrice` LIKE '%d%' OR `quits` LIKE '%d%' OR `orderDesc` LIKE '%d%' OR `orderDesc2` LIKE '%d%') ORDER BY `order_id` DESC`

**Comment by avbdr** [comment]
thats not a paid support :)
