### ISSUE TITLE
MySQL Cluster Support?

### ISSUE THREAD

**Issue by VonHirsch** [joshcam/PHP-MySQLi-Database-Class#447]
Just wondering if you've thought about implementing support for MySQL Cluster.  It entails creating a simple wrapper for reads & writes as detailed here:

https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-scaleout.html

Maybe it could just be a library configuration with a flag and two connections (one for reads, one for writes)

thanks!  still using the library and love it!

**Comment by fatihtoprak** [comment]
sound awesome ;)

**Comment by avbdr** [comment]
thats in todo  for next version

**Comment by avbdr** [comment]
we finally came to that. should be landed shortly

**Comment by avbdr** [comment]
landed in master
