### ISSUE TITLE
Non-Latin Characters?

### ISSUE THREAD

**Issue by Ynhockey** [joshcam/PHP-MySQLi-Database-Class#449]
Hi,

I tried to use the class with non-Latin characters, and got question marks.

Tried to run: $db->rawQuery("SET NAMES 'utf8'"); before and it didn't help either.

Is this a known issue, wontfix issue, or something new?

Thanks in advance!

**Comment by avbdr** [comment]
seems your database data is not in utf8. check this, convert and then retry.
