### ISSUE TITLE
Limit x,y ?

### ISSUE THREAD

**Issue by ttyazilim** [joshcam/PHP-MySQLi-Database-Class#451]
How can we use limit (x.y) sql queries,

For example, is this true usage for "` limit 2,3 `" as "` $db->get('users',2,3);`"

**Comment by ttyazilim** [comment]
$logins = $db->rawQuery('select manset.manset_baslik from manset limit 3,3');

**Comment by ricwein** [comment]
it also possible to pass an offset to the default `get()` method, without using `rawQuery()`. Just pass an array with offset and limit as the second parameter.

```php
$db->get('users', Array(2, 3));
```
