### ISSUE TITLE
Where function raw condition

### ISSUE THREAD

**Issue by arieffikhrie** [joshcam/PHP-MySQLi-Database-Class#452]
Is it possible to do raw condition like this

````
$db->where('email1 IN ? OR email2 IN ?', array($emailList1, $emailList2));
````

**Comment by ricwein** [comment]
Just use the `rawQuery()` method like mentioned in the [Readme](https://github.com/joshcam/PHP-MySQLi-Database-Class#running-raw-sql-queries):

```php
$db->rawQuery('email1 IN ? OR email2 IN ?', Array($emailList1, $emailList2));
```

**Comment by avbdr** [comment]
yes, that will work, no need to use rawquery

**Comment by ricwein** [comment]
oh yeah sorry, didn't recognize, that you just want to write the where statement as raw.
