### ISSUE TITLE
Fulll text search (match-against) usage?

### ISSUE THREAD

**Issue by ttyazilim** [joshcam/PHP-MySQLi-Database-Class#453]
How can we use this query in this class?
`SELECT * FROM firma WHERE MATCH(detay,adi) AGAINST('tags' IN BOOLEAN MODE)`

**Comment by ttyazilim** [comment]
any help?

**Comment by avbdr** [comment]
raw where condition would help
```
$db->where('MATCH(detay,adi) AGAINST('tags' IN BOOLEAN MODE)'); 
```
