### ISSUE TITLE
I want to view the query before it insert or update

### ISSUE THREAD

**Issue by circuitmamu** [joshcam/PHP-MySQLi-Database-Class#454]
as example if I want to insert some record like below example

$data = Array ("login" => "admin",
               "firstName" => "John",
               "lastName" => 'Doe'
);
//$id = $db->insert ('users', $data);
if($id)
    echo 'user was created. Id=' . $id;

So commented the line of insert function but I want to view the sql that is actually run and want to make sure that there is no error in sql generated statement

**Comment by iamtechplayer** [comment]
No way to get before ?

**Comment by avbdr** [comment]
closing as a dup
