### ISSUE TITLE
where IN returns one value because of 'single quote'

### ISSUE THREAD

**Issue by ttyazilim** [joshcam/PHP-MySQLi-Database-Class#455]
i have multiple cheackbox in html form.
```
<input name="bk[]" type="checkbox"  value="16">
<input name="bk[]" type="checkbox"  value="17">
```
and this is my class usage:
```
$bk = $_GET['bk']; 
foreach($bk as $k => $v){  $bk[$k] = "'".$v."'"; } 
	$a=implode(",", $bk);
	if($a!="")
{
	$db->where('kat', Array($a), 'IN');	
}
```
but this  returns  kat IN ( '16,17' ) and it doesnt work it must be  kat IN ( 16,17 ) without quotes.

**Comment by avbdr** [comment]
you need to call     $db->where('kat', $a, 'IN');

**Comment by ttyazilim** [comment]
Omg, thats all i must do, it spends my 12 hour..
$db->where('kat', $_GET['bk'], 'IN');
