### ISSUE TITLE
Selecting field with content:  Name <office@email.com>,

### ISSUE THREAD

**Issue by catalin87** [joshcam/PHP-MySQLi-Database-Class#456]
Selecting field with content:  
`Name <office@email.com>,`

returns: 
`Name ,`

Why is ignoring the text between < > ?

Here is my code:

`$db->where ("user", $user);`
`$db->orderBy("date_send","desc");`
`$emails = $db->get("emails");`

I have in "emails"  a field named "to" with the content:
`Name <office@email.com>,`

If I 
echo $emails[0]['to']

I get:
Name ,

**Comment by avbdr** [comment]
I think the problem is somewhere in your code. library is not transforming an output in any ways

**Comment by catalin87** [comment]
Great :+1:  
Thanks and sorry :) 

The result of the echo is: 
Name <name@email.com>,

but Chrome get <name@email.com> as a html tag .. I can see it if I view source :)
