### ISSUE TITLE
How do i create a where with this class?

### ISSUE THREAD

**Issue by jakobdo** [joshcam/PHP-MySQLi-Database-Class#461]
I now the:
$db->where and $db->orWhere

How do i create a query like:

where (x = ? or x = ? or y = ?) and z = ?

And ? is replaced with vars from php.
It the only way to use rawQuery ?

**Comment by avbdr** [comment]
$db->where("z"...) -> where("(x = ? or x = ? or y = ?) ....

**Comment by jakobdo** [comment]
Thanks.

**Comment by Gregor-Agnes** [comment]
But is this still injection free if I have to use external variables in the or clauses?

**Comment by Gregor-Agnes** [comment]
Ooops, found it: $db->where ("(id = ? or id = ?)", Array(6,2));

Btw: Thank you for that great class 👍
