### ISSUE TITLE
Raw query - Strange output

### ISSUE THREAD

**Issue by carliblaz** [joshcam/PHP-MySQLi-Database-Class#464]
I'm using rawQuery for selecting records that have dates bigger as date - interval and smaller as date - interval:

```
$db->rawQuery("SELECT * FROM table WHERE date > NOW() - INTERVAL duration MINUTE ORDER BY date ASC", $num); <- This works just fine
```
```
$db->rawQuery("SELECT * FROM table WHERE date < NOW() - INTERVAL duration MINUTE ORDER BY date ASC", $num); <- This doesn't work
```

After building last query here is the result: 
[0] => SELECT * FROM table WHERE date 

And idea?

**Comment by carliblaz** [comment]
This works somehow:

```
$db->where('date < NOW() - INTERVAL duration MINUTE');
```

**Comment by avbdr** [comment]
I think you are using very old mysqlidb version. please try to update
