### ISSUE TITLE
Reserved keywords on insert (and others

### ISSUE THREAD

**Issue by 1stdnsltd** [joshcam/PHP-MySQLi-Database-Class#47]
Line 359 - to be able to use reserved words in column names, like condition, name, status the line should be modified to the following

                $this->_query .= '(`' . implode($keys, '`, `') . '`)';

Encapsulating all field names in quotes, better idea of course would be to not use reserved words as column names, but if working an existing database, this would be required.

**Comment by avbdr** [comment]
this could be closed. Already fixed.
