### ISSUE TITLE
get two times same table in one page

### ISSUE THREAD

**Issue by ttyazilim** [joshcam/PHP-MySQLi-Database-Class#476]
Here is my code

```
$db->where(x,1);
$x=$db->get("table");
echo $db->count

$db->where(y,1);
$x=$db->get("table");
echo $db->count
```

But it doesnt work for me, how can i use same table twice in one page..

**Comment by raakesh** [comment]
I don't see any problem here. It works for me. The two echoed values will be side by side. Say, first value is 3 and second value is 5, the final echoed output will be 35.
