### ISSUE TITLE
single row field fetch

### ISSUE THREAD

**Issue by ITest** [joshcam/PHP-MySQLi-Database-Class#48]
Hey,

I am newbie to mysql oop and found this great class but I wonder how there is now fetch field function to get a result for just one row and I don't have to get it into array and write the code every time like this $query[0]['id'] ? and why it should be an array?!
Finally I hope you add more examples for people just like me which just started their way to mysqli and oop.

Thanks

**Comment by avbdr** [comment]
could be closed
