### ISSUE TITLE
Inserting Many Rows With One Query

### ISSUE THREAD

**Issue by bwright611** [joshcam/PHP-MySQLi-Database-Class#483]
Great work so far. I'm not sure if this is an issue, but I need to do a large import and it's taking forever with doing one row at a time. I believe inserting that functionality will make this class even greater. If it's already in there and not documented, I apologize!

**Comment by avbdr** [comment]
Hello,
I still cant decide how to do that right. https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/208

**Comment by avbdr** [comment]
closing as dup

**Comment by bwright611** [comment]
OK, thanks. I'll just do another connection and do a query myself. Is there a function to get your mysqli object so I can use it directly, instead of opening another connection?

**Comment by avbdr** [comment]
you don't need to get another connection. start the transaction, loop inserts via rawquery(), commit()

thats all

**Comment by avbdr** [comment]
fixed in master
