### ISSUE TITLE
Support for "LIKE"

### ISSUE THREAD

**Issue by VonHirsch** [joshcam/PHP-MySQLi-Database-Class#484]
I also noticed there isn't support for a "like" query, so i'm using rawQuery instead like this:

$users = $this->db->rawQuery('SELECT name from TABLE where IP like ?', Array ("%".$IP."%"));

**Comment by ricwein** [comment]
you can use the `where` method with the third argument, see: #478:

```php
$db->where('IP', '%' . $IP . '%', 'like');
```

**Comment by VonHirsch** [comment]
Ah ok cool, thanks for the tip!
