### ISSUE TITLE
[question] Just a quick and simple question

### ISSUE THREAD

**Issue by AlexioVay** [joshcam/PHP-MySQLi-Database-Class#485]
Is this:

        $db->where('id', $_SESSION['temp_uid']);
        $db->delete('users');
        $db->where ('id', $_SESSION['temp_uid']);
        $db->update ('users', Array ('pass' => $data['new_password']));

the same as:

        $db->where('id', $_SESSION['temp_uid']);
        $db->delete('users');
        $db->update ('users', Array ('pass' => $data['new_password']));

?

**Comment by tommyknocker** [comment]
No, it's not the same. On get(), getOne(), getValue(), update(), delete(), replace(), etc. object internal data is being deleted. So the  update('users') in second example will update all users.

**Comment by AlexioVay** [comment]
Thank you! Good to know.
