### ISSUE TITLE
Solution for Undefined offset: error

### ISSUE THREAD

**Issue by multiaki** [joshcam/PHP-MySQLi-Database-Class#487]
I was getting error: "Notice: Undefined offset: 1 in /home//PHP-MySQLi-Database-Class/MysqliDb.php on line 1567"
Somehow,, $vals was not counted empty. I fixed by adding $vals = array_filter($vals);

 protected function replacePlaceHolders($str, $vals)
    {
        $i = 1;
        $newStr = "";

//new code 
        $vals = array_filter($vals);

```
    if (empty($vals)) {
        return $str;
    }
    while ($pos = strpos($str, "?")) {
        $val = $vals[$i++];
        if (is_object($val)) {
            $val = '[object]';
        }
        if ($val === null) {
            $val = 'NULL';
        }
        $newStr .= substr($str, 0, $pos) . "'" . $val . "'";
        $str = substr($str, $pos + 1);
    }
    $newStr .= $str;
    return $newStr;
}
```

**Comment by hitwill** [comment]
Thanks, I experienced the same problem, and the fix above seemed to w ork

**Comment by avbdr** [comment]
can I see a code which is causing such an error? thanks

**Comment by hitwill** [comment]
This is the function that was causing the error:

`protected function replacePlaceHolders($str, $vals)
    {
        $i = 1;
        $newStr = "";
        $vals = array_filter($vals);////This MOD seems to fix the error!!!!!
        if (empty($vals)) {
            return $str;
        }

        while ($pos = strpos($str, "?")) {
            $val = $vals[$i++];
            if (is_object($val)) {
                $val = '[object]';
            }
            if ($val === null) {
                $val = 'NULL';
            }
            $newStr .= substr($str, 0, $pos) . "'" . $val . "'";
            $str = substr($str, $pos + 1);
        }
        $newStr .= $str;
        return $newStr;
    }`

**Comment by avbdr** [comment]
Well, I can figure out what library code is generating a warning. What i were asking is a test case which I can use to reproduce this problem. 
Thanks

**Comment by woeitje** [comment]
I've maybe the same problem, when I have a column: is_success as tinyint the value for that is removed from the data array for some reason. This is the $str and $vals that went into the replacePlaceHolders function:

INSERT INTO cms_user_login_attempt (`type`, `username`, `ip_address`, `user_agent`, `is_success`, `login_at_timestamp`) VALUES (?, ?, ?, ?, ?, ?) 
Array 
( 
[0] => ssssii 
[1] => cms 
[2] => 191060 
[3] => 83.250.39.168 
[4] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36 
[6] => 1483534067 
) 

You can see that the index 5 is removed somewhere. If I put the is_success as the last key you see the same only index 6 is then removed. While you see in the index 0 that it expects 4 strings and 2 ints. The fix above didn't do anything in my case.

Maybe this info helps you to figure out what is going wrong. I don't have the time now to debug it further and find a fix.
