### ISSUE TITLE
How to join 3 Tables using $db->join fucntion

### ISSUE THREAD

**Issue by VeRJiL** [joshcam/PHP-MySQLi-Database-Class#488]
hi guys,
thnx josh for the great and useful MysqliDb class, it helped me a lot but recently i got a problem that cant do it with $db->join command, actually i dont know the way ... .
i hope u can help me with it.
how can i join 3 tables with the join fucntion ?

**Comment by dunqi** [comment]
Use 2 $db->join commands.

**Comment by VeRJiL** [comment]
thnx @dunqi  for the help.
i have a another question. if we join table A with B we will have table AB, right ? then if we use the second join command we join table AB with C which gives us table ABC. am i right ?

**Comment by dunqi** [comment]
I dont know what you mean. Cause in my world I dont call a join of two tables (A and B) as AB. So you cant say: join("usersarticles", ...) if you join "users" with "articles".

**Comment by VeRJiL** [comment]
@dunqi thank you man, now i understand the logic of join method.

**Comment by sakthikamal** [comment]
> Use 2 $db->join commands (every table that joins - in 1 command)
> 
> $db->join("users u", "p.tenantID=u.tenantID", "LEFT");
> $db->join("arcitcles a", "a.tenantID=u.tenantID", "LEFT");

$this->db->join("customers c", "i.cusName=c.cusName", "LEFT");
		$this->db->join("payment c", "i.invoiceId=c.invoiceId", "LEFT");

this format right or wrong
