### ISSUE TITLE
No update if I redirect

### ISSUE THREAD

**Issue by thingNumber1** [joshcam/PHP-MySQLi-Database-Class#489]
I have a code similar to this one

	// Update
	$db_stats->where('id', $var['id']);
	$data = array(
		'param_1' => $var['param_1'],
		'param_2' => $var['param_2'],
		'param_3' => $var['param_3'],
		'param_4' => $var['param_4'],
		'param_5' => 1,
	);
	$db_stats->update('table', $data);
	//echo $db_stats->getLastQuery(); exit;

	// 301 redirect
	header($_SERVER["SERVER_PROTOCOL"].' 301 Moved Permanently');
	header('location: '.$url);
	exit;

And it don't update the info. But if I uncomment the `echo $db_stats->getLastQuery(); exit;` part, (in fact, if I `exit` the script without redirecting) the data get updated.

**Comment by raakesh** [comment]
I don't think there is any relationship between update query and redirection. 
Use `echo $db->getLastError()` after update query and tell us what you see.

**Comment by thingNumber1** [comment]
Using `var_dump ($db_stats->getLastError()); exit;` I see `string(0) ""`.
I know that's weird but this is exactly the reason I came here... If I exit the script before the redirection the UPDATE works well... =S

**Comment by ATouhou** [comment]
Try this:
// Update
$db_stats->where('id', $var['id']);
$data = array(
    'param_1' => $var['param_1'],
    'param_2' => $var['param_2'],
    'param_3' => $var['param_3'],
    'param_4' => $var['param_4'],
    'param_5' => 1,
);
$stats = $db_stats->update('table', $data);

if($stats){
// 301 redirect
header($_SERVER["SERVER_PROTOCOL"].' 301 Moved Permanently');
header('location: '.$url);
exit;
}else{
echo $db_stats->getLastQuery(); exit;
}


ensures it does not activate redirection without query executed and response received

**Comment by thingNumber1** [comment]
Man! This didn't solve directly the issue, but it was the prove that I was taking a wrong approach. The library was successfully executing the UPDATE before the redirection. The problem was that after the redirection the data was updated again in the new location with empty values; and this is why I thought there were no update.

I am sorry for coming to the wrong place, but I apreciate you help. Thanks.
