### ISSUE TITLE
HOW TO INSERT DATE NOW()

### ISSUE THREAD

**Issue by asimsidd** [joshcam/PHP-MySQLi-Database-Class#49]
I am trying to insert into a table where one of the field is datetime type. I have tried the following but no success. Please advice.

$insertData = array('mesg_id' => $mesg_id, 						'main_order_alias' => $order_alias[0]["order_alias"], 'sub_order_alias' => $_POST['suborder_alias'], 'from_user_id' => '1', 'to_user_id' => $to_user[0]["user_id"], 'mesg_isread' => '0', 'mesg_isdelete' => '0',	'mesg_date' => array('NOW()'), 'mesg_details' => $_POST["msg"]);
if ( $db->insert('tblmessage', $insertData) ){
	echo json_encode(array("success" => "1" ));
}else{
	echo json_encode(array("error" => $db->getLastError() ));
}

**Comment by avbdr** [comment]
fixed. could be closed
