### ISSUE TITLE
hello, can i use to do like this?  ->getOne("tabName", ["content(json)"])

### ISSUE THREAD

**Issue by wuchuguang** [joshcam/PHP-MySQLi-Database-Class#490]
data:

id    content
1     jsondata

$result = getOne("tabName", ["id, content(json)"]);

$result['content'] is json data.

**Comment by dunqi** [comment]
That's just mean, that you select the Row with the exakt name "content(json)" from the table tabName.

SELECT id, content(json) FROM tabName LIMIT 1;

You cant parse functions in Select-Statements. If you want JSON:

$db->JsonBuilder()->getOne("tabname", "id, content");

**Comment by wuchuguang** [comment]
yes, thanks

**Comment by wuchuguang** [comment]
getOne("tabName", ["id, content(json), other(xml)"]) like this.

can't select once do ok.

**Comment by wuchuguang** [comment]
format return data. format one fields

getOne("tabName", ["id, content(myformat)"]).

function myformat_writer($data){
      return format($data);
}

function myformat_reader($data){
      return format($data);
}

**Comment by avbdr** [comment]
not a bug
