### ISSUE TITLE
Strange thing ...

### ISSUE THREAD

**Issue by subseven** [joshcam/PHP-MySQLi-Database-Class#492]
I am using the Class in live system. Until the beginning of last week all worked fine.

But now it takes sometimes several requests to get DB results back. I have checked the output, it results a success without any effective results.

Meanwhile it had to switch to direct mysqli code, without this class. And this works still fine. So I don´t know where the issue is, but it seems really a issue related to the Class !

running on Ubunti 12 / 14 with latest updates:
php/fpm

regards,
marquez

**Comment by Noneatme** [comment]
Can you post some examples about the requests you are sending to your sql server?

**Comment by subseven** [comment]
One example:
$db = new MysqliDb (MYSQL_HOST, MYSQL_USER, MYSQL_PASS,MYSQL_DB);
$db->setPrefix (MYSQL_TABLE_PREFIX);

	$user = $db->getOne ("users", "*,
	date_format(`created`,'%d.%m.%Y  %H:%i') AS create_date,
	date_format(`last_modified`,'%d.%m.%Y  %H:%i') AS lastmod_date,
	date_format(`addon_activated`,'%d.%m.%Y') AS addon_activated_date,
	date_format(`addon_expires`,'%d.%m.%Y') AS addon_expire_date,
	date_format(`expires`,'%d.%m.%Y') AS expire_date,
	unix_timestamp(`last_modified`) AS lastmod_unix");

	if ($db->count > 0) Print_r($user);

This is one example. All other routines are equal or using raw queryies.

With the same result.

I also let a profi coder, who also had experience with this class take a look on my code, and he didn´t found an error in Code.

regards,
Marquez

**Comment by avbdr** [comment]
this code is pretty basic, i dont think it will cause any problems.
I believe issue is related to a $db->where() calls somewhere outside of the shown examples.

**Comment by subseven** [comment]
Well,

you can believe me or not. This is the only Code which is used int the PHP for my SQL Query, which causes the issue ! And you also should know, that it was working long time without any problems. But from one day to another it caused this descripted issue !

You also can trust me, when I say to you, when making the query directly with mysqli without using the class on low leve all works fine.

Why do I say this ? Because in our live project I was forced to do so,otherwise we couldn´t continoue our project.

Regards

**Comment by avbdr** [comment]
i believe you, but I need a real testcase to fix a problem. In 99% of such bugs issue usually is on the upper level.

**Comment by subseven** [comment]
Ok,
we can do the following:

Currently I am really under pressure for other projects.

But when I find Time, I will create exactly this php script on one Domain for you for testing reasons, with some demo entries, and the used class, give you ftp access, where you can see the true used php code, and you can check by yourself to find out or fix the error.

Because normally I prefer to use existing classes except using own written code, because on other Scripts I also used the class where the calls were more complicated and needed to be more secured.

**Comment by avbdr** [comment]
im sorry but im not a free troubleshooter.
