### ISSUE TITLE
mysqli is null

### ISSUE THREAD

**Issue by und3rsc0re** [joshcam/PHP-MySQLi-Database-Class#493]
Hi! I'm encountering major problems using this great library. No matter what I do, I get this error:

mysqli is null

using 

`$database = new MysqliDb('localhost', 'root', 'pass', 'test');`

I also tried to use the advanced way, however, it didn't come off and I'm just furious about it. Why isn't it working? Any suggestions?

**Comment by arieffikhrie** [comment]
can you try this?
`$con = new mysqli('localhost', 'user', 'pass', 'demo');`
`$db = new MysqliDb($con)`

**Comment by avbdr** [comment]
do you subclass mysqlidb somehow? I think it's related to construct overload

**Comment by und3rsc0re** [comment]
@avbdr How may I understand? I'm new to PHP, so please be a little more patient with me. :+1: Anyway, I have a folder called 'mysql' containing all the files of the mysql wrapper. I required it from index.php by 'require_once('mysql/MysqliDb.php')' and then started to work with it.

**Comment by avbdr** [comment]
do you have mysqli php extension installed?

**Comment by und3rsc0re** [comment]
I'm using XAMPP but also tried WAMP. Both working fine for me with other mysqli classes or self-written stuff, so I assume mysqli is installed.

**Comment by und3rsc0re** [comment]
@arieffikhrie Now I'm getting this error:

`Notice: Undefined property: MysqliDb::$error in F:\xampp\htdocs\includes\mysql\MysqliDb.php on line 1599
`

**Comment by avbdr** [comment]
can you post an exact code which is not working?

**Comment by und3rsc0re** [comment]
@avbdr `$connection = new MysqliDb(Array(
    'host' => $host,
    'username' => $username,
    'password' => $password,
    'db' => $db,
    'port' => $port,
    'charset' => $charset
));
$database = new MysqliDb($connection);`

**Comment by und3rsc0re** [comment]
When I want to check if there was an error, I'm using this code where it says undefined property (as stated above):

`echo $database->getLastError();`

**Comment by avbdr** [comment]
your code shouldnt produce anything. because it's just a mysqlidb object. 
$db = mysqlidb(...);
print_r($db->get('sometbl');

**Comment by und3rsc0re** [comment]
@avbdr Could you please elaborate that?

**Comment by avbdr** [comment]
not a bug
