### ISSUE TITLE
Where menthod chaining not work with getValue()

### ISSUE THREAD

**Issue by circuitmamu** [joshcam/PHP-MySQLi-Database-Class#495]
$return = $db->getValue ("table_name",'column_name')->where('id',8);
echo "{$return} value found";

This code I tried but it gives me an fatel-error
Fatal error: Call to a member function where() on a non-object

because if I write like below it will work
$db->where('id',8);
$return = $db->getValue ("table_name",'column_name');
echo "{$return} value found";

any solution so code will use with chain of where function conditions

**Comment by avbdr** [comment]
all get*() functions returning a value, not a mysqlidb object. 
so you use it always like db->where->where...->orderBy->get*

**Comment by avbdr** [comment]
not a bug
