### ISSUE TITLE
Escaping and /n /r

### ISSUE THREAD

**Issue by Alekusu** [joshcam/PHP-MySQLi-Database-Class#497]
Hello,

First thanks for your amazing work ! It's a great help.
I read all the documentation and the github but didn't find nothing about my question.

When i escape the data, the results in the DB is a lot of /r/n for the return lines.

For example, the code i use to update the table : 

`$data = Array();
	foreach($_POST as $cle => $element) 
	{
		//$data[$cle] = $db->escape($element);
	}
	$db->update ('table', $data);`

if i don't escape, everything is perfect. 
So my question is : do i really need to escape the data for security purpose when i use this class ? 
If i need it, how can i avoid this kind of results with /r/n

thanks a lot !

**Comment by avbdr** [comment]
you need to use preg_replace to remove end of lines

**Comment by Alekusu** [comment]
Thanks, but you didn't reply to my initial question, do i really need to escape the data ?
And the preg_replace solution is a little dirty when you use prepared statement.

**Comment by avbdr** [comment]
you dont need to escape the data as prepared statements do that for you. 
but you for sure need to cleanup you data to a real view you want to get. 
SQL escaping has nothing to do with EOLs

**Comment by Alekusu** [comment]
So just to be clear (sorry i'm a noob) : there is no need to use $db->escape() for security purpose ? 
Without, it's totally safe and no risk of SQL injection ? 
Right ?

**Comment by avbdr** [comment]
read about what are prepared statements
