### ISSUE TITLE
Reduces/rounds the latitude longitude from mysql - DECIMAL

### ISSUE THREAD

**Issue by kani-rifluxyss** [joshcam/PHP-MySQLi-Database-Class#498]
I have lat,long stored in mysql table as decimal values
`79.1854190826416`
comes as 
`79.185419082642`
is there a solution for this?

**Comment by GAMELASTER** [comment]
check value in table structure.
https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html
The declaration syntax for a DECIMAL column is DECIMAL(M,D). The ranges of values for the arguments in MySQL 5.7 are as follows:
- M is the maximum number of digits (the precision). It has a range of 1 to 65.
- D is the number of digits to the right of the decimal point (the scale). It has a range of 0 to 30 and must be no larger than M.

**Comment by kani-rifluxyss** [comment]
thank you fro your response. Actually mysql table has the value, it's changing only when it's read from the data array fetched using 
`db-get();`

I manually checked in database table, it contains all letters so mysql is not rounding it.

**Comment by avbdr** [comment]
i think its a problem with php float precission . What does regular mysqli/pdo call returns you?

**Comment by kani-rifluxyss** [comment]
regular mysqli/php brings the entire data
`13.597188180552 79.185419082642`

**Comment by kani-rifluxyss** [comment]
I am checking few other combinations, will get back. thanks

**Comment by kani-rifluxyss** [comment]
Ok, now I am sure there is a difference!

1. regular mysqli gives this:     [lng] => 79.1854190826416
2. Phpmyadmin gives this:     [lng] => 79.1854190826416
3. `$db->get'    gives this  ` 79.185419082642`

Please help

**Comment by iZume** [comment]
I tried and the get results me all decimals, i believe which the problem is with you php.ini, or predeterminated configuration.

Try:

ini_set("precision", 17);

**Comment by avbdr** [comment]
have you sort it out?

**Comment by kani-rifluxyss** [comment]
@iZume thanks its making a difference! Please see the difference results from PHp with 14, 17 precision and I tried the same query from mysql command line tool as well. Any idea?

@avbdr For my requirement I was able to handle this different with LIKE in MySQL, however I would learn why we are seeing these differences. I will continue to work on this, so please comment on this when you get some time!

Thanks
![results](https://cloud.githubusercontent.com/assets/5585046/17293410/bc60c340-580d-11e6-8848-c9f836941a7e.png)
