### ISSUE TITLE
mysql_insert_id() return 0

### ISSUE THREAD

**Issue by santiagochen** [joshcam/PHP-MySQLi-Database-Class#50]
Hi, guy,
firstly thanks for your PHP class for Sql basic connection.
however, when I use it, I found a problem, here is my code:
====================
$db->insert('contact', $array);
echo(mysql_insert_id());
====================
data could be accuratly inserted. but mysql_insert_id() can not get the last insert, so it only returns 0. 
could you help me with checking the issue?

**Comment by avbdr** [comment]
could be closed. 
$insertId = $db->insert('contact', $array);
