### ISSUE TITLE
__destruct never called?

### ISSUE THREAD

**Issue by VonHirsch** [joshcam/PHP-MySQLi-Database-Class#500]
Hi - just wondering, have you had any issues with the destructor being called?  I put a print_r statement in there, and I never see it on the console, but it could just be me :)

**Comment by YamiOdymel** [comment]
__destruct always called, it's my biggest problem now.

**Comment by VonHirsch** [comment]
cool thanks! :+1:

**Comment by iZume** [comment]
The __destruct is called when the script is stopped or set $object = null

**Comment by avbdr** [comment]
not a bg

**Comment by VonHirsch** [comment]
ok thanks - I just re-tested this and we're good.  I had put logging in the project MysqliDb php file, but it was picking up from another project... long story :) but good now.
