### ISSUE TITLE
dev/master: Getting a PHP Parse error on a centos 6.5 system running PHP 5

### ISSUE THREAD

**Issue by slash-zero** [joshcam/PHP-MySQLi-Database-Class#515]
**Latest dev/master:** Getting a PHP Parse error on a centos 6.5 system running PHP 5.

`PHP Parse error:  syntax error, unexpected '[' in vendor/joshcam/mysqli-database-class/MysqliDb.php on line 695
`

**Comment by slash-zero** [comment]
I see there is a pull request that addresses this issue.  When can it be merged in?

**PR:** https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/510

**Comment by avbdr** [comment]
thank you, merged.
