### ISSUE TITLE
$db->where('column', NULL) not working

### ISSUE THREAD

**Issue by michael-lynch** [joshcam/PHP-MySQLi-Database-Class#520]
I am trying to get all columns from a table where my column `lat` equals `NULL`.

```
$db->where('lat', NULL);
$results = $db->get('my_table');
```

`$results` is always empty but I can see rows in my DB with `lat` set as `NULL`. My column is set as a `DECIMAL` in the database, with the length as `65,7`, but I also have `NULL` set as the default value and that _is_ what I see. What am I missing? Or is this a bug?

**Comment by avbdr** [comment]
can you please try latest stable release?

**Comment by michael-lynch** [comment]
I just updated it and I'm getting the same result. I checked other columns that weren't `DECIMAL` and it behaved the same way. I can get columns where a column is equal to a string or integer, but not yet `NULL`. Is this on my end or this inherent to the class? Any suggestions?

**Comment by avbdr** [comment]
is this working?
```
$db->where('lat is NULL');
$results = $db->get('my_table');
```

**Comment by michael-lynch** [comment]
Yes, that did work!

So, what is the difference?

**Comment by avbdr** [comment]
you can also use:
```
$db->where ("lat", NULL, '<=>');
```
previous sniplet works as a just raw where condition.

**Comment by michael-lynch** [comment]
Yes, both work for me. Thanks for your help!

**Comment by ATouhou** [comment]
This should go into the documentations :-)

**Comment by avbdr** [comment]
i think it is already in documentation :)
