### ISSUE TITLE
Problem in $db->now()

### ISSUE THREAD

**Issue by weeellingtonnn** [joshcam/PHP-MySQLi-Database-Class#522]
$db->where ("(date = ? or date = ?)", Array('2016-09-13', $db->now()));
$db->where ("login","mike")
$res = $db->get ("users");
// Gives: SELECT \* FROM users WHERE (date = '2016-09-13' or date = '2016-09-14') and login='mike';

Problem in $db->now()

PHP Notice:  Array to string conversion in /_/_/_/_/mysqli_Controller.php on line 1893
PHP Warning:  mysqli_stmt::bind_param(): Number of elements in type definition string doesn't match number of bind variables in /_/_/_/_/mysqli_Controller.php on line 1431

**Comment by avbdr** [comment]
you cant use now() in select(). its intended to be used in insert() or update(). 
```
$db->where ("(date = ? or date = NOW())", Array('2016-09-13'));
$db->where ("login","mike")
$res = $db->get ("users");
``

**Comment by ATouhou** [comment]
Also happens if you try to pass an object (wrong format) into a datetime field by update
