### ISSUE TITLE
 Case sensitivity problem in $db->groupBy('')

### ISSUE THREAD

**Issue by AcademyLime** [joshcam/PHP-MySQLi-Database-Class#523]
DB field name is **userID**
If I use groupBy as $db->groupBy('**userID**'); it doesn't work.  (uppercase i)
But if I use it as $db->groupBy('**useriD**'); it works. (lowercase i)

groupBy() uses preg_replace() function and I think this is the problem.

**Comment by avbdr** [comment]
why preg_replace will be a problem here?
