### ISSUE TITLE
Question mark causing problems on rawQuery()

### ISSUE THREAD

**Issue by RLCabral** [joshcam/PHP-MySQLi-Database-Class#528]
If you have something like this:
`$db->rawQuery("INSERT INTO table (name,about) VALUES ('me','who?') ON DUPLICATE KEY UPDATE about=VALUES(about)")`

It will produce this SQL statement:
`INSERT INTO table (name,about) VALUES ('me','who'NULL'') ON DUPLICATE KEY UPDATE about=VALUES(about)`

It replaced the question mark with 'NULL'.

And throws this error:
`Notice: Undefined offset: 1 in /var/www/html/vendor/joshcam/mysqli-database-class/MysqliDb.php on line 1886`

Despite the wrong SQL statement, the insert works. Escaping that question mark will not fix the problem.

The reason I am using rawQuery() to insert data is because I need to insert multiple entries _and_ update on duplicate. As far as I know, there is no way to do this with insertMulti().

**Comment by vmdude** [comment]
Same issue occurs with non-RAW query:

`$db->get("vms", 5, array("id", "'VM' AS type", "CONCAT('showvm.php?vmid=', id) as urlid", "name", "lastseen"));`

This throw the same error:
`Notice:  Undefined offset: 2 in /var/www/admin/MysqliDb.php on line 1844`

**Comment by avbdr** [comment]
mysqli treats as a placeholders for values. You need to pass this variables as a bind variable and you will be fine
