### ISSUE TITLE
£ sign stores in database as ?

### ISSUE THREAD

**Issue by satchboy** [joshcam/PHP-MySQLi-Database-Class#529]
Hi !

I seem to be having a problem with storing £ characters using the following method of updating or inserting ::

$data['fieldName'] = $var;
            
$db->where ('fieldId', $myId);
$db->update ('tableName', $data);

My database was set as latin1, so I've switched it over to uf8, along with all the tables and field character sets.

I've tried various permutations of field type as well, and the only thing that retains the '£' character is the 'blob' field which I don't want to use everywhere for obvious reasons.

Any ideas ?

Do I need to use the escape() function to sort this ? Single and double quotes appear to already be escaped and store perfectly fine, $ signs work as well, it's just the £ sign I'm having difficulty with.

Thanks in advance :)

**Comment by ricwein** [comment]
This is most likely not a problem with this class, but with your used charset from input-sources, script-files and database. To avoid such encoding problems, you should choose and use only one charset for all of them.

Pay some attention to the default mysql utf8 charset, which might is not the solution you are looking for, instead try `utf8mb4` ([details](https://stackoverflow.com/questions/279170/utf-8-all-the-way-through)).

Init your MysqliDb-Instance accordingly.
```php
$db = new MysqliDb($host, $username, $password, $db, $port, 'utf8mb4');
```

And check your file encoding settings in the php-editor of your choice , e.g. [sublime text](https://stackoverflow.com/questions/21289157/set-encoding-of-file-to-utf8-with-bom-in-sublime-text-3).

**Comment by satchboy** [comment]
Thanks for the comprehensive answer, it was a combination of all 3 :)

Solution was ::

1) Switch full database/tables/column names to utf8mb4
2) Ensure meta charset is served properly<meta http-equiv="content-type" content="text/html; charset=utf-8">

These two steps sorted out the £ sign being stored and retrieved correctly in the database, but then it broke the display of the £ sign in the html on the page itself.

 The final bit of the puzzle which you identified :

3)check the encoding of the .php pages. I use Netbeans, and I couldnt see an encoding option. Opened in Notepad++ and the file was encoded in ANSI. Switched to "Encode in UTF8 without BOM" and the £ sign that 'was' there changed to a black square with "xA3" inside it. Deleted that, typed the £ sign again, saved and uploaded and its perfect.

Many thanks @ricwein and hope this helps somebody in the future.

**Comment by avbdr** [comment]
I don't think you need utf8mb. pound sign should just work in basic utf8
