### ISSUE TITLE
how to use SELECT IF statment

### ISSUE THREAD

**Issue by hosamalzagh** [joshcam/PHP-MySQLi-Database-Class#530]
I need to create a SELECT IF statement
`SELECT
                    sum(IF(bill_type in ('sales','purchsasesReturns'),money,0)) as field1,
                    sum(IF(bill_type in ('salesReturns','purchsases'),money,0)) as field2
 FROM tableName `

is there a way to do this statement ?

**Comment by xXXIMMATTHEWXXx** [comment]
Pretty sure you can just use the raw query method :D

**Comment by avbdr** [comment]
$db->get('tableName',null, "sum(IF(bill_type in ('sales','purchsasesReturns'),money,0)) as field1, sum(IF(bill_type in ('salesReturns','purchsases'),money,0)) as field2")
