### ISSUE TITLE
rawQuery "INSERT" not return result;

### ISSUE THREAD

**Issue by Opekunov** [joshcam/PHP-MySQLi-Database-Class#532]
Hi, guys! Can help?

After this function my DB updated, but $res is empty;
Or how i can use this query in $db->insert ?

```

$res = $db->rawQuery("INSERT INTO items ($u, title)
SELECT * FROM (SELECT '$key', '$title') AS tmp
WHERE NOT EXISTS (
    SELECT $u FROM items WHERE $u = '$key'
) LIMIT 1;
");

```

**Comment by avbdr** [comment]
i think one of you variable are empty as it this function should just work

**Comment by Opekunov** [comment]
Its test code:
`$key = 'testkey_3';
$u = 'unique_key';
$title = 'test';

$res = $db->rawQuery("INSERT INTO items ($u, title)
SELECT * FROM (SELECT '$key', '$title') AS tmp
WHERE NOT EXISTS (
    SELECT $u FROM items WHERE $u = '$key'
) LIMIT 1;
"); 

echo 'affected rows: ' . $db->count . '<br>'; 
echo 'lastQuery: ' .$db->getLastQuery() .'<br>';
echo "Result: "; 
print_r($res);
`
And result:

`
affected rows: 1
lastQuery: INSERT INTO items (unique_key, title) SELECT * FROM (SELECT 'testkey_3', 'test') AS tmp WHERE NOT EXISTS ( SELECT unique_key FROM items WHERE unique_key = 'testkey_3' ) LIMIT 1; 
Result: Array ( )
`

Result Array is empty, what i'm doing wrong?

**Comment by avbdr** [comment]
what you are expecting to get there? Insert wont return you any data. Im not 100% sure, but i think rawQuery on insert will return you false in case insert will fail and empty array in case of success. 

as well looking at affected array you can see that 1 row were successfully processed.

**Comment by Opekunov** [comment]
Yeap, i know about 1 row, but i need get ID (auto_increment) of this added row;

**Comment by avbdr** [comment]
in this case seems you would need to call one more call.
```
 $id = rawQueryValue('select LAST_INSERT_ID() limit 1');
```

**Comment by Opekunov** [comment]
Its work, thx!
