### ISSUE TITLE
Connection Error Handling

### ISSUE THREAD

**Issue by skibulk** [joshcam/PHP-MySQLi-Database-Class#533]
After I instantiate MysqliDb I want to check if the database connection was successful so that I can handle bad connections accordingly. Although I verified a successful connection by inserting data via the MysqliDb interface, the library incorrectly returns "mysqli is null".

```
$db = new MysqliDb ('localhost', 'admin', 'admin', 'database');
$e = $db->getLastError();
if($e != '') {
    die($e);
}
```

**Comment by avbdr** [comment]
you can use ping() to check that
