### ISSUE TITLE
How to Make Queries For Search Form ?

### ISSUE THREAD

**Issue by siberfx** [joshcam/PHP-MySQLi-Database-Class#535]
I want to make a search system like the sample below;
    $query = mysqli_query("SELECT * FROM house WHERE town LIKE '%$search%'") or die ("Could not search");
but I couldnt succeed with some trying.. 
could you please assist me for this? how may I solve this issue?

**Comment by dunqi** [comment]
SELECT * FROM house WHERE town LIKE '%ndon%' - should print "London" for example.
So the solution is:

$db->where('town', '% search%', 'like');
$rows = $db->get('house');

**Comment by siberfx** [comment]
what about pagination? I couldnt succeed with pagination code.

**Comment by ricwein** [comment]
Please read the Readme. To be more precise: [Readme: Pagination](https://github.com/joshcam/PHP-MySQLi-Database-Class#pagination).

For your specific problem, you can do something like:

```php
$page = 1;
$db->pageLimit = 10;

$db->where('town', '%' . $search . '%', 'LIKE');
$page = $db->paginate('house', $page);

echo "showing $page out of " . $db->totalPages;
```

**Comment by siberfx** [comment]
This i know the content listing according to pagination.. this is what i
need
