### ISSUE TITLE
How to Use NOT like Condition?

### ISSUE THREAD

**Issue by ferdyzz4** [joshcam/PHP-MySQLi-Database-Class#536]
I don't know to use NOT like within WHERE condition, 
I've try using manual query in phpmyadmin, and working well

the code is : 
`SELECT *
FROM `table`
WHERE `column` NOT LIKE '%foo1%'
AND `column` != 'foo2'`

Could you add this in your class?

Thank you

**Comment by emmgfx** [comment]
Check this example in the readme:

    $db->where ('id', 50, ">=");
    // or $db->where ('id', Array ('>=' => 50));
    $results = $db->get ('users');
    // Gives: SELECT * FROM users WHERE id >= 50;

Maybe you can try to use something like

    $db->where ('id', 50, "!=");

**Comment by ricwein** [comment]
To be more precise [Readme: Where / Having Methods](https://github.com/joshcam/PHP-MySQLi-Database-Class#where--having-methods)

```php
$db->where("lastName", NULL, 'IS NOT');
$results = $db->get("users");
```

For your specific query you can use something like:

```php
$db->where('column', '%'.$foo.'%', 'NOT LIKE');
$db->where('column', 'foo2', '!=');
$db->get('table');
```
