### ISSUE TITLE
Multi query prepared statement

### ISSUE THREAD

**Issue by Disane87** [joshcam/PHP-MySQLi-Database-Class#538]
Hey guys, I've discovered your class and I really love that. Currently I'm planning an schedule automism to get some things automatically done.

Now is my question, I call a prepared statement with rawQuery() which consists of two SELECT-Statements. In my example the first dataset is the data which I want to send via mail (some data to review from administrators i.e.) and the second is a table of the proper recipients for the mailing.

Is there any chance to achieve this wihtout having a second prepared statement?

**Comment by avbdr** [comment]
prepared statements doesnt support multiple queries at the same time unfortunately.

**Comment by Disane87** [comment]
If I execute a prepared statement within HeidiSQL it shows me both resultsets. So why should this not be possible, I guess HeidiSQL will get that data in the same way.
