### ISSUE TITLE
mysqli_num_fields

### ISSUE THREAD

**Issue by igestalten** [joshcam/PHP-MySQLi-Database-Class#539]
i'm trying to use mysqli_num_fields on a query with no success - any idea?

**Comment by ricwein** [comment]
Hey. Please take a look at the Readme. To be more specific: [Readme: Select Query](https://github.com/joshcam/PHP-MySQLi-Database-Class#select-query). Each select-query stores a count of all effected queries as default in `$db->count`.

```php
$users = $db->get('users');
echo 'Users found: ' . $db->count;
```

**Comment by igestalten** [comment]
but $db->count returns number of rows? I´m trying to ge the number of fields.
Usually i would do something like
$result = mysqli_query($query);
$numberOfFields = mysqli_num_fields($result);
with $numberOfFields returning the number of fields (cols).

**Comment by avbdr** [comment]
rtfm
