### ISSUE TITLE
SubQuery error

### ISSUE THREAD

**Issue by Maxamed** [joshcam/PHP-MySQLi-Database-Class#540]
hey guys,

Firstly, thank you in advance for your help.

Can you pass an Array of ID's to GET Statement  ?

Thanks,

**Comment by ricwein** [comment]
Hey, first: the issues are not for general help.

However: It's possible to pass an array with id's (or an `subQuery()` object) to a `where()` select. See [Readme: Where / Having Methods](https://github.com/joshcam/PHP-MySQLi-Database-Class#where--having-methods).

If you have an array of ID's, you can use:

```php
$ids = array(2, 3, 5, 7, 11, 13, 17);

$db->where('id', $ids, 'IN');
$db->get('tablename');
```
