### ISSUE TITLE
dbObject.php or MysqliDb.php

### ISSUE THREAD

**Issue by myselfgaurav** [joshcam/PHP-MySQLi-Database-Class#542]
there are two class library which one should i use bit confused, seems dbObject.php is not used

**Comment by ricwein** [comment]
Please read the [Readme](https://github.com/joshcam/PHP-MySQLi-Database-Class#objects-mapping) and [dbObject Readme](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.md).

The `MysqliDb.php` class is the actual core of this project and probably what you are looking for. The `dbObject.php` is used as a basic ORM to access db tables like objects in php.

**Comment by myselfgaurav** [comment]
ok thanks bro one more help 

i am trying to make dropdown below is my code seems not working 


```
$allstate = MysqliDb::getInstance()->rawQuery("select * from $tablename $cond");
		$dropdownlist="<option value=''> --Select-- </option>";
		while($row = $allstate->get_result()){
			$issel ="";
			if($selected==$row["$key"]){ $issel ="selected"; }
			$dropdownlist .= '<option value="'.$row["$key"].'" '.$issel.' >'.$row["$val"].'</option>';
		}
		echo $dropdownlist;
```

**Comment by avbdr** [comment]
read the doc

**Comment by myselfgaurav** [comment]
yea but there is no method to add get so i put this question anyways thanks

**Comment by avbdr** [comment]
there is no such method because you cant read.

**Comment by ricwein** [comment]
[Readme: Select Query](https://github.com/joshcam/PHP-MySQLi-Database-Class#select-query).

```php
$db = new MysqliDb ('host', 'username', 'password', 'databaseName');
$list = $db->get($tablename);
foreach($list as $entry) {
  // do stuff with $entry here
}
```

Really everything necessary is written down into the readme for this simple case.

**Comment by myselfgaurav** [comment]
yeah i was saying about that how can i add some condition here like catid=10

**Comment by ricwein** [comment]
Last response from me. Please really take a deep look into the Readme.

[Readme: Where](https://github.com/joshcam/PHP-MySQLi-Database-Class#where--having-methods)

```php
$db->where('catid', 10);
```

**Comment by myselfgaurav** [comment]
thanks a lot one more help no idea why so 

echo $db->insert('ia_customers', $data);
echo "see-->".$db->getInsertId();

i am able to insert but none of echo give me last inserted id as result or above query

**Comment by ms-reza** [comment]
i need image insert code 
please someone help me
