### ISSUE TITLE
is this sql injection free

### ISSUE THREAD

**Issue by myselfgaurav** [joshcam/PHP-MySQLi-Database-Class#544]
hi i am using MysqliDb.php

just want to check is there need to filter parametere , it is free from sql injection ?

**Comment by ricwein** [comment]
Short: This lib uses prepared statements and therefor injections wont work.

Please take a look at previous issues first before asking next time:

- [**#508** Protected with SQL injection ?](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/508)
- [**#408** SQL Injection, question.](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/408)
- [**#400** Is it usefull for Prevent Sql injection?](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/400)
- [**#174** Is this class prevent common security vulnerabilities: SQL injection, XSS, CSRF etc](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/174)

**Comment by ATouhou** [comment]
Except for the rawQueries right? :-)

**Comment by ricwein** [comment]
You really shouldn't inline user-input into your raw-queries or ANY other query method.

But if you use placeholders in your raw-queries, this class also applies your variables and executes the queries as a prepared statement, and therefor also is protected against sql injections.

See: [Readme: rawQueries](https://github.com/joshcam/PHP-MySQLi-Database-Class#running-raw-sql-queries)

```php
$user = $db->rawQueryOne ('select * from users where username = ? and password = ?', array(
    $_POST['username'],
    $_POST['password'],
));
echo $user['username'];
```

**Comment by ATouhou** [comment]
Agreed, actually just wanted you to clarify, so that somebody who reads this "github issue" assumes its' safe to do so :-) 

Thanks for your great effort RicWein

**Comment by myselfgaurav** [comment]
nice bro
