### ISSUE TITLE
how can i use greater than and less than in where condition 

### ISSUE THREAD

**Issue by myselfgaurav** [joshcam/PHP-MySQLi-Database-Class#546]
is there way to add greater than and less than condition in where statement

**Comment by Momenoor** [comment]
$db->where ('id', 50, ">=");


*_________________________________________________*

*Momen I. Noor | Financial Auditor | AXIS Auditing&Accounting*
Office.301 - Hilal Bin Tarraf Building Sheikh Zayed Road, Dubai, UAE. PO.B:
(8002) -[image: cid:image012.png@01D18507.641B6FC0]
<https://goo.gl/maps/WgKBDGRpxbR2>*take me there*
<https://www.google.ae/maps/dir//25.1923575,55.2593556>
T: +9714 328 777 8 ext.(107) | F: + 9714 328 444 9 | M: + 9715 059 475 92
E-mail: momen.noor@gmail.com | [image: Description:
cid:image003.jpg@01CD4FCE.E133FB70]629-685-304
<http://www.icq.com/people/629685304> | [image: Description: Description:
Description: Description: Description:
http://www.iydro.com/tez/skype_icon.gif] Momen.Noor
<callto://Live:Momen.Noor_1/>

*http://www.redhaalrahma.com <http://www.redhaalrahma.com> -
http://www.axisauditing.com <http://www.axisauditing.com>*

**Comment by ricwein** [comment]
Exactly.

The condition feature is documented in the [Readme: Where / Having Methods](https://github.com/joshcam/PHP-MySQLi-Database-Class#where--having-methods) in the 4th code-block.
