### ISSUE TITLE
PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch.

### ISSUE THREAD

**Issue by kailashyadav** [joshcam/PHP-MySQLi-Database-Class#547]
PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50544 Library:50629 in MysqliDb.php on line 281

**Comment by ricwein** [comment]
It's not a problem with this Library, but your php installation. Your installed mysqli extension doesn't match your php. Try to update them both.
