### ISSUE TITLE
Query return array when it's null

### ISSUE THREAD

**Issue by indchubaka** [joshcam/PHP-MySQLi-Database-Class#549]
So, table "payments" is empty.

$conn->rawQueryOne('select itemscount from payments where id=?', [$id]);
result: NULL

$conn->rawQueryOne('select **sum(itemscount)** from payments where id=?', [$id]);
result: array(1) { [0]=> NULL }

This brings difficulties when verifying the result.

**Comment by avbdr** [comment]
$conn->rawQueryOne('select itemscount from payments where id=? limit 1', [$id]);
