### ISSUE TITLE
SQL syntax error

### ISSUE THREAD

**Issue by SinanEker** [joshcam/PHP-MySQLi-Database-Class#55]
In line https://github.com/ajillion/PHP-MySQLi-Database-Class/blob/master/MysqliDb.php#L362 there is a ", " and should be trimmed away if there is just one insert or select, but it doesn't work. I get the following error:
```txt
Problem preparing query (INSERT INTO test(title) VALUES(?, )) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' 

Thanks folks!

**Comment by avbdr** [comment]
i think wont be an issue already
