### ISSUE TITLE
Utilizing LAST_INSERT_ID()

### ISSUE THREAD

**Issue by oohrah** [joshcam/PHP-MySQLi-Database-Class#552]
This may have already been answered but I have searched here as well as google but was unable to find anything about how to get the results using this class wrapper. Is it possible with this? If yes, can you provide sample code

**Comment by ricwein** [comment]
Obviously you haven't looked at the Readme: [Insert Query](https://github.com/joshcam/PHP-MySQLi-Database-Class#insert-query).

The `insert()` method returns the last inserted id as the result (if the query succeeded).

```php
$id = $db->insert ('users', array(
    'username' => 'smith',
    'password' => password_hash('password'),
));

if($id) {
    echo 'user was created. Id=' . $id;
} else {
    echo 'user creation failed with error: ' . $db->getLastError();
}
```

**Comment by oohrah** [comment]
Awesome. It was right in front of me the whole time. I must have read that 100 times Thanks for the speedy response and for jogging my memory
