### ISSUE TITLE
Problem inserting & outputting generated salt (mcrypt_create_iv)

### ISSUE THREAD

**Issue by AlbertMN** [joshcam/PHP-MySQLi-Database-Class#555]
`$db->getOne('table')['salt'];` does not output the exact correct salt. I am not quite sure, but some formatting might be a bit off. It doesn't output with line breaks, and `nl2br();` did not fix it.

I can't seem to figure out exactly what the cause of this is, but the salt I get from the database is not the same as the one i inserted.

**Comment by VeNoMouS** [comment]
examples....
