### ISSUE TITLE
Using dbObject returns object with getOne but complex object with get

### ISSUE THREAD

**Issue by Tom29** [joshcam/PHP-MySQLi-Database-Class#559]
I'm using dbObject for mapping table records into object.
Everything's good with `getOne()`:
`Location::where('id',$id)->getOne();`

But with `get()` , it returns a complex object with data inside it:
`
[data] => Array
                (
                    [l_id] => 5
                    [l_name] => NewYork
                )
`
How do i get the list of objects with each single one is like made of `getOne()` method?

**Comment by avbdr** [comment]
$cities = cities::get();
foreach ($cities as $city)
       echo $city->name;

**Comment by Tom29** [comment]
@avbdr i know this way, but i have to create a foreach and create new single object based on data.
$cities = cities::get();
foreach ($cities as $city)
$city[] = new Location($city->id, $city->name);

Anyway to get directly the list of Location after the Location query ?

**Comment by avbdr** [comment]
get() returns an array of objects. You do not need to create anything.

**Comment by Tom29** [comment]
@avbdr get() return array of object but didn't map the results to the objects.
If i want to access to every single object, i have to do like this: `$l{0}->data['id']`
instead of` $location->id`

**Comment by avbdr** [comment]
$location = $l[0];
echo $location->id.

I have no idea how do you want to map to get single id out of a **multiple** objects. Or you want to get an array of ids?

**Comment by avbdr** [comment]
why dont you just create a Location dbobject and wont cal Location:get() ? :)

**Comment by Tom29** [comment]
@avbdr `$data['id']` ~> is an array , `$data->id` is an object.
`getOne()` maps a single record (from db) to the object (location).
So the location object has all the properties like id, name. Can be access via `location->id` , `location->name`

But `get()` returns an array, not a list of location objects, this is why i'm asking for mapping

**Comment by avbdr** [comment]
this is how its designed to be. There is no plans to make get() to return arrayobject or spl or something like that. array work pretty good and self sufficient.

**Comment by avbdr** [comment]
it's like we are spending on different languages.

> But get() returns an array of data, not a list/array of location objects

you are wrong. get() returns an array of objects like getOne() returns. 

each object have $data element inside which is yes, is array, but you can get its properties as a variable without successing array.  as I showed you in foreach example

**Comment by Tom29** [comment]
If you designed this class for data mapping, so it will be useful if it can help to map db record to the objects. If your purpose is using array: so it wasted learning OOP.

Yes: `get()` return an array of objects but not the data it needed, while we have to access to `$locations{0}->data['id']` to access to the id field of one record
Its inconsistent because by using `getOne()` i can access to the id by `$location->id`

**Comment by avbdr** [comment]
you can access locations{0}->id

**Comment by Tom29** [comment]
Oh, well. You saved my life -.-
