### ISSUE TITLE
Multi table join not returning correct data

### ISSUE THREAD

**Issue by riples** [joshcam/PHP-MySQLi-Database-Class#564]
Could someone tell me what I'm possibly doing wrong:

```
$this->db->join( 'product_categories c', 'p.CategoryId = c.Id', 'LEFT' );
$this->db->join( 'manufacturers m', 'p.ManufacturerId = m.Id', 'LEFT' );
$this->db->where( 'p.Code', $code );
$product = $this->db->getOne( 'products p', null, '*, c.Name as CategoryName, m.Name as ManufacturerName' );
```

This does not seem to return CategoryName or ManufacturerName in my results  It only returns the product record.  When I view the `lastQueryResults()` I get the following statement:

`SELECT  * FROM products p LEFT JOIN product_categories c on p.CategoryId = c.Id LEFT JOIN manufacturers m on p.ManufacturerId = m.Id WHERE  p.Code = '2302-44500-025'  LIMIT 1`

**Comment by riples** [comment]
Just to elaborate further on this: After some testing it seems that this statement works (which is returning all products rather than just one):

```
$this->db->join( 'product_categories c', 'p.CategoryId = c.Id', 'LEFT' );
$this->db->join( 'manufacturers m', 'p.ManufacturerId = m.Id', 'LEFT' );
$products = $this->db->get( 'products p', null, 'p.*, c.Name AS CategoryName, m.Name AS Manufacturer' );
```

Therefore, I'm not sure if the problem stems around the `db->getOne()` command?

**Comment by ricwein** [comment]
The `getOne()` method only requires 2 Parameters instead of the 3 Parameters of `get()`.
Calling `getOne('table', null);` assumes `null` as the requested rows, which is why it returns unexpected results. Try:

```php
$product = $this->db->getOne( 'products p', '*, c.Name as CategoryName, m.Name as ManufacturerName' );
```

**Comment by riples** [comment]
Thanks so much - that worked a treat!
