### ISSUE TITLE
extend dbObject - override __construct - ERROR

### ISSUE THREAD

**Issue by KTP95** [joshcam/PHP-MySQLi-Database-Class#565]
Hello,
I'm trying extend dbObject with a custom __construct.
Or better with a extended costruct , i want make a "callback" after create object (for loaded extra data not in mysql table, but in a .json file ... [ another story] )

So, i try make extend with owerride __construct

```
class user extends dbObject {
	
    protected $dbTable = 'users';
	protected $primaryKey = 'id';
    protected $dbFields = array (
        'id' => array ('int')
    );

    protected $relations = array (

    );
	public function __construct ($data = null) {
		
        $this->db = MysqliDb::getInstance();
		
        if (empty ($this->dbTable))
            $this->dbTable = get_class ($this);
		
        if ($data) {
            $this->data = $data;
			$this->_constructCallback();
		}
    }
	
	public function _constructCallback() {
		
		echo "run";
	}

}
```

BUT, i get fatal error
`
<br />
<b>Fatal error</b>:  Call to a member function where() on null in <b>.... /vendor/joshcam/mysqli-database-class/dbObject.php</b> on line <b>303</b><br />
`

I not understand logic of this error , I try dump $this->db and isn't null, not understand.

Please help me

**Comment by avbdr** [comment]
do you have latest dbobject? I remember library had an issue with that in the past. 
You code looks good. Try to make a test on a small test case. I think this exception is coming from somewhere else.

**Comment by KTP95** [comment]
Yeah, i have the last build with composer,
 * @version   2.6-master

**Comment by avbdr** [comment]
sorry, i just noticed

```
        $this->db = MysqliDb::getInstance();
```

you need to use parent::__construct...
