### ISSUE TITLE
Can't delete using byId

### ISSUE THREAD

**Issue by Tom29** [joshcam/PHP-MySQLi-Database-Class#568]
Get this error `( ! ) Fatal error: Using $this when not in object context in` while execute:
`self::byId(1)->delete();`

I use active record pattern, so i put record handling method inside mode object (dbObject).

**Comment by avbdr** [comment]
can you provide a code to reproduce that?

**Comment by Tom29** [comment]
```
class Message extends dbObject
{
  static function deleteMessage($p_id)
    {
	self::byId($p_id)->delete();
	MessageContent::byId($p_id)->delete();	
    }
}
Message::deleteMessage($p_id);
```

**Comment by Tom29** [comment]
Any comment here? I have to work around by creating new object or using `where` and `getOne()` to get the object.

**Comment by ricwein** [comment]
I just took a look at the code. @Tom29 are you sure a object with the given `id` exists in the database?

The `byId()` Method is only a wrapper around  `getOne()`, see: [dbObject.php Line: 304](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.php#L304).
Therefor, if no matching entry is found inside the database, `null` is returned in [dbObject.php Line: 319](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.php#L319), which than leads to this issue.

I suggest a simple workaround calling the `delete()` method:

```php
$item = self::byId($id);
if ($item === null) {
    echo "nothing to do";
} else {
    $item->delete();
}
```

**Comment by Tom29** [comment]
@ricwein I pretty sure that requested `id` is exist in db. I've read the code, and it comes from `static` property. And the error is `( ! ) Fatal error: Using $this when not in object context in` points to line [303](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.php#L303)

It works if i create new instance of the object like this:
```
$msg = new self;
$msg->byId($p_id)->delete();
```

**Comment by ricwein** [comment]
Oh right, obviously you're correct, I just misread the error-message, sorry!

**Comment by avbdr** [comment]
yes, i see the problem __callStatic is not getting called for some reasons. Ill investigate that later

**Comment by Tom29** [comment]
@avbdr `__callStatic` has never been called because `byId` exists in the `dbObject`.
 In my code, `Message` extends `dbObject` so it can access to the `protected` method:`byId()`.

I think it will work perfectly if you change line [302](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/dbObject.php#L302) from `**protected** function byId ($id, $fields = null) {` to `**private** function byId ($id, $fields = null) {`

Now it will call `__callStatic` first.

**Comment by avbdr** [comment]
thats was landed in master awhile ago
