### ISSUE TITLE
Bug in dbObject.php

### ISSUE THREAD

**Issue by bouwehand** [joshcam/PHP-MySQLi-Database-Class#572]
There was 1 error:

1) Anomynousdb\MysqliTest\MysqliTest::testGetRelationObject
Undefined variable: name

C:\repos\anominizer\vendor\joshcam\mysqli-database-class\dbObject.php:381
C:\repos\anominizer\vendor\joshcam\mysqli-database-class\dbObject.php:493
C:\repos\anominizer\src\anomynousdb\Mysqli\test\MysqliTest.php:98
C:\Users\bas\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:185
C:\Users\bas\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:115

**Comment by avbdr** [comment]
what is that?
