### ISSUE TITLE
Can't have username / password property in the dbFields?

### ISSUE THREAD

**Issue by Tom29** [joshcam/PHP-MySQLi-Database-Class#573]
My db table have 2 fields called: username, password.
After creating new object like:

`$admin = new Admin;`

Got error: `Fatal error: Cannot access protected property MysqliDb::$username in `

I think because it conflicts with protected properties: `$username` , `$password` in the Mysqlidb class (use for connecting to the db).

Anyway to avoid it?

**Comment by avbdr** [comment]
thanks. fixed
