### ISSUE TITLE
rawQuery

### ISSUE THREAD

**Issue by Wilou017** [joshcam/PHP-MySQLi-Database-Class#574]
I want

> SELECT `id`, `start` ,`end` ,`title` FROM `ad_calendar_event` where (date(start) >= '2017-01-02' AND date(start) <= '2017-01-09')

I have 

> $db->rawQuery("SELECT `id`, `start` ,`end` ,`title` FROM  `ad_calendar_event` where (date(start) >= '?' AND date(start) <= '?')", array($_GET["start"], $_GET["end"]));

but 

> '?' 

doesn't work 

> Warning:  mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /class/MysqliDb.class.php on line 438

and for

> SELECT `id`, `start` ,`end` ,`title` FROM `ad_calendar_event` where (date(start) >= 2017-01-02 AND date(start) <= 2017-01-09)

(without ' )
I get bad result :l

**Comment by avbdr** [comment]
```
    $db->rawQuery("SELECT id, start ,end ,title FROM ad_calendar_event where (date(start) >= ? AND date(start) <= ?)", array($_GET["start"], $_GET["end"]));
```
