### ISSUE TITLE
 I can't find function SUM.

### ISSUE THREAD

**Issue by sheriff9** [joshcam/PHP-MySQLi-Database-Class#575]
Hi!
I am Aibek, and I use "MysqliDb.php".

Now I can't find function SUM.
I need SUM all column 'price' from table 'models' WHERE 'model_id' == $model_id.

$db->where('model_id', $model_id);
$summa = $db->???? ('models','price');

Can you help me?!

**Comment by ricwein** [comment]
You can pass mysql function keywords inside the `get()`, `getOne()` or even `getValue()` methods like:

```php
$db->where('model_id', $model_id);
$sum = $db->getOne('models', 'sum(price)');
echo 'total price: ' . $sum;
```

See [Documentation: Select Query](https://github.com/joshcam/PHP-MySQLi-Database-Class#select-query) for more details.
