### ISSUE TITLE
LIKE condition

### ISSUE THREAD

**Issue by MazettePatacaisse** [joshcam/PHP-MySQLi-Database-Class#577]
Hello, First of all, a big thank's to your works!

I want to know if the LIKE condition ca be used with getvalue ?
I need to count rows with LIKE condition.
Example:
("select count(*) from email_bans where mail_domain LIKE '%$maildomain%'")
Thank's for your help

**Comment by ATouhou** [comment]
Use rawquery

**Comment by ricwein** [comment]
Or just use `where()`, this should do the job:

```php
$db->where('mail_domain', '%'.$maildomain.'%', 'like');
$bannedCount = $db->getValue('email_bans', 'count(*)');
```

**Comment by MazettePatacaisse** [comment]
thank's for your help!
