### ISSUE TITLE
onDuplicate is not working with insert multi

### ISSUE THREAD

**Issue by KOLEGA007** [joshcam/PHP-MySQLi-Database-Class#578]
```
$db->onDuplicate(["user_id", "group_id"]);
$db->insertMulti(self::getConnectedTable("group"), $item);
```
This didnt work for me. Not sure if it is bug. Solved by foreach. It only prevented the first duplication.

**Comment by salatproduction** [comment]
Duplicate https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/571
