### ISSUE TITLE
save() method doesn't return record id while updating

### ISSUE THREAD

**Issue by Tom29** [joshcam/PHP-MySQLi-Database-Class#579]
I see the `save()` method works well while inserting new record.
But while updating, it returns `1` not the record id.

Does it return true/false instead of record id while updating?

**Comment by ricwein** [comment]
Yes, the `$db->save()` method for existing entries returns an `bool` - `true` if the update succeeded, or `false` if not.

Internal it utilizes the `$db->update()` method for updates and `$db->insert()` for new entries, both methods are documented in the [Readme](https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/readme.md).
