### ISSUE TITLE
Simple $db->get statement from view

### ISSUE THREAD

**Issue by c0degeekPL** [joshcam/PHP-MySQLi-Database-Class#581]
Hello. I have a simple view in my database, made from two tables. When I am trying make a simple query like 

```
$db = new MysqliDb(HOST, USER, PASSWORD, DATABASE);

if ($db->get('person_info_alll')){
    echo "ok";
} else echo $db->getLastError();
```

I have an error: 

> Prepared statement needs to be re-prepared

**Comment by avbdr** [comment]
are you using some function calls before this call?

**Comment by avbdr** [comment]
or maybe stored procedures

**Comment by c0degeekPL** [comment]
Uhm, it is possible, because I am using it in admin dashboard where I am displaying many data from DB.
