### ISSUE TITLE
using MYSQLI_BOTH

### ISSUE THREAD

**Issue by MazettePatacaisse** [joshcam/PHP-MySQLi-Database-Class#582]
Hello,
I'm wondering how using MYSQLI_BOTH with your class??

For exemple with mysql:
$res = "SELECT `id`, `question`, `flag` FROM `faq` WHERE `type`='categ' ORDER BY `order` ASC";
while ($arr = mysql_fetch_array($res, MYSQL_BOTH)) {
 $faq_categ[$arr[id]][title] = $arr[question];
 $faq_categ[$arr[id]][flag] = $arr[flag];
}
Thank's

**Comment by avbdr** [comment]
i dont think this is possible. what are you trying to solve here?
