### ISSUE TITLE
Incorrect Return Value from delete function

### ISSUE THREAD

**Issue by shimscharf** [joshcam/PHP-MySQLi-Database-Class#583]
Hi,
Firstly --> Fantastic wrapper library. Well done!

I noticed that your delete function's return statement is:
return ($stmt->affected_rows > 0);

Problem is that affected_rows returns 0 if operation didn't need to occur, or nothing required updating
It returns -1 if there was an error. 0 is a normal operative value.

I propose the following change to the delete return statement:
return ($stmt->affected_rows > -1);

Or even:
return ($stmt->affected_rows);
which will allow users to test the result themselves.

Keep up the good work!

**Comment by avbdr** [comment]
fixed in master, thanks
