### ISSUE TITLE
Column alias' not working

### ISSUE THREAD

**Issue by joshghent** [joshcam/PHP-MySQLi-Database-Class#585]
Hi there,

I'm running the following query
```php
$columns = array(
'o.orderID',
'u.firstname as Firstname'
);
$db->get('orders o', null, $columns);
```

I've tried passing a string to the ->get method and it still does not work. 
After debugging the process, it is running the correct query (to get the table alias') but I think _dynamicBindResults is messing with it somehow.

**Comment by ricwein** [comment]
So what exactly isn't working?
Does the complete query fail - or does the resulting array-key just has the wrong column name, despite of the alias?

I assume `u.` is a table alias from a previous join, so let's ignore this.

```php
$result= $db->get('orders o', null, [
  'o.orderID as ID',
  'o.firstname as Firstname',
]);
```

should work, and return something like

```json
[
  {
    "ID": 1,
    "Firstname": "test"
  },
  {
    "ID": 2,
    "Firstname": "someoneelse"
  }
]
```

Make sure you're using the current master branch.

**Comment by joshghent** [comment]
@ricwein Yes sorry I should clarify, it returns the column name literally as 'o.firstname as Firstname'!

**Comment by ricwein** [comment]
Okay, thats pretty interesting. Can you please print the output of `$db->getLastQuery()`?

It should be something like this (as you already said in your first post above):
```sql
SELECT  o.orderID, o.firstname as Firstname FROM orders o
```

Even if this is not the fully actual executed query, maybe it helps.

Obviously something while building your query went wrong. And I'm currently unable to reproduce your Problem, everything works as expected. Are you sure you're running the latest master branch?

**Comment by joshghent** [comment]
Yes it was the correct query. 
`SELECT  o.orderID, o.userID, u.firstname as Firstname, u.surname FROM orders o  JOIN user u on u.userID=o.orderID`

I realise the issue though. I am building up a CSV with this information. Since fputcsv does not realise that these are SQL columns it is just inserting the string 'u.firstname as Firstname'. Doh!

Thanks for your help!
