### ISSUE TITLE
when $host is object $db->copy go wrong

### ISSUE THREAD

**Issue by he426100** [joshcam/PHP-MySQLi-Database-Class#586]
error: MySQL host is not set
`
    $dbi = new MysqliDb ([
        'host' => $db->link_id,
        'db'=> $db->db_name,
        'prefix' => $db->prefix
    ]);

`
My English is very bad, do not know if there is a clear expression

**Comment by he426100** [comment]
Why not provide a method, you can pass the array parameters as a query condition, I think so you can avoid the above problem

**Comment by salatproduction** [comment]
$db = new \stdClass?

**Comment by he426100** [comment]
`class cls_mysql {
...
function __construct($dbhost, $dbuser, $dbpw, $dbname = '', $charset = 'gbk', $pconnect = 0, $quiet = 0) {
		$this->cls_mysql($dbhost, $dbuser, $dbpw, $dbname, $charset, $pconnect, $quiet);
	}
...
function connect($dbhost, $dbuser, $dbpw, $dbname = '', $charset = 'utf8', $pconnect = 0, $quiet = 0) {
		if ($pconnect) {
			$this->link_id = new mysqli('p:' . $dbhost, $dbuser, $dbpw);
			if ($this->link_id->connect_error) {
				if (!$quiet) {
					$this->ErrorMsg("Can't pConnect MySQL Server($dbhost)!");
				}

				return false;
			}
		} else {
			$this->link_id = new mysqli($dbhost, $dbuser, $dbpw);

			if ($this->link_id->connect_error) {
				if (!$quiet) {
					$this->ErrorMsg("Can't Connect MySQL Server($dbhost)!");
				}

				return false;
			}
		}
...
}

$db = new cls_mysql();
`

**Comment by he426100** [comment]
I already have a mysql connection class, I want MysqliDb to coexist with him。
For historical reasons, I can not replace the mysql connection in the old code

**Comment by avbdr** [comment]
can you please provide me a test case? 
you can initialize mysqlidb from mysqli object and it should work just fine.
```
$mysqli = new mysqli ('host', 'username', 'password', 'databaseName');
$db = new MysqliDb ($mysqli);
```

**Comment by he426100** [comment]
`
$where = array();
		if ($filter ['to_user_id'] > 0) {
			$where['up.to_user_id'] = $filter['to_user_id'];
		}
		if ($filter ['payment']) {
			$where['up.payment'] = $filter['payment'];
		}
		if ($filter ['is_paid'] != - 1) {
			$where['up.is_paid'] = $filter['is_paid'];
		}
		if ($filter ['keywords']) {
			$where['receive.user_name'] = array('LIKE' => "'%" . mysql_like_quote ( $filter ['keywords'] ) . "%'");
		}
		if ($filter ['user_name']) {
			$where['pay.user_name'] = array('LIKE' => "'%" . mysql_like_quote ( $filter ['user_name'] ) . "%'");
		}
		if (! empty ( $filter ['start_date'] ) && ! empty ( $filter ['end_date'] )) {
			$where['up.paid_time'] = array('>=' => $filter ['start_date']);
			$where['up.paid_time'] = array('<' => $filter ['end_date']);
		}
		$dbi->join('users pay', 'up.user_id = pay.user_id', 'LEFT');
		$dbi->join('users receive', 'up.user_id = receive.user_id', 'LEFT');
		foreach ($where as $key => $value) {
			$dbi->where($key, $value);
		}
        $counter = $dbi->copy();
	    $filter ['record_count'] = $counter->getValue('user_pay up', 'COUNT(*)');
        $dbi->pageLimit = $filter ['page_size'];
	    $list = $dbi->orderBy($filter ['sort_by'], $filter ['sort_order'])->paginate('user_pay up', $filter ['page'], 'up.*, `pay`.`user_name` `user_name_pay`, `pay`.`true_name` `true_name_pay`, `receive`.`user_name` `user_name_receive`, `receive`.`true_name` `true_name_receive`');
`
When i use the copy method is MysqliDb wrong, because this sentence: $ copy -> _ mysqli = null;

**Comment by avbdr** [comment]
duplicate https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/422
