### ISSUE TITLE
INSERT ... ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by VonHirsch** [joshcam/PHP-MySQLi-Database-Class#590]
Hi !  Do you think in the future you might support INSERT ... ON DUPLICATE KEY UPDATE type Update Queries?  

As in here:
https://chartio.com/resources/tutorials/how-to-insert-if-row-does-not-exist-upsert-in-mysql/

using the INSERT ... on duplicate key update syntax:

insert into sakila.actor (actor_id, first_name, last_name, last_update) 
values (50,'NATALIE','SMITH','2013-09-27 12:34:56')
on duplicate key update
  first_name = values(first_name),
  last_name = values(last_name),
  last_update = values(last_update);

**Comment by avbdr** [comment]
it is already supported

**Comment by VonHirsch** [comment]
oh great!! how then?

**Comment by VonHirsch** [comment]
Nevermind I see it - sorry I must have been staring right at it!! :P
