### ISSUE TITLE
Where in array of values

### ISSUE THREAD

**Issue by benck** [joshcam/PHP-MySQLi-Database-Class#593]
In the example, it gives:

`$db->where('id', Array(1, 5, 27, -1, 'd'), 'IN');
$results = $db->get('users');
// Gives: SELECT * FROM users WHERE id IN (1, 5, 27, -1, 'd');`

It works, but only the simple array with index from 0,1,2,3..., it does not take array with indexes. For example, I have an array of:
`$arr = array(34 => 504, 36 => 501);`

and it will be parsed as:
`UPDATE user SET `current` = ? WHERE  id 34 ?`

 It's easy to fix, just put $arr = array_values($arr); before sending into the function. However, it would be nice if if could be included in the library.

**Comment by VeNoMouS** [comment]
IMHO that's you being lazy , you wouldn't write a mysql query in the CLI that way, so why do you expect the class to accept your dirty input and clean it for you?

just my 2 cents.

**Comment by benck** [comment]
I couldn't find the bug initially, because the array was fed by other functions. However, your suggestions will work, thanks!

$results = $db->where('id', array_values($arr_fed_by_other_class), 'IN')->get('users');

**Comment by 31337Ghost** [comment]
+1
