### ISSUE TITLE
Add socket configuring

### ISSUE THREAD

**Issue by srgraham** [joshcam/PHP-MySQLi-Database-Class#596]
The `mysqli::__construct()` function allows you to pass a socket as the final argument. It would be useful to be able to pass that variable through `MySQLiDB::__construct()`

https://github.com/joshcam/PHP-MySQLi-Database-Class/blob/master/MysqliDb.php#L281
```php
$this->_mysqli = new mysqli($this->host, $this->_username, $this->_password, $this->db, $this->port);
```

**Comment by avbdr** [comment]
new patch just landed. thank you!
