### ISSUE TITLE
Usage of keywords for columns

### ISSUE THREAD

**Issue by lupus92** [joshcam/PHP-MySQLi-Database-Class#599]
It is not possible to use keywords for columns (perhaps also for tables). Is this a bug or a (missing) feature? Would be very nice when column names like "key" are possible, maybe by added \`  \` for column and table names.

**Comment by salatproduction** [comment]
?? [Result transformation](https://github.com/joshcam/PHP-MySQLi-Database-Class#result-transformation--map)
