### ISSUE TITLE
Close Connection after a query?

### ISSUE THREAD

**Issue by Saim1** [joshcam/PHP-MySQLi-Database-Class#607]
I want to know how to close a connection after I am done with certain queires.
Because my database is crossing its connection limits after few hours in run. 
So How to overcome that?

**Comment by avbdr** [comment]
:) i were working on this yesterday. Pushed to the master just right now

**Comment by ricwein** [comment]
This class opens a *mysqli* connection when initializing a new object of itself (actually not until running your first query), and automatically closes it, when destructing the object again.

```php
$db = new MysqliDb(/*...*/);
$result = $db->get('table'); // opens internal mysqli connection to database

$db = null; // destructing the Class object also releases the mysqli database connection
```

Alternatively you can force close the connection manually:
```php
$db->mysqli()->close();
```

> But be aware: this call will open a new connection **if it's not currently opened**, just to close it again.

Since this classes should correctly handle it's own db connection, I guess you have a bug somewhere on your side. Maybe some never ending cronjobs or so.

**Comment by ricwein** [comment]
@avbdr was faster 👍  You'll get a better way of disconnecting manually soon

**Comment by Saim1** [comment]
Thanks @avbdr and @ricwein 

you both the champs :+1:

**Comment by Saim1** [comment]
@ricwein Yes cron are on a continuous loop. But resetting the connection might not go ahead of connection limit set to 250. At the moment it goes beyond 1000+ and mysql crashes. So resting will help, even if it is a persisting job?

**Comment by avbdr** [comment]
@Saim1, im using this disconnect() method on a project where script runs all the time and doing asyncronous tasks. Works as expected for quite a long time.

**Comment by Saim1** [comment]
@avbdr and in this you are using which of the following method? $db = null; or $db->mysqli()->close();

**Comment by avbdr** [comment]
im using $db->disconnect() that i just commited to master

**Comment by avbdr** [comment]
see https://github.com/joshcam/PHP-MySQLi-Database-Class/commit/90f26fb2ef7ac9b894dff03b75d98ee30e069395

**Comment by Saim1** [comment]
@avbdr Thanks again for your help. Have a good day.
