### ISSUE TITLE
limit rows value show in single quotes

### ISSUE THREAD

**Issue by masterkamlesh** [joshcam/PHP-MySQLi-Database-Class#611]
// initilize all variable
$param = $params = $columns = $totalRecords = $data = $posts = $response = array();

$i=1;
$params = $_REQUEST;

//define index of column
$columns = array( 
	0 => 'id', 
	1 => 'name',
	2 => 'mobile',
	3 => 'email',
	4 => 'status'
);

$where = $sqlTot = $sqlRec = "";
$where = $sqlTot = $sqlRec = "";

// check search value exist
if( !empty($params['search']['value']) ) {   
	$where .= " WHERE l.name like ? or l.mobile like ? or l.email like ?";
}

// getting total number records without any search
$sql = "SELECT l.id,l.name,mobile,email,lr.role as role,l.active  FROM login as l inner join login_roles as lr on lr.id=l.role";
//echo $sql;
$sqlTot .= $sql;
$sqlRec .= $sql;
//concatenate search sql if value exist
if(isset($where) && $where != '') {

	$sqlTot .= $where;
	$sqlRec .= $where;
	$searchVar = '%'. $params['search']['value'].'%';
	array_push($param,$searchVar);
	array_push($param,$searchVar);
	array_push($param,$searchVar);
	
}

$sqlRec .=  " ORDER BY ? ASC LIMIT ?,? ";
  array_push($param,$columns[$params['order'][0]['column']]);
  array_push($param,$params['start']);
  array_push($param,$params['length']);
//	$queryTot = mysqli_query($conn, $sqlTot) or die("database error:". mysqli_error($conn));
$db->rawQuery($sqlTot,$param);
//	echo "Last executed query was ". $db->getLastQuery();
//print_r($param);
$totalRecords = $db->count;
$users = $db->rawQuery($sqlRec,$param);
echo "Last executed query was ". $db->getLastQuery();
//print_r($param);
//iterate on results row and create new index array of data
$i= $params['start']+1;
foreach($users as $user)
{
$posts = array("sno" => $i, "id" => $user['id'],"name" => $user['name'],"mobile" => $user['mobile'],"email" => $user['email'],"role" => $user['role'],"active" => $user['active']=='1'?'active':'inactive');
$data[] = $posts;
$i++;
}
/*while( $row = mysqli_fetch_assoc($queryRecords) ) {
$posts = array("sno" => $i, "id" => $row['id'],"name" => $row['name'],"mobile" => $row['mobile'],"email" => $row['email'],"role" => $row['role'],"active" => $row['active']=='1'?'active':'inactive');
$data[] = $posts;
$i++;
}	*/

$json_data = array(
		"draw"            => intval( $params['draw'] ),   
		"recordsTotal"    => intval( $totalRecords ),  
		"recordsFiltered" => intval($totalRecords),
		"data"            => $data   // total data array

		);

echo json_encode($json_data);  // send data as json format
##last executed query
SELECT l.id,l.name,mobile,email,lr.role as role,l.active FROM login as l inner join login_roles as lr on lr.id=l.role WHERE l.name like '%a%' or l.mobile like '%a%' or l.email like '%a%' ORDER BY 'id' ASC LIMIT '0','10'

why 'id' ASC LIMIT '0','10' are showing in single quotes. ??

**Comment by avbdr** [comment]
read readme about getLastQuery
