### ISSUE TITLE
Why SQL_CALC_FOUND_ROWS? This method is not slow?

### ISSUE THREAD

**Issue by temamagic** [joshcam/PHP-MySQLi-Database-Class#614]
Which is fastest? SELECT SQL_CALC_FOUND_ROWS FROM `table`, or SELECT COUNT(*)
Many people say that SQL_CALC_FOUND_ROWS is almost always slower, sometimes up to 10 times slower than two queries.
Is it worth using this method?

**Comment by avbdr** [comment]
in my tests i never saw SQL_CALC_FOUND_ROWS performing worse then count(*). 
but you can make your benchmarks for your case and decide which way works better for you.

**Comment by temamagic** [comment]
@avbdr Perhaps I read the old information about it. Thx u !

**Comment by avbdr** [comment]
yes, i think you did. As I remember the  big difference were happening with mysql earlier then 4.5 or something like that.

**Comment by dzpt** [comment]
@avbdr SQL_CALC_FOUND_ROWS is significantly slower than COUNT(*) on the table has >200k records.
below that threshold, using SQL_CALC_FOUND_ROWS is fine.

if you would like to review , i'm going to send the pull request.
