### ISSUE TITLE
Bug on $db->rawQuery while trying to use ALTER TABLE

### ISSUE THREAD

**Issue by thingNumber1** [joshcam/PHP-MySQLi-Database-Class#615]
I have a table named `rank` with the permissions of users, one of then is `view_template`. This permission basically define wich templates can be seen by a user depending of his/her rank and is database is only a SET type field with the list of templates.

So, I execute this code in order to get an array with of all the fields templates created:

	$listOfTemplates = $db->rawQuery("SHOW COLUMNS FROM rank LIKE 'view_template'");
	$listOfTemplates = explode("','", substr($listOfTemplates[0]['Type'], 5, -2));
	// Return something like: 
	// array('coolTemplate','niceTemplate');

And when I want to create a new template I excecute:

	$listOfTemplates[] = 'awesomeTemplate';
	$aux = "'". implode("','", $listOfTemplates) . "'";
	$result = $db->rawQuery('ALTER TABLE `rank` CHANGE `view_template` `view_template` SET( ? ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;', $aux);

But I get this error message: 

	Fatal error:  Uncaught exception 'Exception' with message 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL' at line 1 query: ALTER TABLE `rank` CHANGE `view_template` `view_template` SET( ? ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;' in C:\xampp\htdocs\catholic\model\vendor\joshcam\mysqli-database-class\MysqliDb.php:1844`

Also tried ` implode("','", $listOfTemplates) ;` instead of `"'". implode("','", $listOfTemplates) . "'";` but I get the same error message.

The curiosus thing is that works find if I try to do it directly with:

	$listOfTemplates[] = 'awesomeTemplate';
	$aux = "'". implode("','", $listOfTemplates) . "'";
	$result = $db->rawQuery("ALTER TABLE `rank` CHANGE `view_template` `view_template` SET( $aux ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;");

**Comment by ricwein** [comment]
The second Parameter of `rawQuery()` is expected to be an array, containing all variables which should be bind to the query. So in your case it should work with:

```php
$result = $db->rawQuery('ALTER TABLE `rank` CHANGE `view_template` `view_template` SET( ? ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;', array($aux));
```
