### ISSUE TITLE
Destructor closes mysqli connection

### ISSUE THREAD

**Issue by leigh-ols** [joshcam/PHP-MySQLi-Database-Class#622]
It would be nice to have an option to prevent this,... Or perhaps just remove it entirely.

It causes issues in various cases especially when attempting to run SQL in other classes `__destruct` methods that depend on `MysqliDb`.

`mysqli` will close itself with garbage collection anyway.

**Comment by avbdr** [comment]
i agree. can you please submit a pull request?

**Comment by avbdr** [comment]
pushed thanks
