### ISSUE TITLE
Mistake in Regexp

### ISSUE THREAD

**Issue by Momenoor** [joshcam/PHP-MySQLi-Database-Class#623]
case "bool":
                    $regexp = "/^[yes|no|0|1|true|false]$/i";
                    break;
Located in dbObject Line no.657

it must replace [ ] to be ( ) to work correctly

**Comment by avbdr** [comment]
thanks for a finding. can you please submit a pull request with added testcase into tests/ file?

**Comment by avbdr** [comment]
fixed thanks
