### ISSUE TITLE
Create Database Table

### ISSUE THREAD

**Issue by iahnn** [joshcam/PHP-MySQLi-Database-Class#625]
Hi,

I wonder if it is possible to create database table using this? i tried using the $mysqli->query() but i cant make it work to create a table.

**Comment by iahnn** [comment]
I wanted to do query like this

> $query = "CREATE TABLE IF NOT EXISTS `" . TABLE_PREFIX . "settings` (
		`ID` bigint(20) NOT NULL AUTO_INCREMENT,
		`meta_key` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
		`meta_value` varchar(255) COLLATE utf8_unicode_ci NULL,
		PRIMARY KEY (`ID`)
	) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;";
    $db->rawQuery($query);

I wonder if that's possible? Thanks.

**Comment by avbdr** [comment]
this should work. I'm using same thing in tests/ files.
