### ISSUE TITLE
Bug on dbObject->with($objectName)

### ISSUE THREAD

**Issue by tuananh77** [joshcam/PHP-MySQLi-Database-Class#626]
I think there is a mistake at line 386 in the function dbObject->with($objectName)
Currently
`if (!property_exists ($this, 'relations') && !isset ($this->relations[$name]))`
The correct conditions should be
`if (!property_exists ($this, 'relations') || !isset ($this->relations[$objectName]))`

Correct me if I'm wrong.
This wrapper is great, and exactly what I need. Excellent work.
Thank you.

**Comment by avbdr** [comment]
thanks for your finding. can you please submit a pull request with added testcase into tests/ file?
