### ISSUE TITLE
Bug: orderBy method does not allow ordering by custom field names containing spaces

### ISSUE THREAD

**Issue by leigh-ols** [joshcam/PHP-MySQLi-Database-Class#630]
```SQL
SELECT CONCAT('',a.date_created,'',DATE_FORMAT(a.date_created,'%d/%m/%Y')) AS 'Order Date',
FROM my_table
ORDER BY `Order Date`
```
Is valid SQL

However doing
```php
$db->orderBy('Order Date');
```

Results in the SQL query having:
```SQL
ORDER BY OrderDate
```

Note how `Order Date` became `OrderDate` which is a non-existant field and returns an SQL error.

This is due to the regex in the orderBy method stripping out spaces.

**Comment by avbdr** [comment]
thanks, fixed

**Comment by leigh-ols** [comment]
Ugh,... this is still an issue. It appears my solution only half fixed the problem.

`ORDER BY` fields that contain spaces need to be wrapped with backticks in order for mysql to correctly sort the results.

**Comment by leigh-ols** [comment]
This is more complex than it first appears. Simply wrapping backticks around the field will not work, because you can have multiple comma separated columns resulting in `` `date,name` `` when what you wanted was `` `date`,`name` ``.

We could explode this on the `,` and trim any whitespace to solve this, but we also have to consider `a.date,b.name` which would result in `` `a.date`,`b.name` ``, which is also wrong. 
To fix this we could then explode the already exploded results on a `.` to get `` a.`date`,b.`name` `` Which is correct until we try something like: ``My.Field.Alias``, or ``My,field,alias`` which would get incorrectly exploded and wrapped.

Ultimately what we want is to end up with results like this:
```
ORDER BY `date`
ORDER BY `date`,`name`
ORDER BY a.`date`,b.`name`
ORDER BY `Start Date`, `End Date`
ORDER BY `Start,Date`,`End.Date`
```

But this may become very complex, very quickly. So i'm curious to hear what others here think is the best approach.
