### ISSUE TITLE
Undefined Method disconnect()

### ISSUE THREAD

**Issue by wdrleo** [joshcam/PHP-MySQLi-Database-Class#632]
Hi,
This disconnect method in the [document](https://github.com/joshcam/PHP-MySQLi-Database-Class#helper-methods) does not exist in the class. I try using get error 
`Uncaught Error: Call to undefined method MysqliDb::disconnect()`

**Comment by avbdr** [comment]
disconnect() is not a static method. as well, seems you are using an old version of the library

**Comment by wdrleo** [comment]
@avbdr Yes, I'm using this version 2.7. Thanks for reply. 
Good day.
