### ISSUE TITLE
Number of Rows.

### ISSUE THREAD

**Issue by GovetaXV** [joshcam/PHP-MySQLi-Database-Class#635]
How to get the number of rows??
The Following is my code:

      $db->where ("username", $this->username);
      $db->where ("password", $this->password);
      $user = $db->getOne ("users");

I want to know if it returns 1 row or more.

**Comment by ricwein** [comment]
The `getOne()` method always returns only a single row (as the name suggests).

If you want to select multiple rows, use `get()` instead. You can use a simple `count()` to get the number of select rows:

```php
$db->where ("username", $this->username);
$db->where ("password", $this->password);
$users = $db->get("users");

echo "rows: " . count($users);
```

**Comment by GovetaXV** [comment]
Thanks Alot!!
