### ISSUE TITLE
where() error

### ISSUE THREAD

**Issue by GovetaXV** [joshcam/PHP-MySQLi-Database-Class#639]
I keep on getting the following:

`Fatal error: Uncaught Error: Call to a member function where() on null in C:\xampp\htdocs\IceDuo\API\app\appdata\private\accounts\login.class.php:61 Stack trace: #0 C:\xampp\htdocs\IceDuo\API\app\app.php(34): loginData->getData() #1 C:\xampp\htdocs\IceDuo\API\index.php(6): GET(Array) #2 {main} thrown in C:\xampp\htdocs\IceDuo\API\app\appdata\private\accounts\login.class.php on line 61`

The following is my code:

```
$db->where("id", 2);
$user = $this->db->get("users");
```

**Comment by cfachinelli** [comment]
i think the correct should be

```
$this->db->where("id", 2);
$user = $this->db->get("users");
```

the mysqlidb object is in $this->db variable, not the local $db;
