### ISSUE TITLE
return StdClass in Query

### ISSUE THREAD

**Issue by Barno** [joshcam/PHP-MySQLi-Database-Class#64]
I have a stdClass instead of an array?

`$query = $this->db
            ->where('email', $email)
            ->where('password',$password)
            ->get('users');`

i try with
`$obj = (object) $query;`

but dosen't works, my obj is empty

**Comment by avbdr** [comment]
more info is in https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/211
