### ISSUE TITLE
get() not working from view

### ISSUE THREAD

**Issue by wdrleo** [joshcam/PHP-MySQLi-Database-Class#641]
Hi,
I use native mysqli i can get data from view table. But i can't get data from view with PHP-MySQLi-Database-Class. 
Other queries are working normally but i dont datas from view. 

I  working on PHP version 5.6

I need urgent help. @joshcam

**Comment by avbdr** [comment]
what is the problem?

**Comment by sonrakiyazilimci** [comment]
I have a **table view** as;
`select `p`.`id` AS `id`,`p`.`price` AS `price`,`p`.`coid` AS `coid`,`p`.`cid` AS `cid`,(select `co`.`name` from `project_db`.`country` `co` where (`co`.`id` = `p`.`coid`)) AS `coname`,(select `ci`.`name` AS `ciname` from `project_db`.`city` `ci` where (`ci`.`id` = `p`.`cid`)) AS `ciname`,(select `tr`.`name` from `project_db`.`transactions` `tr` where (`tr`.`id` = `p`.`tid`)) AS `tid`,`p`.`deleted_at` AS `deleted_at` from `project_db`.`prices` `p``
 
**I execute query  on mysql with phpmyadmin;**
`SELECT * FROM `prices_view` WHERE coid = '3'  AND cid = '1' 

_return results as;_

id	price	coid	cid	coname	ciname	tid	deleted_at	
1	370.00	3	1	Almanya	Adana	Konsolosluk + Aracı Kurum Ücreti		
2	15.00	3	1	Almanya	Adana	Kargo Ücreti		
3	140.00	3	1	Almanya	Adana	Servis Ücreti		

**But execute some query with joshcam/MySQLi**

`Array
(
    [0] => Array
        (
            [0] => SELECT  * FROM prices_view WHERE  coid = '3'  AND cid = '1' 
            [1] => 0.0010271072387695
            [2] => MysqliDb->get() >>  file "x.php" line #69 
        )

)` 

_I get **empty** result._

**Comment by avbdr** [comment]
it works just fine with a vew

**Comment by Mrbrand** [comment]
I have the same problem. I get nothing from my view-table.

**Comment by avbdr** [comment]
do a simple test.php with print_r (get("myview")); and then go back to your original code and search for a bug

**Comment by Mrbrand** [comment]
print_r (get("myview")) returns

>  array()

**Comment by avbdr** [comment]
what php and mysql version you are using?

**Comment by Mrbrand** [comment]
php v5.3

**Comment by sonrakiyazilimci** [comment]
@avbdr PHP 7.1 - MySQL 5.6.36 The problem continues.
