### ISSUE TITLE
Pagination for rawQuery

### ISSUE THREAD

**Issue by brecht2727** [joshcam/PHP-MySQLi-Database-Class#643]
I'm stuck in writing code for a rawQuery in combination with pagination:

This is the query:
`$products` = $db->rawQuery ("SELECT * FROM products WHERE maincat = '$maincat'");

This query above is working correct but if i will have pagination, how can i do this?
```
$page = 1;
$db->pageLimit = 10;
$products = $db->rawQuery ("SELECT * FROM products WHERE maincat = '$maincat'");
echo "showing $page out of " . $db->totalPages;
```
And after that i will have the pages like this (clickable of course):
1 2 3 4 5 6 ...

**Comment by avbdr** [comment]
pagination functionality is not possible with rawQuery.
see for a code how to do it https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/518
