### ISSUE TITLE
Updating with null value

### ISSUE THREAD

**Issue by jeffstagedoor** [joshcam/PHP-MySQLi-Database-Class#645]
when performing an update with an data array containing a NULL this will be converted to a string 'NULL', thus failing on a field defined as date (with default NULL).

db:
```
CREATE TABLE `expenses` (
      `id` int(11) NOT NULL,
      ....
     `invoiceNumber` varchar(50) DEFAULT NULL,
     `invoiceDate` date DEFAULT NULL,
     `invoiceIBAN` varchar(30) NOT NULL, 
      ...
)
```
an 
`$this->db->update('expenses', $data);`
with `$data['invoiceData'] = NULL;`

results in:
```
UPDATE expenses SET `invoiceNumber` = '', `invoiceDate` = 'NULL', `invoiceIBAN` = '',... WHERE  id = '1'
```

**Comment by avbdr** [comment]
are you using latest stable release? I think thats quite an old issue

**Comment by mshs013** [comment]
It works when I updated replacePlaceHolders function by bellow

`protected function replacePlaceHolders($str, $vals)
    {
        $i = 1;
        $newStr = "";

        if (empty($vals)) {
            return $str;
        }

        while ($pos = strpos($str, "?")) {
            $val = $vals[$i++];
            if (is_object($val)) {
                $val = '[object]';
            }
            
            if($val === null) {
                $newStr .= substr($str, 0, $pos) . 'NULL';
            } else {
                $newStr .= substr($str, 0, $pos) . "'" . $val . "'";
            }
            
            $str = substr($str, $pos + 1);
        }
        $newStr .= $str;
        return $newStr;
    }`
