### ISSUE TITLE
Mistake at MysqliDb::_buildLimit($numRows) function

### ISSUE THREAD

**Issue by tuananh77** [joshcam/PHP-MySQLi-Database-Class#646]
The comments for the function say

> `@param int|array $numRows Array to define SQL limit in format Array ($count, $offset) or only $count`

And this is the code

> `$this->_query .= ' LIMIT ' . (int) $numRows[0] . ', ' . (int) $numRows[1];`

In fact, the syntax of LIMIT in MySQL is `LIMIT [offset,] count` which means in the code above, the parameters are placed in wrong order, or the comments are not consistent with the actual code.

**Comment by avbdr** [comment]
thanks. fixed comments in master
