### ISSUE TITLE
Unsigned zerofill int value returned int

### ISSUE THREAD

**Issue by tonny-sofijan** [joshcam/PHP-MySQLi-Database-Class#647]
My table have unsigned zerofill primary key. Fetched value is int:
e.g. data on table = **`000001`** but fetched data is **`1`**

**Comment by ricwein** [comment]
This is the correct behavior of [mysqli prepared statements](https://stackoverflow.com/questions/6825106/php-mysql-zerofill-is-lost-when-using-mysqli-prepare), which are utilized in this library. The returned field are interpreted as pure php-integers, which don't support zerofills.

Just use phps [`str_pad()`](https://secure.php.net/manual/en/function.str-pad.php), if you want to zerofill you integers:

```php
$result = $db->get(...);
$number = $result['number']; // int

$zerofilledNumber = str_pad((string) $number, 6, '0', STR_PAD_LEFT); // string
```

**Comment by tonny-sofijan** [comment]
I see. OK, noted. I'll use str_pad. Thanks for the info!
