### ISSUE TITLE
Versión PHP 5.5 Min

### ISSUE THREAD

**Issue by Oxicode** [joshcam/PHP-MySQLi-Database-Class#649]
+1

**Comment by avbdr** [comment]
What is the question?

**Comment by Oxicode** [comment]
Que la versión mínima de uso sea PHP 5.5. Por ejemplo usamos array cortos [], mejoras en performance, entre muchas otras cosas.

**Comment by avbdr** [comment]
Lo dudo que tiene razón que subir versión mínima. Hay varios usuarios de la librería con PHP viejo. 
Yo utilizo la librería con varios versión de PHP también.

**Comment by Oxicode** [comment]
El problema radica que si sigues dando soporte a versiones viejas de PHP, nunca se impulsará las nuevas.
