### ISSUE TITLE
Two or more query in same function

### ISSUE THREAD

**Issue by Barno** [joshcam/PHP-MySQLi-Database-Class#65]
this is my my class

    require_once ('class/MysqliDb.php');

    class Foo {
    
        private  $db;
    
        public function __construct()
        {
            $this->db = MySqliDb::getInstance();
        }
    }
    
     public function register($password, $email) {
    
            $password = @sha1($password);
    
            $query = $this->db
                ->where('email', $email)
                ->get('users');
    
            if (count($query) == 0)
            {
    
                $insertData = array(
                    'email' => $email,
                    'password' => $password
                );
    
                if($this->db->insert('users', $insertData)){
                    return true;
                }
    
            }else{
                return FALSE;
            }
        }

I save in Db (if `count($query) == 0`) but I also receive this error

    ( ! ) Notice: Undefined property: MysqliDb::$_paramTypeList in /.../class/MysqliDb.php on line 356

if I do not write this query

    $query = $this->db
                    ->where('email', $email)
                    ->get('users');

I Haven't error.
Can I Do multi Query in the single function ? And how i have this error `MysqliDb::$_paramTypeList`

**Comment by avbdr** [comment]
this should be working now. Could be closed
