### ISSUE TITLE
loadData SQL Statement not allowed/possible on shared hostings

### ISSUE THREAD

**Issue by DragonflyNet67** [joshcam/PHP-MySQLi-Database-Class#652]
I just tried to import a CSV File into a table by using loadData() and all its options necessary. On a shared hosting server (like mine is) the necessary permission (FILE) cannot be granted to a user. So MySql returns with an error message "#1045 - Access denied for user...". Also changing the SQL-Statement to LOAD DATA **LOCAL** INFILE does not change anything. There's no way to use LOAD DATA on a shared hosting (since the FILE permission is a server-wide setting on shared-hosting). That's what my hoster/provider told me based on a request by granting FILE permission to a certain User. So XML Load probably would also not work.

**Comment by jefvhal** [comment]
Same issue here. Seems to be fixed when adding the LOCAL keyword

MysqliDb.php line 981
"LOAD DATA INFILE" => "LOAD DATA LOCAL INFILE"

Perhaps this should be done with a optional switch.

**Comment by Noneatme** [comment]
Is that a fault within the wrapper? It seems to me that this problem is a hosting problem with your server hoster.

**Comment by DragonflyNet67** [comment]
I don't think so. The Problem is, that LOAD DATA needs FILE permission for the DB User. And that's the main problem. On shared hosters FILE Permission is a global setting for all clients (as they told me on the phone) and they do not give the possibility for FILE Permission to none of the DB-Users (for every client). The wrapper itself does not more than a standart LOAD DATA Command. Which works fine on my local machine, but not for my website residing on a shared hoster. I added another routine to the wrapper where the CSV-Files are splitted and uses INSERT Commands for each line. This way I do not need the FILE Permission for LOAD DATA, since they would not give it to any client on their shared host.

Thank you

**Comment by avbdr** [comment]
i doubt that we can do anything with this issue
