### ISSUE TITLE
Call stored Procedure

### ISSUE THREAD

**Issue by hibbert-de** [joshcam/PHP-MySQLi-Database-Class#66]
Ho do I call a stored procedure?

$params = array('param 1',2);
$db->rawQuery("CALL my_func(?,?)",$params)

The result is:
Fatal error: Problem preparing query (CALL my_func(?,?) LIMIT 1) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' ...

I have removed the LIMIT 1 statement, but it still don't work.

How can I call stored procedures?

**Comment by hibbert-de** [comment]
bump...again....

**Comment by avbdr** [comment]
fixed in master. thanks
