### ISSUE TITLE
Verify database connection

### ISSUE THREAD

**Issue by biswajitpaul01** [joshcam/PHP-MySQLi-Database-Class#664]
How can I check or throw an error that database is connected properly after this code:

$db = new MysqliDb ('host', 'username', 'password', 'databaseName');

I also added this code to verify connection but it does not return any error.
if ($db->connect_error) {
            die( 'Error establishing database connection.' );
}

**Comment by avbdr** [comment]
if (!$db->ping())

**Comment by biswajitpaul01** [comment]
Thanks. I got it.
