### ISSUE TITLE
Fatal error: Class 'MysqliDb' not found in /home/highl608/public_html/sys/include-all.php on line 12

### ISSUE THREAD

**Issue by zabih01** [joshcam/PHP-MySQLi-Database-Class#671]
It's working properly on my localhost, but whenever i upload my files on my online server then i get the above mentioned error.
I have used this class in my whole project. Help me out.
Thanks...!!
The line 12 code is:
`$mysqli = new mysqli ('localhost', 'highl608_u', 'VmA,17510e', 'highl608');
$db       = new MysqliDb ($mysqli);`

This is my server link:
https://sys.highlandadventure.net/index.php

**Comment by avbdr** [comment]
you have a problem with your require string. maybe case sensivity issue

**Comment by zabih01** [comment]
Thanks. Can u explain with example ?
