### ISSUE TITLE
BUG: Uncaught Error: Wrong parameters for Exception

### ISSUE THREAD

**Issue by HerrWurstwasser** [joshcam/PHP-MySQLi-Database-Class#677]
Hi,

When I Run This (expand)
<details>
$__USER = $db->where("d.puidDevice", $_SERVER["HTTP_AUTH_NAME"])
                ->where("d.expiringDevice < NOW()")
                ->where("d.expiringDevice IS null", null, null, "OR")

                ->join("users u", "u.idUser = d.fkUser", "INNER")

                ->getOne("devices d", "d.tokenDevice, u.idUser, u.emailUser, u.nameUser");
</details>

I get this Stacktrace
<details>
<b>Notice</b>:  Use of undefined constant error - assumed 'error' in <b>/home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php</b> on line <b>1919</b><br />
<b>Notice</b>:  Use of undefined constant query - assumed 'query' in <b>/home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php</b> on line <b>1919</b><br />
<b>Notice</b>:  Use of undefined constant errno - assumed 'errno' in <b>/home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php</b> on line <b>1919</b><br />
<b>Fatal error</b>:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php:1919
Stack trace:
#0 /home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php(1919): Exception-&gt;__construct('error query: qu...', 'errno')
#1 /home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php(1512): MysqliDb-&gt;_prepareQuery()
#2 /home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php(679): MysqliDb-&gt;_buildQuery(1)
#3 /home/bjarne/PhpstormProjects/Umfrager/vendor/joshcam/mysqli-database-class/MysqliDb.php(704): MysqliDb-&gt;get('devices d', 1, 'd.tokenDevice, ...')
#4 /home/bjarne/PhpstormProjects/Umfrager/api/init.php(48): MysqliDb-&gt;getOne('devices d', 'd.tokenDevice, ...')
</details>

It seems like that the exception is not my fault. Maybe there is a bugfix

> Thanks!
> HerrWurstwasser

**Comment by avbdr** [comment]
please pull latest master :)

**Comment by HerrWurstwasser** [comment]
Nope, I am already on d87decd63f8695ff07c7843766a4690fd692f0d1

**Comment by avbdr** [comment]
Yes, and the fix is in the next commit

**Comment by HerrWurstwasser** [comment]
Ok, when do you think composer will fetch the next commit? Does composer directly fetch from master branch or is there another composer branch?

**Comment by HerrWurstwasser** [comment]
Composer dev-master still is on d87decd63f8695ff07c7843766a4690fd692f0d1
See [Packagist](https://packagist.org/packages/joshcam/mysqli-database-class#dev-master)

**Comment by avbdr** [comment]
should be fixed. thanks
