### ISSUE TITLE
what is get again after getValue with one where

### ISSUE THREAD

**Issue by hoangnamitc** [joshcam/PHP-MySQLi-Database-Class#678]
Hi adm,

My problem is: I want use again $db->where for two $db->get and $db->getValue ?

Example: 
$db->where('hide', 1);
$db->where('active', 1)

$db->getValue('table', 'count(id)'); // oke

$data = $db->get('table', null, '*'); // not working with ->where above

Thanks !

**Comment by avbdr** [comment]
Your particular example could be resolved using withTotalCount() method.
To run same queries on the same set of conditions it's also possible using copy() method

**Comment by hoangnamitc** [comment]
Thanks @avbdr ! :)

My problem has been resolved with copy() method !
