### ISSUE TITLE
Q: named parameters

### ISSUE THREAD

**Issue by michabbb** [joshcam/PHP-MySQLi-Database-Class#682]
hi @joshcam , sorry, i was not able to find it in the readme, so i ask: does this project support named parameters ? i know mysqli itself does not, but maybe you made a wrapper for this. thanks.

**Comment by avbdr** [comment]
there are no named placeholders unfortunately. I wanted to add them, but never managed to start

**Comment by michabbb** [comment]
@avbdr okay, thanks for the quick feedback ;)

**Comment by michabbb** [comment]
@avbdr i was going to build a new mysqli wrapper for mysqlf, but your project is nearly perfect i guess, the only thing that blocks me, is the missing feature of named-paramters. i used a super old class `MDB2` which emulates the named paramters perfectly. the code is super old, but i guess the part of parsing the query, still works perfect. if i would provide a pull request in the future, are you open for that ? 😏

**Comment by avbdr** [comment]
named placeholders is what I been missing for years but been too lazy to implement that.
If you will come up with a pull request, ill be happy to accept it. 
Thanks

**Comment by michabbb** [comment]
@avbdr turned out, names placeholders are not that difficult as expected. PEAR::MDB2 did a great job, that´s where i got the code from, [feel free to use it](https://github.com/michabbb/mysqlihelper/blob/e88c644b940f745f71149baca649902c977cf8ed/MySQLiBase.php#L263). because this framework here is way too heavy for me, i decided to start my own 😏
