### ISSUE TITLE
Like Clause 

### ISSUE THREAD

**Issue by abdulmanan7** [joshcam/PHP-MySQLi-Database-Class#685]
Like class need to be something like $db->like()

**Comment by avbdr** [comment]
It's in readme

**Comment by abdulmanan7** [comment]
i searched the readme but not found any like statement

**Comment by avbdr** [comment]
Haha. Indeed Need to add :)
```
Db->where('a', '%test%');
```

**Comment by avbdr** [comment]
Db->where('a', '%test%', 'like');

**Comment by abdulmanan7** [comment]
i was searching "like" LOL thanks dude for your quick support.
i would suggest to implement it like $Db->like()
it would be more readable .

**Comment by avbdr** [comment]
added to readme
