### ISSUE TITLE
Showing Fatal error when using where() method at same time in two different methods

### ISSUE THREAD

**Issue by ahmedali5530** [joshcam/PHP-MySQLi-Database-Class#69]
Hi there i m having trouble in using where method, when i use where() method in 2 of my methods, and when i call those methods at same time it gives me error of:
"Fatal error: Problem preparing query ( WHERE lot_id = ?) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE lot_id = ?' at line 1 in D:\Program Files\XAMPP\htdocs\bootstrap\inc\bootstrap.php on line 467".

Please tell me about this issue.
Thanks in advance.

**Comment by avbdr** [comment]
lot of code were since time bugreport were created. I cant imagine a case when this can happen now.
