### ISSUE TITLE
Insert array to database with null - escaping to string

### ISSUE THREAD

**Issue by Ajtak** [joshcam/PHP-MySQLi-Database-Class#693]
I use
```
$obj = array([
  "barcode"=> "123456",
  "sn" => null,
]);

$this->db->insert('items', $obj);
```
then "sn" is nullable unique varchar datetype in database. 
Library convert null to string, as "null". If I can echo last query, its same as

`INSERT INTO items(barcode, sn) VALUES ("123456", "null");`

Its possible fix it?
Thank you.

**Comment by avbdr** [comment]
Try latest stable version. Should be fixedong time ago

**Comment by Ajtak** [comment]
Not working. I made a simple fix on line 1969:
```
$query = substr($str, 0, $pos) . "'" . $val . "'";
$newStr .= str_replace("'NULL'", "NULL", $query) ;
```

**Comment by avbdr** [comment]
thats not a fix getLastQuery() wont return you same query that it would actually insert. 
Test an actual insert() and read readme

**Comment by Ajtak** [comment]
Yes , Im testing insert, but was error for duplicates key sn (it's NULL string)
