### ISSUE TITLE
Insert fails

### ISSUE THREAD

**Issue by ehudg** [joshcam/PHP-MySQLi-Database-Class#72]
Hi

The insert command doesnt work:

if(!$db->insert('footer_menu', $db_data)) echo 'error!'; 

Always return error.

In the core code:

public function insert($tableName, $insertData)
    {
        $this->_query = "INSERT into $tableName";
        $stmt = $this->_buildQuery(null, $insertData);
        $stmt->execute();
        $this->reset();

    ---->    return ($stmt->affected_rows > 0 ? $stmt->insert_id : false);
    }
The data is good but I always get back error.

Please help!

**Comment by avbdr** [comment]
fixed in master long time ago.
