### ISSUE TITLE
Problems with qoutes on update

### ISSUE THREAD

**Issue by lgt** [joshcam/PHP-MySQLi-Database-Class#74]
I try to execute the following query setting up first imploded qouted values but fails

<code>
 function add_quotes($str) {
        return sprintf('"%s"', $str);
    }

    public function updateCategory($ids, $new_cat_name) {

     $imploded = implode(',',array_map(array($this,'add_quotes'), $ids));
     $resutls = $this->db->query("UPDATE __cat_product SET category = ".$new_cat_name." WHERE product_id IN(". $imploded .")");
     echo $this->db->getSql();

    }
</code>

**Comment by avbdr** [comment]
use 
```
 $resutls = $this->db->rawQuery("UPDATE __cat_product SET category = ".$new_cat_name." WHERE product_id IN(". $imploded .")",null, false); 
```
and better switch to prepared statements. 
```
$db->where ("product_id", $ids, 'in');
$db->update(" __cat_product", ['category' => $new_cat_name]);
```
