### ISSUE TITLE
Problem when dbfield < ? is used

### ISSUE THREAD

**Issue by hasibiqbal** [joshcam/PHP-MySQLi-Database-Class#76]
Hello,

In case of raw query, if we use dbfield < ? than FILTER_SANITIZE_STRING removes < while running filter_var

example database query:

select * from tablename where dbfield < 100;

example code
$param = array(100);
$query = "select * from tablename where dbfield < ?";
dbclass->rawQuery($query, $param);

**Comment by avbdr** [comment]
workaround added.
```php
$param = array(100);
$query = "select * from tablename where dbfield < ?";
dbclass->rawQuery($query, $param, false);
```
