### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by danielcorrea** [joshcam/PHP-MySQLi-Database-Class#79]
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4294967296 bytes) in /home/abeporgb/public_html/encontro/_classes/mysqli/dbMySqli.php on line 594

#594
call_user_func_array(array($stmt, 'bind_result'), $parameters);

what might be happening?

**Comment by avbdr** [comment]
can anybody provide a reproducible testcase for this? I mean query + sample table structure + sample data?

**Comment by ramjamx** [comment]
@avbdr  Update version solve my problem even with longtext. thank you.

**Comment by avbdr** [comment]
great then :) @danielcorrea can you confirm that latest version fixes issue for you too?

**Comment by azizjassar** [comment]
what is the latest version ??

**Comment by azizjassar** [comment]
i made the changes with latest version of the myqlidb class but the same problem. but when i set the memory limit to 512M it's fine. and i hope that the problem is gonna be ending at this

**Comment by avbdr** [comment]
just pull the latest master.

**Comment by azizjassar** [comment]
i downloaded the latest version but the problem still the same. but when i change the memory limit from 256M to 512M it works

**Comment by avbdr** [comment]
how many records you are pulling out?

**Comment by azizjassar** [comment]
i don't know where is the problem exatly. so i can't find out how much result i'm pulling out

**Comment by pquerner** [comment]
Its too much data to process. You cant take the script to handle it for you. Its your system.

**Comment by avbdr** [comment]
i have a feeling that this bug is mostly not related to a library but about big amounts of data peoples are trying to select with 1 select. Maybe as a workaround to this problem we need to come up with one more get() which will be performing multiple selects with limit in the background.

Also im still not sure if we need to call mysql_store_result() for all the queries.

**Comment by pquerner** [comment]
I dont think thats really helping the issue here.
Sure, it doesnt try to have it all in one select, but once you're finished you have this big array data which is floating somewhere in memory.
This is a programmatic error, not some error of a 3rd party library in my opinion.

**Comment by danielcorrea** [comment]
Yep :-)
