### ISSUE TITLE
mysqli_stmt::bind_result(): Server returned unknown type 245. 

### ISSUE THREAD

**Issue by huseyinaslim** [joshcam/PHP-MySQLi-Database-Class#791]
Hi,
I try get records from database table with json datatype column. But i get this error message;

`Warning: mysqli_stmt::bind_result(): Server returned unknown type 245. Probably your client library is incompatible with the server version you use! in /home/project/public_html/vendor/joshcam/mysqli-database-class/MysqliDb.php on line 1578`

**MysqliDb.php on line 1578:**
`call_user_func_array(array($stmt, 'bind_result'), $parameters);`

**I Use code for get data with MysqliDb Class; but not working for json column and get error message**

```
$result = $db->get('specs');
echo '<pre>', print_r($result), '</pre>';
```

**Output:**

```
Warning: mysqli_stmt::bind_result(): Server returned unknown type 245. Probably your client library is incompatible with the server version you use! in /home/project/public_html/vendor/joshcam/mysqli-database-class/MysqliDb.php on line 1578
Array
(
    [0] => Array
        (
            [id] => 1
            [name] => kilometer
            [type] => 
        )

)
```

**I try native query code is working;**
```
$mysqli = new mysqli("localhost", "user", "pass", "db");
$result = $mysqli->query("SELECT * FROM el_specs");
```

**Output:**
```
Array
(
    [id] => 1
    [name] => Kilometer
    [type] => {"items": [{"bool": false, "name": "Regina", "email": "danielle@vincent.yt", "float": 18.517, "index": 1, "integer": 32, "surname": "Jennings", "fullname": "Alice Bowman", "index_start_at": 56}]}
)
```

**_Server PHP Version: 7.2
Server MySQL Version:  5.1.73
MysqliDb Version: 2.9.2_**

**specs Table**
```
id       | INT | AI
name | VARCHAR
type   | JSON
```

**Comment by VeNoMouS** [comment]
https://bugs.php.net/bug.php?id=70384

**Comment by VeNoMouS** [comment]
@huseyinaslim this is a bug with PHP not the library.

**Comment by VeNoMouS** [comment]
As a workaround, cast the json as varchar.

**Comment by VeNoMouS** [comment]
If your going to raise a bug report with PHP i suggest you link https://bugs.php.net/bug.php?id=70384
