### ISSUE TITLE
Warning: mysqli_stmt::bind_param(): Number of elements in type definition string doesn't match number of bind variables

### ISSUE THREAD

**Issue by prabhakaran0225** [joshcam/PHP-MySQLi-Database-Class#82]
I am trying to use where in clause but getting warning
Warning: mysqli_stmt::bind_param(): Number of elements in type definition string doesn't match number of bind variables

This is the code I have used

           $samples = (1,2,3,4,5);
       $mydb->where("psit_img_id",  array("in", $samples));
       $data = array("Sample"=>1);
       $mydb->update("ProcessDetail",$data);

How can I resolve it.

**Comment by avbdr** [comment]
please close
