### ISSUE TITLE
mysql_ping

### ISSUE THREAD

**Issue by brostm** [joshcam/PHP-MySQLi-Database-Class#84]
hi
i use this db class in my script.
Script must work some days with mysql.
in second day script goes down.
In log i see
HY000: [MySQL][ODBC 5.1 Driver]MySQL server has gone away
How i can check DB connection and reconnect if down?
php community recommends use mysql_ping.
How can use mysql_ping in DB Class?

**Comment by avbdr** [comment]
already fixed. Please close
