### ISSUE TITLE
Feature Request: Sql Transaction

### ISSUE THREAD

**Issue by scazzy** [joshcam/PHP-MySQLi-Database-Class#86]
Add Feature for Commit and Roll back.
I had written this code in your older version, so haven't modified yet to send a pull req.

=============================================
    /**
     * Set auto_commit off
     *
     * @return TRUE or FALSE 
     */
    public function autoCommit($mode = TRUE)
    {
        return $this->_mysqli->autocommit($mode);
    }

    /**
     * Set Commit Transaction
     *
     * @return TRUE or FALSE 
     */
    public function commit($auto_commit_ON = false)
    {
        $response = $this->_mysqli->commit();

		if($auto_commit_ON === true){
			// restart auto_commit
			$this->autoCommit();
		}
		return $response;
    }

    /**
     * Set Rollback Transaction
     *
     * @return TRUE or FALSE 
     */
    public function rollback($auto_commit_ON = false)
    {
        $response = $this->_mysqli->rollback();
		
		if($auto_commit_ON === true){
			// restart auto_commit
			$this->autoCommit();
		}
		return $response;
    }

**Comment by avbdr** [comment]
transaction api is landed already. please close
