### ISSUE TITLE
Undefined property: MysqliDb::$_paramTypeList

### ISSUE THREAD

**Issue by ghost** [joshcam/PHP-MySQLi-Database-Class#87]
Usually I get 
( ! ) Notice: Undefined property: MysqliDb::$_paramTypeList in /.../class/MysqliDb.php

Here is the same issue 
http://stackoverflow.com/questions/20941107/error-mysqlidb-paramtypelist

**Comment by avbdr** [comment]
can you still reproduce that with latest master?

**Comment by avbdr** [comment]
that should be fixed long time ago
