### ISSUE TITLE
Error on RawQuery when call a procedure

### ISSUE THREAD

**Issue by MarioCares** [joshcam/PHP-MySQLi-Database-Class#97]
I'm calling a procedure like this:
```php
$results = $this->handler->rawQuery("call BEP(?);", array($obj["Rango"]));
return $results;
```
But, it shows => 
![Alt text](https://pbs.twimg.com/media/BjvoCbfCYAAXnVo.png:large)

It, in fact call, the procedure and get the info ... but that weird message is driving me crazy

**Comment by boomware** [comment]
Did you find the solution? I have the same problem.

**Comment by boomware** [comment]
add this line $stmt->close();
after "return" in method "_dynamicBindResults"

**Comment by avbdr** [comment]
fixed in master
